//! `ApiVersionsRequest` — generated from `schemas/ApiVersionsRequest.json`.
//!
//! @generated by `cargo xtask codegen`. Do not edit by hand.

#![allow(
    clippy::field_reassign_with_default,
    clippy::nonminimal_bool,
    clippy::derivable_impls,
    clippy::borrow_deref_ref,
    clippy::double_parens,
    unused_parens
)]

use bytes::{Buf, BufMut};

#[allow(unused_imports)]
use crate::error::{DecodeError, EncodeError};
use crate::wire::{self, RawTaggedField};

/// Whether `version` of this message uses the flexible (compact) encoding.
pub fn is_flexible(version: i16) -> bool {
    let _ = version;
    version >= 3
}

/// `ApiVersionsRequest`, versions 0-4.
#[derive(Debug, Clone, PartialEq)]
#[non_exhaustive]
pub struct ApiVersionsRequest {
    /// The name of the client.
    pub client_software_name: String,
    /// The version of the client.
    pub client_software_version: String,
    /// Tagged fields not (yet) known to this crate, kept raw.
    pub unknown_tagged_fields: Vec<RawTaggedField>,
}

impl Default for ApiVersionsRequest {
    fn default() -> Self {
        Self {
            client_software_name: String::new(),
            client_software_version: String::new(),
            unknown_tagged_fields: Vec::new(),
        }
    }
}

impl ApiVersionsRequest {
    pub const API_KEY: i16 = 18;
    pub const MIN_VERSION: i16 = 0;
    pub const MAX_VERSION: i16 = 4;

    pub fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        if version >= 3 {
            if is_flexible(version) {
                wire::put_compact_string(buf, &self.client_software_name);
            } else {
                wire::put_string(buf, &self.client_software_name)?;
            }
        }
        if version >= 3 {
            if is_flexible(version) {
                wire::put_compact_string(buf, &self.client_software_version);
            } else {
                wire::put_string(buf, &self.client_software_version)?;
            }
        }
        if is_flexible(version) {
            wire::put_tagged_fields(buf, &self.unknown_tagged_fields);
        }
        Ok(())
    }

    pub fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        let mut this = Self::default();
        if version >= 3 {
            this.client_software_name = if is_flexible(version) {
                wire::get_compact_string(buf)?
            } else {
                wire::get_string(buf)?
            };
        }
        if version >= 3 {
            this.client_software_version = if is_flexible(version) {
                wire::get_compact_string(buf)?
            } else {
                wire::get_string(buf)?
            };
        }
        if is_flexible(version) {
            this.unknown_tagged_fields = wire::get_tagged_fields(buf)?;
        }
        Ok(this)
    }
}

impl crate::Message for ApiVersionsRequest {
    const API_KEY: i16 = 18;
    const MIN_VERSION: i16 = 0;
    const MAX_VERSION: i16 = 4;

    fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        ApiVersionsRequest::encode(self, buf, version)
    }
    fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        ApiVersionsRequest::decode(buf, version)
    }
}
