//! `ApiVersionsResponse` — generated from `schemas/ApiVersionsResponse.json`.
//!
//! @generated by `cargo xtask codegen`. Do not edit by hand.
//!
//! Tagged fields not yet materialized (they round-trip through
//! `unknown_tagged_fields`): ApiVersionsResponse.SupportedFeatures (tag 0), ApiVersionsResponse.FinalizedFeaturesEpoch (tag 1), ApiVersionsResponse.FinalizedFeatures (tag 2), ApiVersionsResponse.ZkMigrationReady (tag 3).

#![allow(
    clippy::field_reassign_with_default,
    clippy::nonminimal_bool,
    clippy::derivable_impls
)]

use bytes::{Buf, BufMut};

#[allow(unused_imports)]
use crate::error::{DecodeError, EncodeError};
use crate::wire::{self, RawTaggedField};

/// Whether `version` of this message uses the flexible (compact) encoding.
pub fn is_flexible(version: i16) -> bool {
    let _ = version;
    version >= 3
}

/// `ApiVersionsResponse`, versions 0-4.
#[derive(Debug, Clone, PartialEq)]
pub struct ApiVersionsResponse {
    /// The top-level error code.
    pub error_code: i16,
    /// The APIs supported by the broker.
    pub api_keys: Vec<ApiVersion>,
    /// The duration in milliseconds for which the request was throttled due to a quota violation, or zero if the request did not violate any quota.
    pub throttle_time_ms: i32,
    /// Tagged fields not (yet) known to this crate, kept raw.
    pub unknown_tagged_fields: Vec<RawTaggedField>,
}

impl Default for ApiVersionsResponse {
    fn default() -> Self {
        Self {
            error_code: 0,
            api_keys: Vec::new(),
            throttle_time_ms: 0,
            unknown_tagged_fields: Vec::new(),
        }
    }
}

impl ApiVersionsResponse {
    pub const API_KEY: i16 = 18;
    pub const MIN_VERSION: i16 = 0;
    pub const MAX_VERSION: i16 = 4;

    pub fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        buf.put_i16(self.error_code);
        if is_flexible(version) {
            wire::put_compact_array_len(buf, Some(self.api_keys.len()));
        } else {
            wire::put_array_len(buf, Some(self.api_keys.len()))?;
        }
        for item in &self.api_keys {
            item.encode(buf, version)?;
        }
        if version >= 1 {
            buf.put_i32(self.throttle_time_ms);
        }
        if is_flexible(version) {
            wire::put_tagged_fields(buf, &self.unknown_tagged_fields);
        }
        Ok(())
    }

    pub fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        let mut this = Self::default();
        this.error_code = wire::get_i16(buf)?;
        this.api_keys = {
            let len = if is_flexible(version) {
                wire::get_compact_array_len(buf)?
            } else {
                wire::get_array_len(buf)?
            };
            match len {
                None => return Err(DecodeError::InvalidLength(-1)),
                Some(n) => {
                    let mut items = Vec::new();
                    for _ in 0..n {
                        items.push(ApiVersion::decode(buf, version)?);
                    }
                    items
                }
            }
        };
        if version >= 1 {
            this.throttle_time_ms = wire::get_i32(buf)?;
        }
        if is_flexible(version) {
            this.unknown_tagged_fields = wire::get_tagged_fields(buf)?;
        }
        Ok(this)
    }
}

/// `ApiVersion` (nested in [`ApiVersionsResponse`]).
#[derive(Debug, Clone, PartialEq)]
pub struct ApiVersion {
    /// The API index.
    pub api_key: i16,
    /// The minimum supported version, inclusive.
    pub min_version: i16,
    /// The maximum supported version, inclusive.
    pub max_version: i16,
    /// Tagged fields not (yet) known to this crate, kept raw.
    pub unknown_tagged_fields: Vec<RawTaggedField>,
}

impl Default for ApiVersion {
    fn default() -> Self {
        Self {
            api_key: 0,
            min_version: 0,
            max_version: 0,
            unknown_tagged_fields: Vec::new(),
        }
    }
}

impl ApiVersion {
    pub fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        buf.put_i16(self.api_key);
        buf.put_i16(self.min_version);
        buf.put_i16(self.max_version);
        if is_flexible(version) {
            wire::put_tagged_fields(buf, &self.unknown_tagged_fields);
        }
        Ok(())
    }

    pub fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        let mut this = Self::default();
        this.api_key = wire::get_i16(buf)?;
        this.min_version = wire::get_i16(buf)?;
        this.max_version = wire::get_i16(buf)?;
        if is_flexible(version) {
            this.unknown_tagged_fields = wire::get_tagged_fields(buf)?;
        }
        Ok(this)
    }
}

/// `SupportedFeatureKey` (nested in [`ApiVersionsResponse`]).
#[derive(Debug, Clone, PartialEq)]
pub struct SupportedFeatureKey {
    /// The name of the feature.
    pub name: String,
    /// The minimum supported version for the feature.
    pub min_version: i16,
    /// The maximum supported version for the feature.
    pub max_version: i16,
    /// Tagged fields not (yet) known to this crate, kept raw.
    pub unknown_tagged_fields: Vec<RawTaggedField>,
}

impl Default for SupportedFeatureKey {
    fn default() -> Self {
        Self {
            name: String::new(),
            min_version: 0,
            max_version: 0,
            unknown_tagged_fields: Vec::new(),
        }
    }
}

impl SupportedFeatureKey {
    pub fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        if version >= 3 {
            if is_flexible(version) {
                wire::put_compact_string(buf, &self.name);
            } else {
                wire::put_string(buf, &self.name)?;
            }
        }
        if version >= 3 {
            buf.put_i16(self.min_version);
        }
        if version >= 3 {
            buf.put_i16(self.max_version);
        }
        if is_flexible(version) {
            wire::put_tagged_fields(buf, &self.unknown_tagged_fields);
        }
        Ok(())
    }

    pub fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        let mut this = Self::default();
        if version >= 3 {
            this.name = if is_flexible(version) {
                wire::get_compact_string(buf)?
            } else {
                wire::get_string(buf)?
            };
        }
        if version >= 3 {
            this.min_version = wire::get_i16(buf)?;
        }
        if version >= 3 {
            this.max_version = wire::get_i16(buf)?;
        }
        if is_flexible(version) {
            this.unknown_tagged_fields = wire::get_tagged_fields(buf)?;
        }
        Ok(this)
    }
}

/// `FinalizedFeatureKey` (nested in [`ApiVersionsResponse`]).
#[derive(Debug, Clone, PartialEq)]
pub struct FinalizedFeatureKey {
    /// The name of the feature.
    pub name: String,
    /// The cluster-wide finalized max version level for the feature.
    pub max_version_level: i16,
    /// The cluster-wide finalized min version level for the feature.
    pub min_version_level: i16,
    /// Tagged fields not (yet) known to this crate, kept raw.
    pub unknown_tagged_fields: Vec<RawTaggedField>,
}

impl Default for FinalizedFeatureKey {
    fn default() -> Self {
        Self {
            name: String::new(),
            max_version_level: 0,
            min_version_level: 0,
            unknown_tagged_fields: Vec::new(),
        }
    }
}

impl FinalizedFeatureKey {
    pub fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        if version >= 3 {
            if is_flexible(version) {
                wire::put_compact_string(buf, &self.name);
            } else {
                wire::put_string(buf, &self.name)?;
            }
        }
        if version >= 3 {
            buf.put_i16(self.max_version_level);
        }
        if version >= 3 {
            buf.put_i16(self.min_version_level);
        }
        if is_flexible(version) {
            wire::put_tagged_fields(buf, &self.unknown_tagged_fields);
        }
        Ok(())
    }

    pub fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        let mut this = Self::default();
        if version >= 3 {
            this.name = if is_flexible(version) {
                wire::get_compact_string(buf)?
            } else {
                wire::get_string(buf)?
            };
        }
        if version >= 3 {
            this.max_version_level = wire::get_i16(buf)?;
        }
        if version >= 3 {
            this.min_version_level = wire::get_i16(buf)?;
        }
        if is_flexible(version) {
            this.unknown_tagged_fields = wire::get_tagged_fields(buf)?;
        }
        Ok(this)
    }
}
