//! `ApiVersionsResponse` — generated from `schemas/ApiVersionsResponse.json`.
//!
//! @generated by `cargo xtask codegen`. Do not edit by hand.
//!
//! Tagged fields are materialized as `Option` struct fields (`None` = absent
//! on the wire); unknown tags still round-trip through `unknown_tagged_fields`.

#![allow(
    clippy::field_reassign_with_default,
    clippy::nonminimal_bool,
    clippy::derivable_impls,
    clippy::borrow_deref_ref,
    clippy::double_parens,
    unused_parens
)]

use bytes::{Buf, BufMut};

#[allow(unused_imports)]
use crate::error::{DecodeError, EncodeError};
use crate::wire::{self, RawTaggedField};

/// Whether `version` of this message uses the flexible (compact) encoding.
pub fn is_flexible(version: i16) -> bool {
    let _ = version;
    version >= 3
}

/// `ApiVersionsResponse`, versions 0-4.
#[derive(Debug, Clone, PartialEq)]
#[non_exhaustive]
pub struct ApiVersionsResponse {
    /// The top-level error code.
    pub error_code: i16,
    /// The APIs supported by the broker.
    pub api_keys: Vec<ApiVersion>,
    /// The duration in milliseconds for which the request was throttled due to a quota violation, or zero if the request did not violate any quota.
    pub throttle_time_ms: i32,
    /// Features supported by the broker. Note: in v0-v3, features with MinSupportedVersion = 0 are omitted.
    /// (Tagged field 0; `None` = absent on the wire.)
    pub supported_features: Option<Vec<SupportedFeatureKey>>,
    /// The monotonically increasing epoch for the finalized features information. Valid values are >= 0. A value of -1 is special and represents unknown epoch.
    /// (Tagged field 1; `None` = absent on the wire.)
    pub finalized_features_epoch: Option<i64>,
    /// List of cluster-wide finalized features. The information is valid only if FinalizedFeaturesEpoch >= 0.
    /// (Tagged field 2; `None` = absent on the wire.)
    pub finalized_features: Option<Vec<FinalizedFeatureKey>>,
    /// Set by a KRaft controller if the required configurations for ZK migration are present.
    /// (Tagged field 3; `None` = absent on the wire.)
    pub zk_migration_ready: Option<bool>,
    /// Tagged fields not (yet) known to this crate, kept raw.
    pub unknown_tagged_fields: Vec<RawTaggedField>,
}

impl Default for ApiVersionsResponse {
    fn default() -> Self {
        Self {
            error_code: 0,
            api_keys: Vec::new(),
            throttle_time_ms: 0,
            supported_features: None,
            finalized_features_epoch: None,
            finalized_features: None,
            zk_migration_ready: None,
            unknown_tagged_fields: Vec::new(),
        }
    }
}

impl ApiVersionsResponse {
    pub const API_KEY: i16 = 18;
    pub const MIN_VERSION: i16 = 0;
    pub const MAX_VERSION: i16 = 4;

    pub fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        buf.put_i16(self.error_code);
        if is_flexible(version) {
            wire::put_compact_array_len(buf, Some(self.api_keys.len()));
        } else {
            wire::put_array_len(buf, Some(self.api_keys.len()))?;
        }
        for item in &self.api_keys {
            item.encode(buf, version)?;
        }
        if version >= 1 {
            buf.put_i32(self.throttle_time_ms);
        }
        if is_flexible(version) {
            let mut tagged = self.unknown_tagged_fields.clone();
            if version >= 3 {
                if let Some(v) = &self.supported_features {
                    let mut tag_data = bytes::BytesMut::new();
                    {
                        let buf = &mut tag_data;
                        if is_flexible(version) {
                            wire::put_compact_array_len(buf, Some((*v).len()));
                        } else {
                            wire::put_array_len(buf, Some((*v).len()))?;
                        }
                        for item in &(*v) {
                            item.encode(buf, version)?;
                        }
                    }
                    tagged.push(RawTaggedField {
                        tag: 0,
                        data: tag_data.freeze(),
                    });
                }
            }
            if version >= 3 {
                if let Some(v) = &self.finalized_features_epoch {
                    let mut tag_data = bytes::BytesMut::new();
                    {
                        let buf = &mut tag_data;
                        buf.put_i64((*v));
                    }
                    tagged.push(RawTaggedField {
                        tag: 1,
                        data: tag_data.freeze(),
                    });
                }
            }
            if version >= 3 {
                if let Some(v) = &self.finalized_features {
                    let mut tag_data = bytes::BytesMut::new();
                    {
                        let buf = &mut tag_data;
                        if is_flexible(version) {
                            wire::put_compact_array_len(buf, Some((*v).len()));
                        } else {
                            wire::put_array_len(buf, Some((*v).len()))?;
                        }
                        for item in &(*v) {
                            item.encode(buf, version)?;
                        }
                    }
                    tagged.push(RawTaggedField {
                        tag: 2,
                        data: tag_data.freeze(),
                    });
                }
            }
            if version >= 3 {
                if let Some(v) = &self.zk_migration_ready {
                    let mut tag_data = bytes::BytesMut::new();
                    {
                        let buf = &mut tag_data;
                        buf.put_u8(u8::from((*v)));
                    }
                    tagged.push(RawTaggedField {
                        tag: 3,
                        data: tag_data.freeze(),
                    });
                }
            }
            tagged.sort_by_key(|f| f.tag);
            wire::put_tagged_fields(buf, &tagged);
        }
        Ok(())
    }

    pub fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        let mut this = Self::default();
        this.error_code = wire::get_i16(buf)?;
        this.api_keys = {
            let len = if is_flexible(version) {
                wire::get_compact_array_len(buf)?
            } else {
                wire::get_array_len(buf)?
            };
            match len {
                None => return Err(DecodeError::InvalidLength(-1)),
                Some(n) => {
                    let mut items = Vec::new();
                    for _ in 0..n {
                        items.push(ApiVersion::decode(buf, version)?);
                    }
                    items
                }
            }
        };
        if version >= 1 {
            this.throttle_time_ms = wire::get_i32(buf)?;
        }
        if is_flexible(version) {
            for raw in wire::get_tagged_fields(buf)? {
                if raw.tag == 0 && (version >= 3) {
                    let mut tag_data = raw.data;
                    let buf = &mut tag_data;
                    this.supported_features = Some({
                        let len = if is_flexible(version) {
                            wire::get_compact_array_len(buf)?
                        } else {
                            wire::get_array_len(buf)?
                        };
                        match len {
                            None => return Err(DecodeError::InvalidLength(-1)),
                            Some(n) => {
                                let mut items = Vec::new();
                                for _ in 0..n {
                                    items.push(SupportedFeatureKey::decode(buf, version)?);
                                }
                                items
                            }
                        }
                    });
                    if buf.has_remaining() {
                        return Err(DecodeError::InvalidLength(
                            i64::try_from(buf.remaining()).unwrap_or(i64::MAX),
                        ));
                    }
                } else if raw.tag == 1 && (version >= 3) {
                    let mut tag_data = raw.data;
                    let buf = &mut tag_data;
                    this.finalized_features_epoch = Some(wire::get_i64(buf)?);
                    if buf.has_remaining() {
                        return Err(DecodeError::InvalidLength(
                            i64::try_from(buf.remaining()).unwrap_or(i64::MAX),
                        ));
                    }
                } else if raw.tag == 2 && (version >= 3) {
                    let mut tag_data = raw.data;
                    let buf = &mut tag_data;
                    this.finalized_features = Some({
                        let len = if is_flexible(version) {
                            wire::get_compact_array_len(buf)?
                        } else {
                            wire::get_array_len(buf)?
                        };
                        match len {
                            None => return Err(DecodeError::InvalidLength(-1)),
                            Some(n) => {
                                let mut items = Vec::new();
                                for _ in 0..n {
                                    items.push(FinalizedFeatureKey::decode(buf, version)?);
                                }
                                items
                            }
                        }
                    });
                    if buf.has_remaining() {
                        return Err(DecodeError::InvalidLength(
                            i64::try_from(buf.remaining()).unwrap_or(i64::MAX),
                        ));
                    }
                } else if raw.tag == 3 && (version >= 3) {
                    let mut tag_data = raw.data;
                    let buf = &mut tag_data;
                    this.zk_migration_ready = Some(wire::get_bool(buf)?);
                    if buf.has_remaining() {
                        return Err(DecodeError::InvalidLength(
                            i64::try_from(buf.remaining()).unwrap_or(i64::MAX),
                        ));
                    }
                } else {
                    this.unknown_tagged_fields.push(raw);
                }
            }
        }
        Ok(this)
    }
}

impl crate::Message for ApiVersionsResponse {
    const API_KEY: i16 = 18;
    const MIN_VERSION: i16 = 0;
    const MAX_VERSION: i16 = 4;

    fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        ApiVersionsResponse::encode(self, buf, version)
    }
    fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        ApiVersionsResponse::decode(buf, version)
    }
}

/// `ApiVersion` (nested in [`ApiVersionsResponse`]).
#[derive(Debug, Clone, PartialEq)]
#[non_exhaustive]
pub struct ApiVersion {
    /// The API index.
    pub api_key: i16,
    /// The minimum supported version, inclusive.
    pub min_version: i16,
    /// The maximum supported version, inclusive.
    pub max_version: i16,
    /// Tagged fields not (yet) known to this crate, kept raw.
    pub unknown_tagged_fields: Vec<RawTaggedField>,
}

impl Default for ApiVersion {
    fn default() -> Self {
        Self {
            api_key: 0,
            min_version: 0,
            max_version: 0,
            unknown_tagged_fields: Vec::new(),
        }
    }
}

impl ApiVersion {
    pub fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        buf.put_i16(self.api_key);
        buf.put_i16(self.min_version);
        buf.put_i16(self.max_version);
        if is_flexible(version) {
            wire::put_tagged_fields(buf, &self.unknown_tagged_fields);
        }
        Ok(())
    }

    pub fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        let mut this = Self::default();
        this.api_key = wire::get_i16(buf)?;
        this.min_version = wire::get_i16(buf)?;
        this.max_version = wire::get_i16(buf)?;
        if is_flexible(version) {
            this.unknown_tagged_fields = wire::get_tagged_fields(buf)?;
        }
        Ok(this)
    }
}

/// `SupportedFeatureKey` (nested in [`ApiVersionsResponse`]).
#[derive(Debug, Clone, PartialEq)]
#[non_exhaustive]
pub struct SupportedFeatureKey {
    /// The name of the feature.
    pub name: String,
    /// The minimum supported version for the feature.
    pub min_version: i16,
    /// The maximum supported version for the feature.
    pub max_version: i16,
    /// Tagged fields not (yet) known to this crate, kept raw.
    pub unknown_tagged_fields: Vec<RawTaggedField>,
}

impl Default for SupportedFeatureKey {
    fn default() -> Self {
        Self {
            name: String::new(),
            min_version: 0,
            max_version: 0,
            unknown_tagged_fields: Vec::new(),
        }
    }
}

impl SupportedFeatureKey {
    pub fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        if version >= 3 {
            if is_flexible(version) {
                wire::put_compact_string(buf, &self.name);
            } else {
                wire::put_string(buf, &self.name)?;
            }
        }
        if version >= 3 {
            buf.put_i16(self.min_version);
        }
        if version >= 3 {
            buf.put_i16(self.max_version);
        }
        if is_flexible(version) {
            wire::put_tagged_fields(buf, &self.unknown_tagged_fields);
        }
        Ok(())
    }

    pub fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        let mut this = Self::default();
        if version >= 3 {
            this.name = if is_flexible(version) {
                wire::get_compact_string(buf)?
            } else {
                wire::get_string(buf)?
            };
        }
        if version >= 3 {
            this.min_version = wire::get_i16(buf)?;
        }
        if version >= 3 {
            this.max_version = wire::get_i16(buf)?;
        }
        if is_flexible(version) {
            this.unknown_tagged_fields = wire::get_tagged_fields(buf)?;
        }
        Ok(this)
    }
}

/// `FinalizedFeatureKey` (nested in [`ApiVersionsResponse`]).
#[derive(Debug, Clone, PartialEq)]
#[non_exhaustive]
pub struct FinalizedFeatureKey {
    /// The name of the feature.
    pub name: String,
    /// The cluster-wide finalized max version level for the feature.
    pub max_version_level: i16,
    /// The cluster-wide finalized min version level for the feature.
    pub min_version_level: i16,
    /// Tagged fields not (yet) known to this crate, kept raw.
    pub unknown_tagged_fields: Vec<RawTaggedField>,
}

impl Default for FinalizedFeatureKey {
    fn default() -> Self {
        Self {
            name: String::new(),
            max_version_level: 0,
            min_version_level: 0,
            unknown_tagged_fields: Vec::new(),
        }
    }
}

impl FinalizedFeatureKey {
    pub fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        if version >= 3 {
            if is_flexible(version) {
                wire::put_compact_string(buf, &self.name);
            } else {
                wire::put_string(buf, &self.name)?;
            }
        }
        if version >= 3 {
            buf.put_i16(self.max_version_level);
        }
        if version >= 3 {
            buf.put_i16(self.min_version_level);
        }
        if is_flexible(version) {
            wire::put_tagged_fields(buf, &self.unknown_tagged_fields);
        }
        Ok(())
    }

    pub fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        let mut this = Self::default();
        if version >= 3 {
            this.name = if is_flexible(version) {
                wire::get_compact_string(buf)?
            } else {
                wire::get_string(buf)?
            };
        }
        if version >= 3 {
            this.max_version_level = wire::get_i16(buf)?;
        }
        if version >= 3 {
            this.min_version_level = wire::get_i16(buf)?;
        }
        if is_flexible(version) {
            this.unknown_tagged_fields = wire::get_tagged_fields(buf)?;
        }
        Ok(this)
    }
}
