//! `DeleteTopicsResponse` — generated from `schemas/DeleteTopicsResponse.json`.
//!
//! @generated by `cargo xtask codegen`. Do not edit by hand.

#![allow(
    clippy::field_reassign_with_default,
    clippy::nonminimal_bool,
    clippy::derivable_impls,
    clippy::borrow_deref_ref,
    clippy::double_parens,
    unused_parens
)]

use bytes::{Buf, BufMut};

use crate::budget::{Budget, Limits};
#[allow(unused_imports)]
use crate::error::{DecodeError, EncodeError};
use crate::wire::{self, RawTaggedField};

/// Whether `version` of this message uses the flexible (compact) encoding.
pub fn is_flexible(version: i16) -> bool {
    let _ = version;
    version >= 4
}

/// `DeleteTopicsResponse`, versions 1-6.
#[derive(Debug, Clone, PartialEq)]
#[non_exhaustive]
pub struct DeleteTopicsResponse {
    /// The duration in milliseconds for which the request was throttled due to a quota violation, or zero if the request did not violate any quota.
    pub throttle_time_ms: i32,
    /// The results for each topic we tried to delete.
    pub responses: Vec<DeletableTopicResult>,
    /// Tagged fields not (yet) known to this crate, kept raw.
    pub unknown_tagged_fields: Vec<RawTaggedField>,
}

impl Default for DeleteTopicsResponse {
    fn default() -> Self {
        Self {
            throttle_time_ms: 0,
            responses: Vec::new(),
            unknown_tagged_fields: Vec::new(),
        }
    }
}

impl DeleteTopicsResponse {
    /// This message's api key in Kafka's registry.
    pub const API_KEY: i16 = 20;
    /// The lowest schema version this snapshot can speak.
    pub const MIN_VERSION: i16 = 1;
    /// The highest schema version this snapshot can speak.
    pub const MAX_VERSION: i16 = 6;

    /// Encode this `DeleteTopicsResponse` at `version`.
    pub fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        buf.put_i32(self.throttle_time_ms);
        if is_flexible(version) {
            wire::put_compact_array_len(buf, Some(self.responses.len()));
        } else {
            wire::put_array_len(buf, Some(self.responses.len()))?;
        }
        for item in &self.responses {
            item.encode(buf, version)?;
        }
        if is_flexible(version) {
            wire::put_tagged_fields(buf, &self.unknown_tagged_fields);
        }
        Ok(())
    }

    /// Decode one `DeleteTopicsResponse`, bounding allocation by the default
    /// [`Limits`] derived from `buf`'s remaining length.
    pub fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        Self::decode_with_limits(buf, version, Limits::default())
    }

    /// Decode one `DeleteTopicsResponse` under `limits`.
    pub fn decode_with_limits(
        buf: &mut impl Buf,
        version: i16,
        limits: Limits,
    ) -> Result<Self, DecodeError> {
        let mut budget = limits.budget(buf.remaining());
        Self::decode_with_budget(buf, version, &mut budget)
    }

    /// Decode one `DeleteTopicsResponse` against an existing `budget`.
    pub fn decode_with_budget(
        buf: &mut impl Buf,
        version: i16,
        budget: &mut Budget,
    ) -> Result<Self, DecodeError> {
        let mut this = Self::default();
        this.throttle_time_ms = wire::get_i32(buf)?;
        this.responses = {
            let len = if is_flexible(version) {
                wire::get_compact_array_len(buf)?
            } else {
                wire::get_array_len(buf)?
            };
            match len {
                None => return Err(DecodeError::InvalidLength(-1)),
                Some(n) => {
                    let mut items = Vec::new();
                    for _ in 0..n {
                        let mark = buf.remaining();
                        let item = DeletableTopicResult::decode_with_budget(buf, version, budget)?;
                        budget.progress(mark, buf.remaining())?;
                        budget.push(&mut items, item)?;
                    }
                    items
                }
            }
        };
        if is_flexible(version) {
            this.unknown_tagged_fields = wire::get_tagged_fields_with_budget(buf, budget)?;
        }
        Ok(this)
    }
}

impl crate::Message for DeleteTopicsResponse {
    const API_KEY: i16 = 20;
    const MIN_VERSION: i16 = 1;
    const MAX_VERSION: i16 = 6;

    fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        DeleteTopicsResponse::encode(self, buf, version)
    }
    fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        DeleteTopicsResponse::decode(buf, version)
    }
    fn decode_with_limits(
        buf: &mut impl Buf,
        version: i16,
        limits: Limits,
    ) -> Result<Self, DecodeError> {
        DeleteTopicsResponse::decode_with_limits(buf, version, limits)
    }
    fn throttle_time_ms(&self) -> Option<i32> {
        Some(self.throttle_time_ms)
    }
}

/// `DeletableTopicResult` (nested in [`DeleteTopicsResponse`]).
#[derive(Debug, Clone, PartialEq)]
#[non_exhaustive]
pub struct DeletableTopicResult {
    /// The topic name.
    pub name: Option<String>,
    /// The unique topic ID.
    pub topic_id: [u8; 16],
    /// The deletion error, or 0 if the deletion succeeded.
    pub error_code: i16,
    /// The error message, or null if there was no error.
    pub error_message: Option<String>,
    /// Tagged fields not (yet) known to this crate, kept raw.
    pub unknown_tagged_fields: Vec<RawTaggedField>,
}

impl Default for DeletableTopicResult {
    fn default() -> Self {
        Self {
            name: Some(String::new()),
            topic_id: [0u8; 16],
            error_code: 0,
            error_message: None,
            unknown_tagged_fields: Vec::new(),
        }
    }
}

impl DeletableTopicResult {
    /// Encode this `DeletableTopicResult` at `version`.
    pub fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        if self.name.is_none() && !(version >= 6) {
            return Err(EncodeError::NullField("Name"));
        }
        if is_flexible(version) {
            wire::put_compact_nullable_string(buf, self.name.as_deref());
        } else {
            wire::put_nullable_string(buf, self.name.as_deref())?;
        }
        if version >= 6 {
            wire::put_uuid(buf, self.topic_id);
        }
        buf.put_i16(self.error_code);
        if version >= 5 {
            if is_flexible(version) {
                wire::put_compact_nullable_string(buf, self.error_message.as_deref());
            } else {
                wire::put_nullable_string(buf, self.error_message.as_deref())?;
            }
        }
        if is_flexible(version) {
            wire::put_tagged_fields(buf, &self.unknown_tagged_fields);
        }
        Ok(())
    }

    /// Decode one `DeletableTopicResult`, bounding allocation by the default
    /// [`Limits`] derived from `buf`'s remaining length.
    pub fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        Self::decode_with_limits(buf, version, Limits::default())
    }

    /// Decode one `DeletableTopicResult` under `limits`.
    pub fn decode_with_limits(
        buf: &mut impl Buf,
        version: i16,
        limits: Limits,
    ) -> Result<Self, DecodeError> {
        let mut budget = limits.budget(buf.remaining());
        Self::decode_with_budget(buf, version, &mut budget)
    }

    /// Decode one `DeletableTopicResult` against an existing `budget`.
    pub fn decode_with_budget(
        buf: &mut impl Buf,
        version: i16,
        budget: &mut Budget,
    ) -> Result<Self, DecodeError> {
        let mut this = Self::default();
        this.name = {
            let raw = if is_flexible(version) {
                wire::get_compact_nullable_string(buf)?
            } else {
                wire::get_nullable_string(buf)?
            };
            if raw.is_none() && !(version >= 6) {
                return Err(DecodeError::InvalidLength(-1));
            }
            raw
        };
        if version >= 6 {
            this.topic_id = wire::get_uuid(buf)?;
        }
        this.error_code = wire::get_i16(buf)?;
        if version >= 5 {
            this.error_message = if is_flexible(version) {
                wire::get_compact_nullable_string(buf)?
            } else {
                wire::get_nullable_string(buf)?
            };
        }
        if is_flexible(version) {
            this.unknown_tagged_fields = wire::get_tagged_fields_with_budget(buf, budget)?;
        }
        Ok(this)
    }
}
