//! `DeleteTopicsRequest` — generated from `schemas/DeleteTopicsRequest.json`.
//!
//! @generated by `cargo xtask codegen`. Do not edit by hand.

#![allow(
    clippy::field_reassign_with_default,
    clippy::nonminimal_bool,
    clippy::derivable_impls,
    clippy::borrow_deref_ref,
    clippy::double_parens,
    unused_parens
)]

use bytes::{Buf, BufMut};

use crate::budget::{Budget, Limits};
#[allow(unused_imports)]
use crate::error::{DecodeError, EncodeError};
use crate::wire::{self, RawTaggedField};

/// Whether `version` of this message uses the flexible (compact) encoding.
pub fn is_flexible(version: i16) -> bool {
    let _ = version;
    version >= 4
}

/// `DeleteTopicsRequest`, versions 1-6.
#[derive(Debug, Clone, PartialEq)]
#[non_exhaustive]
pub struct DeleteTopicsRequest {
    /// The name or topic ID of the topic.
    pub topics: Vec<DeleteTopicState>,
    /// The names of the topics to delete.
    pub topic_names: Vec<String>,
    /// The length of time in milliseconds to wait for the deletions to complete.
    pub timeout_ms: i32,
    /// Tagged fields not (yet) known to this crate, kept raw.
    pub unknown_tagged_fields: Vec<RawTaggedField>,
}

impl Default for DeleteTopicsRequest {
    fn default() -> Self {
        Self {
            topics: Vec::new(),
            topic_names: Vec::new(),
            timeout_ms: 0,
            unknown_tagged_fields: Vec::new(),
        }
    }
}

impl DeleteTopicsRequest {
    /// This message's api key in Kafka's registry.
    pub const API_KEY: i16 = 20;
    /// The lowest schema version this snapshot can speak.
    pub const MIN_VERSION: i16 = 1;
    /// The highest schema version this snapshot can speak.
    pub const MAX_VERSION: i16 = 6;

    /// Encode this `DeleteTopicsRequest` at `version`.
    pub fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        if version >= 6 {
            if is_flexible(version) {
                wire::put_compact_array_len(buf, Some(self.topics.len()));
            } else {
                wire::put_array_len(buf, Some(self.topics.len()))?;
            }
            for item in &self.topics {
                item.encode(buf, version)?;
            }
        }
        if version <= 5 {
            if is_flexible(version) {
                wire::put_compact_array_len(buf, Some(self.topic_names.len()));
            } else {
                wire::put_array_len(buf, Some(self.topic_names.len()))?;
            }
            for item in &self.topic_names {
                if is_flexible(version) {
                    wire::put_compact_string(buf, item);
                } else {
                    wire::put_string(buf, item)?;
                }
            }
        }
        buf.put_i32(self.timeout_ms);
        if is_flexible(version) {
            wire::put_tagged_fields(buf, &self.unknown_tagged_fields);
        }
        Ok(())
    }

    /// Decode one `DeleteTopicsRequest`, bounding allocation by the default
    /// [`Limits`] derived from `buf`'s remaining length.
    pub fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        Self::decode_with_limits(buf, version, Limits::default())
    }

    /// Decode one `DeleteTopicsRequest` under `limits`.
    pub fn decode_with_limits(
        buf: &mut impl Buf,
        version: i16,
        limits: Limits,
    ) -> Result<Self, DecodeError> {
        let mut budget = limits.budget(buf.remaining());
        Self::decode_with_budget(buf, version, &mut budget)
    }

    /// Decode one `DeleteTopicsRequest` against an existing `budget`.
    pub fn decode_with_budget(
        buf: &mut impl Buf,
        version: i16,
        budget: &mut Budget,
    ) -> Result<Self, DecodeError> {
        let mut this = Self::default();
        if version >= 6 {
            this.topics = {
                let len = if is_flexible(version) {
                    wire::get_compact_array_len(buf)?
                } else {
                    wire::get_array_len(buf)?
                };
                match len {
                    None => return Err(DecodeError::InvalidLength(-1)),
                    Some(n) => {
                        let mut items = Vec::new();
                        for _ in 0..n {
                            let mark = buf.remaining();
                            let item = DeleteTopicState::decode_with_budget(buf, version, budget)?;
                            budget.progress(mark, buf.remaining())?;
                            budget.push(&mut items, item)?;
                        }
                        items
                    }
                }
            };
        }
        if version <= 5 {
            this.topic_names = {
                let len = if is_flexible(version) {
                    wire::get_compact_array_len(buf)?
                } else {
                    wire::get_array_len(buf)?
                };
                match len {
                    None => return Err(DecodeError::InvalidLength(-1)),
                    Some(n) => {
                        let mut items = Vec::new();
                        for _ in 0..n {
                            budget.push(
                                &mut items,
                                if is_flexible(version) {
                                    wire::get_compact_string(buf)?
                                } else {
                                    wire::get_string(buf)?
                                },
                            )?;
                        }
                        items
                    }
                }
            };
        }
        this.timeout_ms = wire::get_i32(buf)?;
        if is_flexible(version) {
            this.unknown_tagged_fields = wire::get_tagged_fields_with_budget(buf, budget)?;
        }
        Ok(this)
    }
}

impl crate::Message for DeleteTopicsRequest {
    const API_KEY: i16 = 20;
    const MIN_VERSION: i16 = 1;
    const MAX_VERSION: i16 = 6;

    fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        DeleteTopicsRequest::encode(self, buf, version)
    }
    fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        DeleteTopicsRequest::decode(buf, version)
    }
    fn decode_with_limits(
        buf: &mut impl Buf,
        version: i16,
        limits: Limits,
    ) -> Result<Self, DecodeError> {
        DeleteTopicsRequest::decode_with_limits(buf, version, limits)
    }
}

/// `DeleteTopicState` (nested in [`DeleteTopicsRequest`]).
#[derive(Debug, Clone, PartialEq)]
#[non_exhaustive]
pub struct DeleteTopicState {
    /// The topic name.
    pub name: Option<String>,
    /// The unique topic ID.
    pub topic_id: [u8; 16],
    /// Tagged fields not (yet) known to this crate, kept raw.
    pub unknown_tagged_fields: Vec<RawTaggedField>,
}

impl Default for DeleteTopicState {
    fn default() -> Self {
        Self {
            name: None,
            topic_id: [0u8; 16],
            unknown_tagged_fields: Vec::new(),
        }
    }
}

impl DeleteTopicState {
    /// Encode this `DeleteTopicState` at `version`.
    pub fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        if version >= 6 {
            if is_flexible(version) {
                wire::put_compact_nullable_string(buf, self.name.as_deref());
            } else {
                wire::put_nullable_string(buf, self.name.as_deref())?;
            }
        }
        if version >= 6 {
            wire::put_uuid(buf, self.topic_id);
        }
        if is_flexible(version) {
            wire::put_tagged_fields(buf, &self.unknown_tagged_fields);
        }
        Ok(())
    }

    /// Decode one `DeleteTopicState`, bounding allocation by the default
    /// [`Limits`] derived from `buf`'s remaining length.
    pub fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        Self::decode_with_limits(buf, version, Limits::default())
    }

    /// Decode one `DeleteTopicState` under `limits`.
    pub fn decode_with_limits(
        buf: &mut impl Buf,
        version: i16,
        limits: Limits,
    ) -> Result<Self, DecodeError> {
        let mut budget = limits.budget(buf.remaining());
        Self::decode_with_budget(buf, version, &mut budget)
    }

    /// Decode one `DeleteTopicState` against an existing `budget`.
    pub fn decode_with_budget(
        buf: &mut impl Buf,
        version: i16,
        budget: &mut Budget,
    ) -> Result<Self, DecodeError> {
        let mut this = Self::default();
        if version >= 6 {
            this.name = if is_flexible(version) {
                wire::get_compact_nullable_string(buf)?
            } else {
                wire::get_nullable_string(buf)?
            };
        }
        if version >= 6 {
            this.topic_id = wire::get_uuid(buf)?;
        }
        if is_flexible(version) {
            this.unknown_tagged_fields = wire::get_tagged_fields_with_budget(buf, budget)?;
        }
        Ok(this)
    }
}
