//! `DescribeGroupsRequest` — generated from `schemas/DescribeGroupsRequest.json`.
//!
//! @generated by `cargo xtask codegen`. Do not edit by hand.

#![allow(
    clippy::field_reassign_with_default,
    clippy::nonminimal_bool,
    clippy::derivable_impls,
    clippy::borrow_deref_ref,
    clippy::double_parens,
    unused_parens
)]

use bytes::{Buf, BufMut};

use crate::budget::{Budget, Limits};
#[allow(unused_imports)]
use crate::error::{DecodeError, EncodeError};
use crate::wire::{self, RawTaggedField};

/// Whether `version` of this message uses the flexible (compact) encoding.
pub fn is_flexible(version: i16) -> bool {
    let _ = version;
    version >= 5
}

/// `DescribeGroupsRequest`, versions 0-6.
#[derive(Debug, Clone, PartialEq)]
#[non_exhaustive]
pub struct DescribeGroupsRequest {
    /// The names of the groups to describe.
    pub groups: Vec<String>,
    /// Whether to include authorized operations.
    pub include_authorized_operations: bool,
    /// Tagged fields not (yet) known to this crate, kept raw.
    pub unknown_tagged_fields: Vec<RawTaggedField>,
}

impl Default for DescribeGroupsRequest {
    fn default() -> Self {
        Self {
            groups: Vec::new(),
            include_authorized_operations: false,
            unknown_tagged_fields: Vec::new(),
        }
    }
}

impl DescribeGroupsRequest {
    /// This message's api key in Kafka's registry.
    pub const API_KEY: i16 = 15;
    /// The lowest schema version this snapshot can speak.
    pub const MIN_VERSION: i16 = 0;
    /// The highest schema version this snapshot can speak.
    pub const MAX_VERSION: i16 = 6;

    /// Encode this `DescribeGroupsRequest` at `version`.
    pub fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        if is_flexible(version) {
            wire::put_compact_array_len(buf, Some(self.groups.len()));
        } else {
            wire::put_array_len(buf, Some(self.groups.len()))?;
        }
        for item in &self.groups {
            if is_flexible(version) {
                wire::put_compact_string(buf, item);
            } else {
                wire::put_string(buf, item)?;
            }
        }
        if version >= 3 {
            buf.put_u8(u8::from(self.include_authorized_operations));
        }
        if is_flexible(version) {
            wire::put_tagged_fields(buf, &self.unknown_tagged_fields);
        }
        Ok(())
    }

    /// Decode one `DescribeGroupsRequest`, bounding allocation by the default
    /// [`Limits`] derived from `buf`'s remaining length.
    pub fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        Self::decode_with_limits(buf, version, Limits::default())
    }

    /// Decode one `DescribeGroupsRequest` under `limits`.
    pub fn decode_with_limits(
        buf: &mut impl Buf,
        version: i16,
        limits: Limits,
    ) -> Result<Self, DecodeError> {
        let mut budget = limits.budget(buf.remaining());
        Self::decode_with_budget(buf, version, &mut budget)
    }

    /// Decode one `DescribeGroupsRequest` against an existing `budget`.
    pub fn decode_with_budget(
        buf: &mut impl Buf,
        version: i16,
        budget: &mut Budget,
    ) -> Result<Self, DecodeError> {
        let mut this = Self::default();
        this.groups = {
            let len = if is_flexible(version) {
                wire::get_compact_array_len(buf)?
            } else {
                wire::get_array_len(buf)?
            };
            match len {
                None => return Err(DecodeError::InvalidLength(-1)),
                Some(n) => {
                    let mut items = Vec::new();
                    for _ in 0..n {
                        budget.push(
                            &mut items,
                            if is_flexible(version) {
                                wire::get_compact_string(buf)?
                            } else {
                                wire::get_string(buf)?
                            },
                        )?;
                    }
                    items
                }
            }
        };
        if version >= 3 {
            this.include_authorized_operations = wire::get_bool(buf)?;
        }
        if is_flexible(version) {
            this.unknown_tagged_fields = wire::get_tagged_fields_with_budget(buf, budget)?;
        }
        Ok(this)
    }
}

impl crate::Message for DescribeGroupsRequest {
    const API_KEY: i16 = 15;
    const MIN_VERSION: i16 = 0;
    const MAX_VERSION: i16 = 6;

    fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        DescribeGroupsRequest::encode(self, buf, version)
    }
    fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        DescribeGroupsRequest::decode(buf, version)
    }
    fn decode_with_limits(
        buf: &mut impl Buf,
        version: i16,
        limits: Limits,
    ) -> Result<Self, DecodeError> {
        DescribeGroupsRequest::decode_with_limits(buf, version, limits)
    }
}
