//! `DescribeConfigsRequest` — generated from `schemas/DescribeConfigsRequest.json`.
//!
//! @generated by `cargo xtask codegen`. Do not edit by hand.

#![allow(
    clippy::field_reassign_with_default,
    clippy::nonminimal_bool,
    clippy::derivable_impls,
    clippy::borrow_deref_ref,
    clippy::double_parens,
    unused_parens
)]

use bytes::{Buf, BufMut};

use crate::budget::{Budget, Limits};
#[allow(unused_imports)]
use crate::error::{DecodeError, EncodeError};
use crate::wire::{self, RawTaggedField};

/// Whether `version` of this message uses the flexible (compact) encoding.
pub fn is_flexible(version: i16) -> bool {
    let _ = version;
    version >= 4
}

/// `DescribeConfigsRequest`, versions 1-4.
#[derive(Debug, Clone, PartialEq)]
#[non_exhaustive]
pub struct DescribeConfigsRequest {
    /// The resources whose configurations we want to describe.
    pub resources: Vec<DescribeConfigsResource>,
    /// True if we should include all synonyms.
    pub include_synonyms: bool,
    /// True if we should include configuration documentation.
    pub include_documentation: bool,
    /// Tagged fields not (yet) known to this crate, kept raw.
    pub unknown_tagged_fields: Vec<RawTaggedField>,
}

impl Default for DescribeConfigsRequest {
    fn default() -> Self {
        Self {
            resources: Vec::new(),
            include_synonyms: false,
            include_documentation: false,
            unknown_tagged_fields: Vec::new(),
        }
    }
}

impl DescribeConfigsRequest {
    /// This message's api key in Kafka's registry.
    pub const API_KEY: i16 = 32;
    /// The lowest schema version this snapshot can speak.
    pub const MIN_VERSION: i16 = 1;
    /// The highest schema version this snapshot can speak.
    pub const MAX_VERSION: i16 = 4;

    /// Encode this `DescribeConfigsRequest` at `version`.
    pub fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        if is_flexible(version) {
            wire::put_compact_array_len(buf, Some(self.resources.len()));
        } else {
            wire::put_array_len(buf, Some(self.resources.len()))?;
        }
        for item in &self.resources {
            item.encode(buf, version)?;
        }
        buf.put_u8(u8::from(self.include_synonyms));
        if version >= 3 {
            buf.put_u8(u8::from(self.include_documentation));
        }
        if is_flexible(version) {
            wire::put_tagged_fields(buf, &self.unknown_tagged_fields);
        }
        Ok(())
    }

    /// Decode one `DescribeConfigsRequest`, bounding allocation by the default
    /// [`Limits`] derived from `buf`'s remaining length.
    pub fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        Self::decode_with_limits(buf, version, Limits::default())
    }

    /// Decode one `DescribeConfigsRequest` under `limits`.
    pub fn decode_with_limits(
        buf: &mut impl Buf,
        version: i16,
        limits: Limits,
    ) -> Result<Self, DecodeError> {
        let mut budget = limits.budget(buf.remaining());
        Self::decode_with_budget(buf, version, &mut budget)
    }

    /// Decode one `DescribeConfigsRequest` against an existing `budget`.
    pub fn decode_with_budget(
        buf: &mut impl Buf,
        version: i16,
        budget: &mut Budget,
    ) -> Result<Self, DecodeError> {
        let mut this = Self::default();
        this.resources = {
            let len = if is_flexible(version) {
                wire::get_compact_array_len(buf)?
            } else {
                wire::get_array_len(buf)?
            };
            match len {
                None => return Err(DecodeError::InvalidLength(-1)),
                Some(n) => {
                    let mut items = Vec::new();
                    for _ in 0..n {
                        let mark = buf.remaining();
                        let item =
                            DescribeConfigsResource::decode_with_budget(buf, version, budget)?;
                        budget.progress(mark, buf.remaining())?;
                        budget.push(&mut items, item)?;
                    }
                    items
                }
            }
        };
        this.include_synonyms = wire::get_bool(buf)?;
        if version >= 3 {
            this.include_documentation = wire::get_bool(buf)?;
        }
        if is_flexible(version) {
            this.unknown_tagged_fields = wire::get_tagged_fields_with_budget(buf, budget)?;
        }
        Ok(this)
    }
}

impl crate::Message for DescribeConfigsRequest {
    const API_KEY: i16 = 32;
    const MIN_VERSION: i16 = 1;
    const MAX_VERSION: i16 = 4;

    fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        DescribeConfigsRequest::encode(self, buf, version)
    }
    fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        DescribeConfigsRequest::decode(buf, version)
    }
    fn decode_with_limits(
        buf: &mut impl Buf,
        version: i16,
        limits: Limits,
    ) -> Result<Self, DecodeError> {
        DescribeConfigsRequest::decode_with_limits(buf, version, limits)
    }
}

/// `DescribeConfigsResource` (nested in [`DescribeConfigsRequest`]).
#[derive(Debug, Clone, PartialEq)]
#[non_exhaustive]
pub struct DescribeConfigsResource {
    /// The resource type.
    pub resource_type: i8,
    /// The resource name.
    pub resource_name: String,
    /// The configuration keys to list, or null to list all configuration keys.
    pub configuration_keys: Option<Vec<String>>,
    /// Tagged fields not (yet) known to this crate, kept raw.
    pub unknown_tagged_fields: Vec<RawTaggedField>,
}

impl Default for DescribeConfigsResource {
    fn default() -> Self {
        Self {
            resource_type: 0,
            resource_name: String::new(),
            configuration_keys: Some(Vec::new()),
            unknown_tagged_fields: Vec::new(),
        }
    }
}

impl DescribeConfigsResource {
    /// Encode this `DescribeConfigsResource` at `version`.
    pub fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        buf.put_i8(self.resource_type);
        if is_flexible(version) {
            wire::put_compact_string(buf, &self.resource_name);
        } else {
            wire::put_string(buf, &self.resource_name)?;
        }
        match &self.configuration_keys {
            Some(items) => {
                if is_flexible(version) {
                    wire::put_compact_array_len(buf, Some(items.len()));
                } else {
                    wire::put_array_len(buf, Some(items.len()))?;
                }
                for item in items {
                    if is_flexible(version) {
                        wire::put_compact_string(buf, item);
                    } else {
                        wire::put_string(buf, item)?;
                    }
                }
            }
            None => {
                if is_flexible(version) {
                    wire::put_compact_array_len(buf, None);
                } else {
                    wire::put_array_len(buf, None)?;
                }
            }
        }
        if is_flexible(version) {
            wire::put_tagged_fields(buf, &self.unknown_tagged_fields);
        }
        Ok(())
    }

    /// Decode one `DescribeConfigsResource`, bounding allocation by the default
    /// [`Limits`] derived from `buf`'s remaining length.
    pub fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        Self::decode_with_limits(buf, version, Limits::default())
    }

    /// Decode one `DescribeConfigsResource` under `limits`.
    pub fn decode_with_limits(
        buf: &mut impl Buf,
        version: i16,
        limits: Limits,
    ) -> Result<Self, DecodeError> {
        let mut budget = limits.budget(buf.remaining());
        Self::decode_with_budget(buf, version, &mut budget)
    }

    /// Decode one `DescribeConfigsResource` against an existing `budget`.
    pub fn decode_with_budget(
        buf: &mut impl Buf,
        version: i16,
        budget: &mut Budget,
    ) -> Result<Self, DecodeError> {
        let mut this = Self::default();
        this.resource_type = wire::get_i8(buf)?;
        this.resource_name = if is_flexible(version) {
            wire::get_compact_string(buf)?
        } else {
            wire::get_string(buf)?
        };
        this.configuration_keys = {
            let len = if is_flexible(version) {
                wire::get_compact_array_len(buf)?
            } else {
                wire::get_array_len(buf)?
            };
            match len {
                None => None,
                Some(n) => {
                    let mut items = Vec::new();
                    for _ in 0..n {
                        budget.push(
                            &mut items,
                            if is_flexible(version) {
                                wire::get_compact_string(buf)?
                            } else {
                                wire::get_string(buf)?
                            },
                        )?;
                    }
                    Some(items)
                }
            }
        };
        if is_flexible(version) {
            this.unknown_tagged_fields = wire::get_tagged_fields_with_budget(buf, budget)?;
        }
        Ok(this)
    }
}
