//! `FetchResponse` — generated from `schemas/FetchResponse.json`.
//!
//! @generated by `cargo xtask codegen`. Do not edit by hand.
//!
//! Tagged fields are materialized as `Option` struct fields (`None` = absent
//! on the wire); unknown tags still round-trip through `unknown_tagged_fields`.

#![allow(
    clippy::field_reassign_with_default,
    clippy::nonminimal_bool,
    clippy::derivable_impls,
    clippy::borrow_deref_ref,
    clippy::double_parens,
    unused_parens
)]

use bytes::{Buf, BufMut};

#[allow(unused_imports)]
use crate::error::{DecodeError, EncodeError};
use crate::wire::{self, RawTaggedField};

/// Whether `version` of this message uses the flexible (compact) encoding.
pub fn is_flexible(version: i16) -> bool {
    let _ = version;
    version >= 12
}

/// `FetchResponse`, versions 4-18.
#[derive(Debug, Clone, PartialEq)]
#[non_exhaustive]
pub struct FetchResponse {
    /// The duration in milliseconds for which the request was throttled due to a quota violation, or zero if the request did not violate any quota.
    pub throttle_time_ms: i32,
    /// The top level response error code.
    pub error_code: i16,
    /// The fetch session ID, or 0 if this is not part of a fetch session.
    pub session_id: i32,
    /// The response topics.
    pub responses: Vec<FetchableTopicResponse>,
    /// Endpoints for all current-leaders enumerated in PartitionData, with errors NOT_LEADER_OR_FOLLOWER & FENCED_LEADER_EPOCH.
    /// (Tagged field 0; `None` = absent on the wire.)
    pub node_endpoints: Option<Vec<NodeEndpoint>>,
    /// Tagged fields not (yet) known to this crate, kept raw.
    pub unknown_tagged_fields: Vec<RawTaggedField>,
}

impl Default for FetchResponse {
    fn default() -> Self {
        Self {
            throttle_time_ms: 0,
            error_code: 0,
            session_id: 0,
            responses: Vec::new(),
            node_endpoints: None,
            unknown_tagged_fields: Vec::new(),
        }
    }
}

impl FetchResponse {
    pub const API_KEY: i16 = 1;
    pub const MIN_VERSION: i16 = 4;
    pub const MAX_VERSION: i16 = 18;

    pub fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        buf.put_i32(self.throttle_time_ms);
        if version >= 7 {
            buf.put_i16(self.error_code);
        }
        if version >= 7 {
            buf.put_i32(self.session_id);
        }
        if is_flexible(version) {
            wire::put_compact_array_len(buf, Some(self.responses.len()));
        } else {
            wire::put_array_len(buf, Some(self.responses.len()))?;
        }
        for item in &self.responses {
            item.encode(buf, version)?;
        }
        if is_flexible(version) {
            let mut tagged = self.unknown_tagged_fields.clone();
            if version >= 16 {
                if let Some(v) = &self.node_endpoints {
                    let mut tag_data = bytes::BytesMut::new();
                    {
                        let buf = &mut tag_data;
                        if is_flexible(version) {
                            wire::put_compact_array_len(buf, Some((*v).len()));
                        } else {
                            wire::put_array_len(buf, Some((*v).len()))?;
                        }
                        for item in &(*v) {
                            item.encode(buf, version)?;
                        }
                    }
                    tagged.push(RawTaggedField {
                        tag: 0,
                        data: tag_data.freeze(),
                    });
                }
            }
            tagged.sort_by_key(|f| f.tag);
            wire::put_tagged_fields(buf, &tagged);
        }
        Ok(())
    }

    pub fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        let mut this = Self::default();
        this.throttle_time_ms = wire::get_i32(buf)?;
        if version >= 7 {
            this.error_code = wire::get_i16(buf)?;
        }
        if version >= 7 {
            this.session_id = wire::get_i32(buf)?;
        }
        this.responses = {
            let len = if is_flexible(version) {
                wire::get_compact_array_len(buf)?
            } else {
                wire::get_array_len(buf)?
            };
            match len {
                None => return Err(DecodeError::InvalidLength(-1)),
                Some(n) => {
                    let mut items = Vec::new();
                    for _ in 0..n {
                        items.push(FetchableTopicResponse::decode(buf, version)?);
                    }
                    items
                }
            }
        };
        if is_flexible(version) {
            for raw in wire::get_tagged_fields(buf)? {
                if raw.tag == 0 && (version >= 16) {
                    let mut tag_data = raw.data;
                    let buf = &mut tag_data;
                    this.node_endpoints = Some({
                        let len = if is_flexible(version) {
                            wire::get_compact_array_len(buf)?
                        } else {
                            wire::get_array_len(buf)?
                        };
                        match len {
                            None => return Err(DecodeError::InvalidLength(-1)),
                            Some(n) => {
                                let mut items = Vec::new();
                                for _ in 0..n {
                                    items.push(NodeEndpoint::decode(buf, version)?);
                                }
                                items
                            }
                        }
                    });
                    if buf.has_remaining() {
                        return Err(DecodeError::InvalidLength(
                            i64::try_from(buf.remaining()).unwrap_or(i64::MAX),
                        ));
                    }
                } else {
                    this.unknown_tagged_fields.push(raw);
                }
            }
        }
        Ok(this)
    }
}

impl crate::Message for FetchResponse {
    const API_KEY: i16 = 1;
    const MIN_VERSION: i16 = 4;
    const MAX_VERSION: i16 = 18;

    fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        FetchResponse::encode(self, buf, version)
    }
    fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        FetchResponse::decode(buf, version)
    }
}

/// `FetchableTopicResponse` (nested in [`FetchResponse`]).
#[derive(Debug, Clone, PartialEq)]
#[non_exhaustive]
pub struct FetchableTopicResponse {
    /// The topic name.
    pub topic: String,
    /// The unique topic ID.
    pub topic_id: [u8; 16],
    /// The topic partitions.
    pub partitions: Vec<PartitionData>,
    /// Tagged fields not (yet) known to this crate, kept raw.
    pub unknown_tagged_fields: Vec<RawTaggedField>,
}

impl Default for FetchableTopicResponse {
    fn default() -> Self {
        Self {
            topic: String::new(),
            topic_id: [0u8; 16],
            partitions: Vec::new(),
            unknown_tagged_fields: Vec::new(),
        }
    }
}

impl FetchableTopicResponse {
    pub fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        if version <= 12 {
            if is_flexible(version) {
                wire::put_compact_string(buf, &self.topic);
            } else {
                wire::put_string(buf, &self.topic)?;
            }
        }
        if version >= 13 {
            wire::put_uuid(buf, self.topic_id);
        }
        if is_flexible(version) {
            wire::put_compact_array_len(buf, Some(self.partitions.len()));
        } else {
            wire::put_array_len(buf, Some(self.partitions.len()))?;
        }
        for item in &self.partitions {
            item.encode(buf, version)?;
        }
        if is_flexible(version) {
            wire::put_tagged_fields(buf, &self.unknown_tagged_fields);
        }
        Ok(())
    }

    pub fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        let mut this = Self::default();
        if version <= 12 {
            this.topic = if is_flexible(version) {
                wire::get_compact_string(buf)?
            } else {
                wire::get_string(buf)?
            };
        }
        if version >= 13 {
            this.topic_id = wire::get_uuid(buf)?;
        }
        this.partitions = {
            let len = if is_flexible(version) {
                wire::get_compact_array_len(buf)?
            } else {
                wire::get_array_len(buf)?
            };
            match len {
                None => return Err(DecodeError::InvalidLength(-1)),
                Some(n) => {
                    let mut items = Vec::new();
                    for _ in 0..n {
                        items.push(PartitionData::decode(buf, version)?);
                    }
                    items
                }
            }
        };
        if is_flexible(version) {
            this.unknown_tagged_fields = wire::get_tagged_fields(buf)?;
        }
        Ok(this)
    }
}

/// `PartitionData` (nested in [`FetchResponse`]).
#[derive(Debug, Clone, PartialEq)]
#[non_exhaustive]
pub struct PartitionData {
    /// The partition index.
    pub partition_index: i32,
    /// The error code, or 0 if there was no fetch error.
    pub error_code: i16,
    /// The current high water mark.
    pub high_watermark: i64,
    /// The last stable offset (or LSO) of the partition. This is the last offset such that the state of all transactional records prior to this offset have been decided (ABORTED or COMMITTED).
    pub last_stable_offset: i64,
    /// The current log start offset.
    pub log_start_offset: i64,
    /// The aborted transactions.
    pub aborted_transactions: Option<Vec<AbortedTransaction>>,
    /// The preferred read replica for the consumer to use on its next fetch request.
    pub preferred_read_replica: i32,
    /// The record data.
    pub records: Option<bytes::Bytes>,
    /// In case divergence is detected based on the `LastFetchedEpoch` and `FetchOffset` in the request, this field indicates the largest epoch and its end offset such that subsequent records are known to diverge.
    /// (Tagged field 0; `None` = absent on the wire.)
    pub diverging_epoch: Option<EpochEndOffset>,
    /// The current leader of the partition.
    /// (Tagged field 1; `None` = absent on the wire.)
    pub current_leader: Option<LeaderIdAndEpoch>,
    /// In the case of fetching an offset less than the LogStartOffset, this is the end offset and epoch that should be used in the FetchSnapshot request.
    /// (Tagged field 2; `None` = absent on the wire.)
    pub snapshot_id: Option<SnapshotId>,
    /// Tagged fields not (yet) known to this crate, kept raw.
    pub unknown_tagged_fields: Vec<RawTaggedField>,
}

impl Default for PartitionData {
    fn default() -> Self {
        Self {
            partition_index: 0,
            error_code: 0,
            high_watermark: 0,
            last_stable_offset: -1,
            log_start_offset: -1,
            aborted_transactions: Some(Vec::new()),
            preferred_read_replica: -1,
            records: Some(bytes::Bytes::new()),
            diverging_epoch: None,
            current_leader: None,
            snapshot_id: None,
            unknown_tagged_fields: Vec::new(),
        }
    }
}

impl PartitionData {
    pub fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        buf.put_i32(self.partition_index);
        buf.put_i16(self.error_code);
        buf.put_i64(self.high_watermark);
        buf.put_i64(self.last_stable_offset);
        if version >= 5 {
            buf.put_i64(self.log_start_offset);
        }
        match &self.aborted_transactions {
            Some(items) => {
                if is_flexible(version) {
                    wire::put_compact_array_len(buf, Some(items.len()));
                } else {
                    wire::put_array_len(buf, Some(items.len()))?;
                }
                for item in items {
                    item.encode(buf, version)?;
                }
            }
            None => {
                if is_flexible(version) {
                    wire::put_compact_array_len(buf, None);
                } else {
                    wire::put_array_len(buf, None)?;
                }
            }
        }
        if version >= 11 {
            buf.put_i32(self.preferred_read_replica);
        }
        if is_flexible(version) {
            wire::put_compact_nullable_bytes(buf, self.records.as_deref());
        } else {
            wire::put_nullable_bytes(buf, self.records.as_deref())?;
        }
        if is_flexible(version) {
            let mut tagged = self.unknown_tagged_fields.clone();
            if version >= 12 {
                if let Some(v) = &self.diverging_epoch {
                    let mut tag_data = bytes::BytesMut::new();
                    {
                        let buf = &mut tag_data;
                        (*v).encode(buf, version)?;
                    }
                    tagged.push(RawTaggedField {
                        tag: 0,
                        data: tag_data.freeze(),
                    });
                }
            }
            if version >= 12 {
                if let Some(v) = &self.current_leader {
                    let mut tag_data = bytes::BytesMut::new();
                    {
                        let buf = &mut tag_data;
                        (*v).encode(buf, version)?;
                    }
                    tagged.push(RawTaggedField {
                        tag: 1,
                        data: tag_data.freeze(),
                    });
                }
            }
            if version >= 12 {
                if let Some(v) = &self.snapshot_id {
                    let mut tag_data = bytes::BytesMut::new();
                    {
                        let buf = &mut tag_data;
                        (*v).encode(buf, version)?;
                    }
                    tagged.push(RawTaggedField {
                        tag: 2,
                        data: tag_data.freeze(),
                    });
                }
            }
            tagged.sort_by_key(|f| f.tag);
            wire::put_tagged_fields(buf, &tagged);
        }
        Ok(())
    }

    pub fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        let mut this = Self::default();
        this.partition_index = wire::get_i32(buf)?;
        this.error_code = wire::get_i16(buf)?;
        this.high_watermark = wire::get_i64(buf)?;
        this.last_stable_offset = wire::get_i64(buf)?;
        if version >= 5 {
            this.log_start_offset = wire::get_i64(buf)?;
        }
        this.aborted_transactions = {
            let len = if is_flexible(version) {
                wire::get_compact_array_len(buf)?
            } else {
                wire::get_array_len(buf)?
            };
            match len {
                None => None,
                Some(n) => {
                    let mut items = Vec::new();
                    for _ in 0..n {
                        items.push(AbortedTransaction::decode(buf, version)?);
                    }
                    Some(items)
                }
            }
        };
        if version >= 11 {
            this.preferred_read_replica = wire::get_i32(buf)?;
        }
        this.records = if is_flexible(version) {
            wire::get_compact_nullable_bytes(buf)?
        } else {
            wire::get_nullable_bytes(buf)?
        };
        if is_flexible(version) {
            for raw in wire::get_tagged_fields(buf)? {
                if raw.tag == 0 && (version >= 12) {
                    let mut tag_data = raw.data;
                    let buf = &mut tag_data;
                    this.diverging_epoch = Some(EpochEndOffset::decode(buf, version)?);
                    if buf.has_remaining() {
                        return Err(DecodeError::InvalidLength(
                            i64::try_from(buf.remaining()).unwrap_or(i64::MAX),
                        ));
                    }
                } else if raw.tag == 1 && (version >= 12) {
                    let mut tag_data = raw.data;
                    let buf = &mut tag_data;
                    this.current_leader = Some(LeaderIdAndEpoch::decode(buf, version)?);
                    if buf.has_remaining() {
                        return Err(DecodeError::InvalidLength(
                            i64::try_from(buf.remaining()).unwrap_or(i64::MAX),
                        ));
                    }
                } else if raw.tag == 2 && (version >= 12) {
                    let mut tag_data = raw.data;
                    let buf = &mut tag_data;
                    this.snapshot_id = Some(SnapshotId::decode(buf, version)?);
                    if buf.has_remaining() {
                        return Err(DecodeError::InvalidLength(
                            i64::try_from(buf.remaining()).unwrap_or(i64::MAX),
                        ));
                    }
                } else {
                    this.unknown_tagged_fields.push(raw);
                }
            }
        }
        Ok(this)
    }
}

/// `EpochEndOffset` (nested in [`FetchResponse`]).
#[derive(Debug, Clone, PartialEq)]
#[non_exhaustive]
pub struct EpochEndOffset {
    /// The largest epoch.
    pub epoch: i32,
    /// The end offset of the epoch.
    pub end_offset: i64,
    /// Tagged fields not (yet) known to this crate, kept raw.
    pub unknown_tagged_fields: Vec<RawTaggedField>,
}

impl Default for EpochEndOffset {
    fn default() -> Self {
        Self {
            epoch: -1,
            end_offset: -1,
            unknown_tagged_fields: Vec::new(),
        }
    }
}

impl EpochEndOffset {
    pub fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        if version >= 12 {
            buf.put_i32(self.epoch);
        }
        if version >= 12 {
            buf.put_i64(self.end_offset);
        }
        if is_flexible(version) {
            wire::put_tagged_fields(buf, &self.unknown_tagged_fields);
        }
        Ok(())
    }

    pub fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        let mut this = Self::default();
        if version >= 12 {
            this.epoch = wire::get_i32(buf)?;
        }
        if version >= 12 {
            this.end_offset = wire::get_i64(buf)?;
        }
        if is_flexible(version) {
            this.unknown_tagged_fields = wire::get_tagged_fields(buf)?;
        }
        Ok(this)
    }
}

/// `LeaderIdAndEpoch` (nested in [`FetchResponse`]).
#[derive(Debug, Clone, PartialEq)]
#[non_exhaustive]
pub struct LeaderIdAndEpoch {
    /// The ID of the current leader or -1 if the leader is unknown.
    pub leader_id: i32,
    /// The latest known leader epoch.
    pub leader_epoch: i32,
    /// Tagged fields not (yet) known to this crate, kept raw.
    pub unknown_tagged_fields: Vec<RawTaggedField>,
}

impl Default for LeaderIdAndEpoch {
    fn default() -> Self {
        Self {
            leader_id: -1,
            leader_epoch: -1,
            unknown_tagged_fields: Vec::new(),
        }
    }
}

impl LeaderIdAndEpoch {
    pub fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        if version >= 12 {
            buf.put_i32(self.leader_id);
        }
        if version >= 12 {
            buf.put_i32(self.leader_epoch);
        }
        if is_flexible(version) {
            wire::put_tagged_fields(buf, &self.unknown_tagged_fields);
        }
        Ok(())
    }

    pub fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        let mut this = Self::default();
        if version >= 12 {
            this.leader_id = wire::get_i32(buf)?;
        }
        if version >= 12 {
            this.leader_epoch = wire::get_i32(buf)?;
        }
        if is_flexible(version) {
            this.unknown_tagged_fields = wire::get_tagged_fields(buf)?;
        }
        Ok(this)
    }
}

/// `SnapshotId` (nested in [`FetchResponse`]).
#[derive(Debug, Clone, PartialEq)]
#[non_exhaustive]
pub struct SnapshotId {
    /// The end offset of the epoch.
    pub end_offset: i64,
    /// The largest epoch.
    pub epoch: i32,
    /// Tagged fields not (yet) known to this crate, kept raw.
    pub unknown_tagged_fields: Vec<RawTaggedField>,
}

impl Default for SnapshotId {
    fn default() -> Self {
        Self {
            end_offset: -1,
            epoch: -1,
            unknown_tagged_fields: Vec::new(),
        }
    }
}

impl SnapshotId {
    pub fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        buf.put_i64(self.end_offset);
        buf.put_i32(self.epoch);
        if is_flexible(version) {
            wire::put_tagged_fields(buf, &self.unknown_tagged_fields);
        }
        Ok(())
    }

    pub fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        let mut this = Self::default();
        this.end_offset = wire::get_i64(buf)?;
        this.epoch = wire::get_i32(buf)?;
        if is_flexible(version) {
            this.unknown_tagged_fields = wire::get_tagged_fields(buf)?;
        }
        Ok(this)
    }
}

/// `AbortedTransaction` (nested in [`FetchResponse`]).
#[derive(Debug, Clone, PartialEq)]
#[non_exhaustive]
pub struct AbortedTransaction {
    /// The producer id associated with the aborted transaction.
    pub producer_id: i64,
    /// The first offset in the aborted transaction.
    pub first_offset: i64,
    /// Tagged fields not (yet) known to this crate, kept raw.
    pub unknown_tagged_fields: Vec<RawTaggedField>,
}

impl Default for AbortedTransaction {
    fn default() -> Self {
        Self {
            producer_id: 0,
            first_offset: 0,
            unknown_tagged_fields: Vec::new(),
        }
    }
}

impl AbortedTransaction {
    pub fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        buf.put_i64(self.producer_id);
        buf.put_i64(self.first_offset);
        if is_flexible(version) {
            wire::put_tagged_fields(buf, &self.unknown_tagged_fields);
        }
        Ok(())
    }

    pub fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        let mut this = Self::default();
        this.producer_id = wire::get_i64(buf)?;
        this.first_offset = wire::get_i64(buf)?;
        if is_flexible(version) {
            this.unknown_tagged_fields = wire::get_tagged_fields(buf)?;
        }
        Ok(this)
    }
}

/// `NodeEndpoint` (nested in [`FetchResponse`]).
#[derive(Debug, Clone, PartialEq)]
#[non_exhaustive]
pub struct NodeEndpoint {
    /// The ID of the associated node.
    pub node_id: i32,
    /// The node's hostname.
    pub host: String,
    /// The node's port.
    pub port: i32,
    /// The rack of the node, or null if it has not been assigned to a rack.
    pub rack: Option<String>,
    /// Tagged fields not (yet) known to this crate, kept raw.
    pub unknown_tagged_fields: Vec<RawTaggedField>,
}

impl Default for NodeEndpoint {
    fn default() -> Self {
        Self {
            node_id: 0,
            host: String::new(),
            port: 0,
            rack: None,
            unknown_tagged_fields: Vec::new(),
        }
    }
}

impl NodeEndpoint {
    pub fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        if version >= 16 {
            buf.put_i32(self.node_id);
        }
        if version >= 16 {
            if is_flexible(version) {
                wire::put_compact_string(buf, &self.host);
            } else {
                wire::put_string(buf, &self.host)?;
            }
        }
        if version >= 16 {
            buf.put_i32(self.port);
        }
        if version >= 16 {
            if is_flexible(version) {
                wire::put_compact_nullable_string(buf, self.rack.as_deref());
            } else {
                wire::put_nullable_string(buf, self.rack.as_deref())?;
            }
        }
        if is_flexible(version) {
            wire::put_tagged_fields(buf, &self.unknown_tagged_fields);
        }
        Ok(())
    }

    pub fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        let mut this = Self::default();
        if version >= 16 {
            this.node_id = wire::get_i32(buf)?;
        }
        if version >= 16 {
            this.host = if is_flexible(version) {
                wire::get_compact_string(buf)?
            } else {
                wire::get_string(buf)?
            };
        }
        if version >= 16 {
            this.port = wire::get_i32(buf)?;
        }
        if version >= 16 {
            this.rack = if is_flexible(version) {
                wire::get_compact_nullable_string(buf)?
            } else {
                wire::get_nullable_string(buf)?
            };
        }
        if is_flexible(version) {
            this.unknown_tagged_fields = wire::get_tagged_fields(buf)?;
        }
        Ok(this)
    }
}
