//! `FetchRequest` — generated from `schemas/FetchRequest.json`.
//!
//! @generated by `cargo xtask codegen`. Do not edit by hand.
//!
//! Tagged fields are materialized as `Option` struct fields (`None` = absent
//! on the wire); unknown tags still round-trip through `unknown_tagged_fields`.

#![allow(
    clippy::field_reassign_with_default,
    clippy::nonminimal_bool,
    clippy::derivable_impls,
    clippy::borrow_deref_ref,
    clippy::double_parens,
    unused_parens
)]

use bytes::{Buf, BufMut};

#[allow(unused_imports)]
use crate::error::{DecodeError, EncodeError};
use crate::wire::{self, RawTaggedField};

/// Whether `version` of this message uses the flexible (compact) encoding.
pub fn is_flexible(version: i16) -> bool {
    let _ = version;
    version >= 12
}

/// `FetchRequest`, versions 4-18.
#[derive(Debug, Clone, PartialEq)]
#[non_exhaustive]
pub struct FetchRequest {
    /// The broker ID of the follower, of -1 if this request is from a consumer.
    pub replica_id: i32,
    /// The maximum time in milliseconds to wait for the response.
    pub max_wait_ms: i32,
    /// The minimum bytes to accumulate in the response.
    pub min_bytes: i32,
    /// The maximum bytes to fetch.  See KIP-74 for cases where this limit may not be honored.
    pub max_bytes: i32,
    /// This setting controls the visibility of transactional records. Using READ_UNCOMMITTED (isolation_level = 0) makes all records visible. With READ_COMMITTED (isolation_level = 1), non-transactional and COMMITTED transactional records are visible. To be more concrete, READ_COMMITTED returns all data from offsets smaller than the current LSO (last stable offset), and enables the inclusion of the list of aborted transactions in the result, which allows consumers to discard ABORTED transactional records.
    pub isolation_level: i8,
    /// The fetch session ID.
    pub session_id: i32,
    /// The fetch session epoch, which is used for ordering requests in a session.
    pub session_epoch: i32,
    /// The topics to fetch.
    pub topics: Vec<FetchTopic>,
    /// In an incremental fetch request, the partitions to remove.
    pub forgotten_topics_data: Vec<ForgottenTopic>,
    /// Rack ID of the consumer making this request.
    pub rack_id: String,
    /// The clusterId if known. This is used to validate metadata fetches prior to broker registration.
    /// (Tagged field 0; `None` = absent on the wire.)
    pub cluster_id: Option<Option<String>>,
    /// The state of the replica in the follower.
    /// (Tagged field 1; `None` = absent on the wire.)
    pub replica_state: Option<ReplicaState>,
    /// Tagged fields not (yet) known to this crate, kept raw.
    pub unknown_tagged_fields: Vec<RawTaggedField>,
}

impl Default for FetchRequest {
    fn default() -> Self {
        Self {
            replica_id: -1,
            max_wait_ms: 0,
            min_bytes: 0,
            max_bytes: 2147483647,
            isolation_level: 0,
            session_id: 0,
            session_epoch: -1,
            topics: Vec::new(),
            forgotten_topics_data: Vec::new(),
            rack_id: "".to_string(),
            cluster_id: None,
            replica_state: None,
            unknown_tagged_fields: Vec::new(),
        }
    }
}

impl FetchRequest {
    pub const API_KEY: i16 = 1;
    pub const MIN_VERSION: i16 = 4;
    pub const MAX_VERSION: i16 = 18;

    pub fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        if version <= 14 {
            buf.put_i32(self.replica_id);
        }
        buf.put_i32(self.max_wait_ms);
        buf.put_i32(self.min_bytes);
        buf.put_i32(self.max_bytes);
        buf.put_i8(self.isolation_level);
        if version >= 7 {
            buf.put_i32(self.session_id);
        }
        if version >= 7 {
            buf.put_i32(self.session_epoch);
        }
        if is_flexible(version) {
            wire::put_compact_array_len(buf, Some(self.topics.len()));
        } else {
            wire::put_array_len(buf, Some(self.topics.len()))?;
        }
        for item in &self.topics {
            item.encode(buf, version)?;
        }
        if version >= 7 {
            if is_flexible(version) {
                wire::put_compact_array_len(buf, Some(self.forgotten_topics_data.len()));
            } else {
                wire::put_array_len(buf, Some(self.forgotten_topics_data.len()))?;
            }
            for item in &self.forgotten_topics_data {
                item.encode(buf, version)?;
            }
        }
        if version >= 11 {
            if is_flexible(version) {
                wire::put_compact_string(buf, &self.rack_id);
            } else {
                wire::put_string(buf, &self.rack_id)?;
            }
        }
        if is_flexible(version) {
            let mut tagged = self.unknown_tagged_fields.clone();
            if version >= 12 {
                if let Some(v) = &self.cluster_id {
                    let mut tag_data = bytes::BytesMut::new();
                    {
                        let buf = &mut tag_data;
                        if (*v).is_none() && !(version >= 12) {
                            return Err(EncodeError::NullField("ClusterId"));
                        }
                        if is_flexible(version) {
                            wire::put_compact_nullable_string(buf, (*v).as_deref());
                        } else {
                            wire::put_nullable_string(buf, (*v).as_deref())?;
                        }
                    }
                    tagged.push(RawTaggedField {
                        tag: 0,
                        data: tag_data.freeze(),
                    });
                }
            }
            if version >= 15 {
                if let Some(v) = &self.replica_state {
                    let mut tag_data = bytes::BytesMut::new();
                    {
                        let buf = &mut tag_data;
                        (*v).encode(buf, version)?;
                    }
                    tagged.push(RawTaggedField {
                        tag: 1,
                        data: tag_data.freeze(),
                    });
                }
            }
            tagged.sort_by_key(|f| f.tag);
            wire::put_tagged_fields(buf, &tagged);
        }
        Ok(())
    }

    pub fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        let mut this = Self::default();
        if version <= 14 {
            this.replica_id = wire::get_i32(buf)?;
        }
        this.max_wait_ms = wire::get_i32(buf)?;
        this.min_bytes = wire::get_i32(buf)?;
        this.max_bytes = wire::get_i32(buf)?;
        this.isolation_level = wire::get_i8(buf)?;
        if version >= 7 {
            this.session_id = wire::get_i32(buf)?;
        }
        if version >= 7 {
            this.session_epoch = wire::get_i32(buf)?;
        }
        this.topics = {
            let len = if is_flexible(version) {
                wire::get_compact_array_len(buf)?
            } else {
                wire::get_array_len(buf)?
            };
            match len {
                None => return Err(DecodeError::InvalidLength(-1)),
                Some(n) => {
                    let mut items = Vec::new();
                    for _ in 0..n {
                        items.push(FetchTopic::decode(buf, version)?);
                    }
                    items
                }
            }
        };
        if version >= 7 {
            this.forgotten_topics_data = {
                let len = if is_flexible(version) {
                    wire::get_compact_array_len(buf)?
                } else {
                    wire::get_array_len(buf)?
                };
                match len {
                    None => return Err(DecodeError::InvalidLength(-1)),
                    Some(n) => {
                        let mut items = Vec::new();
                        for _ in 0..n {
                            items.push(ForgottenTopic::decode(buf, version)?);
                        }
                        items
                    }
                }
            };
        }
        if version >= 11 {
            this.rack_id = if is_flexible(version) {
                wire::get_compact_string(buf)?
            } else {
                wire::get_string(buf)?
            };
        }
        if is_flexible(version) {
            for raw in wire::get_tagged_fields(buf)? {
                if raw.tag == 0 && (version >= 12) {
                    let mut tag_data = raw.data;
                    let buf = &mut tag_data;
                    this.cluster_id = Some({
                        let raw = if is_flexible(version) {
                            wire::get_compact_nullable_string(buf)?
                        } else {
                            wire::get_nullable_string(buf)?
                        };
                        if raw.is_none() && !(version >= 12) {
                            return Err(DecodeError::InvalidLength(-1));
                        }
                        raw
                    });
                    if buf.has_remaining() {
                        return Err(DecodeError::InvalidLength(
                            i64::try_from(buf.remaining()).unwrap_or(i64::MAX),
                        ));
                    }
                } else if raw.tag == 1 && (version >= 15) {
                    let mut tag_data = raw.data;
                    let buf = &mut tag_data;
                    this.replica_state = Some(ReplicaState::decode(buf, version)?);
                    if buf.has_remaining() {
                        return Err(DecodeError::InvalidLength(
                            i64::try_from(buf.remaining()).unwrap_or(i64::MAX),
                        ));
                    }
                } else {
                    this.unknown_tagged_fields.push(raw);
                }
            }
        }
        Ok(this)
    }
}

/// `ReplicaState` (nested in [`FetchRequest`]).
#[derive(Debug, Clone, PartialEq)]
#[non_exhaustive]
pub struct ReplicaState {
    /// The replica ID of the follower, or -1 if this request is from a consumer.
    pub replica_id: i32,
    /// The epoch of this follower, or -1 if not available.
    pub replica_epoch: i64,
    /// Tagged fields not (yet) known to this crate, kept raw.
    pub unknown_tagged_fields: Vec<RawTaggedField>,
}

impl Default for ReplicaState {
    fn default() -> Self {
        Self {
            replica_id: -1,
            replica_epoch: -1,
            unknown_tagged_fields: Vec::new(),
        }
    }
}

impl ReplicaState {
    pub fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        if version >= 15 {
            buf.put_i32(self.replica_id);
        }
        if version >= 15 {
            buf.put_i64(self.replica_epoch);
        }
        if is_flexible(version) {
            wire::put_tagged_fields(buf, &self.unknown_tagged_fields);
        }
        Ok(())
    }

    pub fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        let mut this = Self::default();
        if version >= 15 {
            this.replica_id = wire::get_i32(buf)?;
        }
        if version >= 15 {
            this.replica_epoch = wire::get_i64(buf)?;
        }
        if is_flexible(version) {
            this.unknown_tagged_fields = wire::get_tagged_fields(buf)?;
        }
        Ok(this)
    }
}

/// `FetchTopic` (nested in [`FetchRequest`]).
#[derive(Debug, Clone, PartialEq)]
#[non_exhaustive]
pub struct FetchTopic {
    /// The name of the topic to fetch.
    pub topic: String,
    /// The unique topic ID.
    pub topic_id: [u8; 16],
    /// The partitions to fetch.
    pub partitions: Vec<FetchPartition>,
    /// Tagged fields not (yet) known to this crate, kept raw.
    pub unknown_tagged_fields: Vec<RawTaggedField>,
}

impl Default for FetchTopic {
    fn default() -> Self {
        Self {
            topic: String::new(),
            topic_id: [0u8; 16],
            partitions: Vec::new(),
            unknown_tagged_fields: Vec::new(),
        }
    }
}

impl FetchTopic {
    pub fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        if version <= 12 {
            if is_flexible(version) {
                wire::put_compact_string(buf, &self.topic);
            } else {
                wire::put_string(buf, &self.topic)?;
            }
        }
        if version >= 13 {
            wire::put_uuid(buf, self.topic_id);
        }
        if is_flexible(version) {
            wire::put_compact_array_len(buf, Some(self.partitions.len()));
        } else {
            wire::put_array_len(buf, Some(self.partitions.len()))?;
        }
        for item in &self.partitions {
            item.encode(buf, version)?;
        }
        if is_flexible(version) {
            wire::put_tagged_fields(buf, &self.unknown_tagged_fields);
        }
        Ok(())
    }

    pub fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        let mut this = Self::default();
        if version <= 12 {
            this.topic = if is_flexible(version) {
                wire::get_compact_string(buf)?
            } else {
                wire::get_string(buf)?
            };
        }
        if version >= 13 {
            this.topic_id = wire::get_uuid(buf)?;
        }
        this.partitions = {
            let len = if is_flexible(version) {
                wire::get_compact_array_len(buf)?
            } else {
                wire::get_array_len(buf)?
            };
            match len {
                None => return Err(DecodeError::InvalidLength(-1)),
                Some(n) => {
                    let mut items = Vec::new();
                    for _ in 0..n {
                        items.push(FetchPartition::decode(buf, version)?);
                    }
                    items
                }
            }
        };
        if is_flexible(version) {
            this.unknown_tagged_fields = wire::get_tagged_fields(buf)?;
        }
        Ok(this)
    }
}

/// `FetchPartition` (nested in [`FetchRequest`]).
#[derive(Debug, Clone, PartialEq)]
#[non_exhaustive]
pub struct FetchPartition {
    /// The partition index.
    pub partition: i32,
    /// The current leader epoch of the partition.
    pub current_leader_epoch: i32,
    /// The message offset.
    pub fetch_offset: i64,
    /// The epoch of the last fetched record or -1 if there is none.
    pub last_fetched_epoch: i32,
    /// The earliest available offset of the follower replica.  The field is only used when the request is sent by the follower.
    pub log_start_offset: i64,
    /// The maximum bytes to fetch from this partition.  See KIP-74 for cases where this limit may not be honored.
    pub partition_max_bytes: i32,
    /// The directory id of the follower fetching.
    /// (Tagged field 0; `None` = absent on the wire.)
    pub replica_directory_id: Option<[u8; 16]>,
    /// The high-watermark known by the replica. -1 if the high-watermark is not known and 9223372036854775807 if the feature is not supported.
    /// (Tagged field 1; `None` = absent on the wire.)
    pub high_watermark: Option<i64>,
    /// Tagged fields not (yet) known to this crate, kept raw.
    pub unknown_tagged_fields: Vec<RawTaggedField>,
}

impl Default for FetchPartition {
    fn default() -> Self {
        Self {
            partition: 0,
            current_leader_epoch: -1,
            fetch_offset: 0,
            last_fetched_epoch: -1,
            log_start_offset: -1,
            partition_max_bytes: 0,
            replica_directory_id: None,
            high_watermark: None,
            unknown_tagged_fields: Vec::new(),
        }
    }
}

impl FetchPartition {
    pub fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        buf.put_i32(self.partition);
        if version >= 9 {
            buf.put_i32(self.current_leader_epoch);
        }
        buf.put_i64(self.fetch_offset);
        if version >= 12 {
            buf.put_i32(self.last_fetched_epoch);
        }
        if version >= 5 {
            buf.put_i64(self.log_start_offset);
        }
        buf.put_i32(self.partition_max_bytes);
        if is_flexible(version) {
            let mut tagged = self.unknown_tagged_fields.clone();
            if version >= 17 {
                if let Some(v) = &self.replica_directory_id {
                    let mut tag_data = bytes::BytesMut::new();
                    {
                        let buf = &mut tag_data;
                        wire::put_uuid(buf, (*v));
                    }
                    tagged.push(RawTaggedField {
                        tag: 0,
                        data: tag_data.freeze(),
                    });
                }
            }
            if version >= 18 {
                if let Some(v) = &self.high_watermark {
                    let mut tag_data = bytes::BytesMut::new();
                    {
                        let buf = &mut tag_data;
                        buf.put_i64((*v));
                    }
                    tagged.push(RawTaggedField {
                        tag: 1,
                        data: tag_data.freeze(),
                    });
                }
            }
            tagged.sort_by_key(|f| f.tag);
            wire::put_tagged_fields(buf, &tagged);
        }
        Ok(())
    }

    pub fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        let mut this = Self::default();
        this.partition = wire::get_i32(buf)?;
        if version >= 9 {
            this.current_leader_epoch = wire::get_i32(buf)?;
        }
        this.fetch_offset = wire::get_i64(buf)?;
        if version >= 12 {
            this.last_fetched_epoch = wire::get_i32(buf)?;
        }
        if version >= 5 {
            this.log_start_offset = wire::get_i64(buf)?;
        }
        this.partition_max_bytes = wire::get_i32(buf)?;
        if is_flexible(version) {
            for raw in wire::get_tagged_fields(buf)? {
                if raw.tag == 0 && (version >= 17) {
                    let mut tag_data = raw.data;
                    let buf = &mut tag_data;
                    this.replica_directory_id = Some(wire::get_uuid(buf)?);
                    if buf.has_remaining() {
                        return Err(DecodeError::InvalidLength(
                            i64::try_from(buf.remaining()).unwrap_or(i64::MAX),
                        ));
                    }
                } else if raw.tag == 1 && (version >= 18) {
                    let mut tag_data = raw.data;
                    let buf = &mut tag_data;
                    this.high_watermark = Some(wire::get_i64(buf)?);
                    if buf.has_remaining() {
                        return Err(DecodeError::InvalidLength(
                            i64::try_from(buf.remaining()).unwrap_or(i64::MAX),
                        ));
                    }
                } else {
                    this.unknown_tagged_fields.push(raw);
                }
            }
        }
        Ok(this)
    }
}

/// `ForgottenTopic` (nested in [`FetchRequest`]).
#[derive(Debug, Clone, PartialEq)]
#[non_exhaustive]
pub struct ForgottenTopic {
    /// The topic name.
    pub topic: String,
    /// The unique topic ID.
    pub topic_id: [u8; 16],
    /// The partitions indexes to forget.
    pub partitions: Vec<i32>,
    /// Tagged fields not (yet) known to this crate, kept raw.
    pub unknown_tagged_fields: Vec<RawTaggedField>,
}

impl Default for ForgottenTopic {
    fn default() -> Self {
        Self {
            topic: String::new(),
            topic_id: [0u8; 16],
            partitions: Vec::new(),
            unknown_tagged_fields: Vec::new(),
        }
    }
}

impl ForgottenTopic {
    pub fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        if (7..=12).contains(&version) {
            if is_flexible(version) {
                wire::put_compact_string(buf, &self.topic);
            } else {
                wire::put_string(buf, &self.topic)?;
            }
        }
        if version >= 13 {
            wire::put_uuid(buf, self.topic_id);
        }
        if version >= 7 {
            if is_flexible(version) {
                wire::put_compact_array_len(buf, Some(self.partitions.len()));
            } else {
                wire::put_array_len(buf, Some(self.partitions.len()))?;
            }
            for item in &self.partitions {
                buf.put_i32(*item);
            }
        }
        if is_flexible(version) {
            wire::put_tagged_fields(buf, &self.unknown_tagged_fields);
        }
        Ok(())
    }

    pub fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        let mut this = Self::default();
        if (7..=12).contains(&version) {
            this.topic = if is_flexible(version) {
                wire::get_compact_string(buf)?
            } else {
                wire::get_string(buf)?
            };
        }
        if version >= 13 {
            this.topic_id = wire::get_uuid(buf)?;
        }
        if version >= 7 {
            this.partitions = {
                let len = if is_flexible(version) {
                    wire::get_compact_array_len(buf)?
                } else {
                    wire::get_array_len(buf)?
                };
                match len {
                    None => return Err(DecodeError::InvalidLength(-1)),
                    Some(n) => {
                        let mut items = Vec::new();
                        for _ in 0..n {
                            items.push(wire::get_i32(buf)?);
                        }
                        items
                    }
                }
            };
        }
        if is_flexible(version) {
            this.unknown_tagged_fields = wire::get_tagged_fields(buf)?;
        }
        Ok(this)
    }
}
