//! `InitProducerIdRequest` — generated from `schemas/InitProducerIdRequest.json`.
//!
//! @generated by `cargo xtask codegen`. Do not edit by hand.

#![allow(
    clippy::field_reassign_with_default,
    clippy::nonminimal_bool,
    clippy::derivable_impls,
    clippy::borrow_deref_ref,
    clippy::double_parens,
    unused_parens
)]

use bytes::{Buf, BufMut};

use crate::budget::{Budget, Limits};
#[allow(unused_imports)]
use crate::error::{DecodeError, EncodeError};
use crate::wire::{self, RawTaggedField};

/// Whether `version` of this message uses the flexible (compact) encoding.
pub fn is_flexible(version: i16) -> bool {
    let _ = version;
    version >= 2
}

/// `InitProducerIdRequest`, versions 0-6.
#[derive(Debug, Clone, PartialEq)]
#[non_exhaustive]
pub struct InitProducerIdRequest {
    /// The transactional id, or null if the producer is not transactional.
    pub transactional_id: Option<String>,
    /// The time in ms to wait before aborting idle transactions sent by this producer. This is only relevant if a TransactionalId has been defined.
    pub transaction_timeout_ms: i32,
    /// The producer id. This is used to disambiguate requests if a transactional id is reused following its expiration.
    pub producer_id: i64,
    /// The producer's current epoch. This will be checked against the producer epoch on the broker, and the request will return an error if they do not match.
    pub producer_epoch: i16,
    /// True if the client wants to enable two-phase commit (2PC) protocol for transactions.
    pub enable2_pc: bool,
    /// True if the client wants to keep the currently ongoing transaction instead of aborting it.
    pub keep_prepared_txn: bool,
    /// Tagged fields not (yet) known to this crate, kept raw.
    pub unknown_tagged_fields: Vec<RawTaggedField>,
}

impl Default for InitProducerIdRequest {
    fn default() -> Self {
        Self {
            transactional_id: Some(String::new()),
            transaction_timeout_ms: 0,
            producer_id: -1,
            producer_epoch: -1,
            enable2_pc: false,
            keep_prepared_txn: false,
            unknown_tagged_fields: Vec::new(),
        }
    }
}

impl InitProducerIdRequest {
    /// This message's api key in Kafka's registry.
    pub const API_KEY: i16 = 22;
    /// The lowest schema version this snapshot can speak.
    pub const MIN_VERSION: i16 = 0;
    /// The highest schema version this snapshot can speak.
    pub const MAX_VERSION: i16 = 6;

    /// Encode this `InitProducerIdRequest` at `version`.
    pub fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        if is_flexible(version) {
            wire::put_compact_nullable_string(buf, self.transactional_id.as_deref());
        } else {
            wire::put_nullable_string(buf, self.transactional_id.as_deref())?;
        }
        buf.put_i32(self.transaction_timeout_ms);
        if version >= 3 {
            buf.put_i64(self.producer_id);
        }
        if version >= 3 {
            buf.put_i16(self.producer_epoch);
        }
        if version >= 6 {
            buf.put_u8(u8::from(self.enable2_pc));
        }
        if version >= 6 {
            buf.put_u8(u8::from(self.keep_prepared_txn));
        }
        if is_flexible(version) {
            wire::put_tagged_fields(buf, &self.unknown_tagged_fields);
        }
        Ok(())
    }

    /// Decode one `InitProducerIdRequest`, bounding allocation by the default
    /// [`Limits`] derived from `buf`'s remaining length.
    pub fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        Self::decode_with_limits(buf, version, Limits::default())
    }

    /// Decode one `InitProducerIdRequest` under `limits`.
    pub fn decode_with_limits(
        buf: &mut impl Buf,
        version: i16,
        limits: Limits,
    ) -> Result<Self, DecodeError> {
        let mut budget = limits.budget(buf.remaining());
        Self::decode_with_budget(buf, version, &mut budget)
    }

    /// Decode one `InitProducerIdRequest` against an existing `budget`.
    pub fn decode_with_budget(
        buf: &mut impl Buf,
        version: i16,
        budget: &mut Budget,
    ) -> Result<Self, DecodeError> {
        let mut this = Self::default();
        this.transactional_id = if is_flexible(version) {
            wire::get_compact_nullable_string(buf)?
        } else {
            wire::get_nullable_string(buf)?
        };
        this.transaction_timeout_ms = wire::get_i32(buf)?;
        if version >= 3 {
            this.producer_id = wire::get_i64(buf)?;
        }
        if version >= 3 {
            this.producer_epoch = wire::get_i16(buf)?;
        }
        if version >= 6 {
            this.enable2_pc = wire::get_bool(buf)?;
        }
        if version >= 6 {
            this.keep_prepared_txn = wire::get_bool(buf)?;
        }
        if is_flexible(version) {
            this.unknown_tagged_fields = wire::get_tagged_fields_with_budget(buf, budget)?;
        }
        Ok(this)
    }
}

impl crate::Message for InitProducerIdRequest {
    const API_KEY: i16 = 22;
    const MIN_VERSION: i16 = 0;
    const MAX_VERSION: i16 = 6;

    fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        InitProducerIdRequest::encode(self, buf, version)
    }
    fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        InitProducerIdRequest::decode(buf, version)
    }
    fn decode_with_limits(
        buf: &mut impl Buf,
        version: i16,
        limits: Limits,
    ) -> Result<Self, DecodeError> {
        InitProducerIdRequest::decode_with_limits(buf, version, limits)
    }
}
