//! `ListGroupsRequest` — generated from `schemas/ListGroupsRequest.json`.
//!
//! @generated by `cargo xtask codegen`. Do not edit by hand.

#![allow(
    clippy::field_reassign_with_default,
    clippy::nonminimal_bool,
    clippy::derivable_impls,
    clippy::borrow_deref_ref,
    clippy::double_parens,
    unused_parens
)]

use bytes::{Buf, BufMut};

use crate::budget::{Budget, Limits};
#[allow(unused_imports)]
use crate::error::{DecodeError, EncodeError};
use crate::wire::{self, RawTaggedField};

/// Whether `version` of this message uses the flexible (compact) encoding.
pub fn is_flexible(version: i16) -> bool {
    let _ = version;
    version >= 3
}

/// `ListGroupsRequest`, versions 0-5.
#[derive(Debug, Clone, PartialEq)]
#[non_exhaustive]
pub struct ListGroupsRequest {
    /// The states of the groups we want to list. If empty, all groups are returned with their state.
    pub states_filter: Vec<String>,
    /// The types of the groups we want to list. If empty, all groups are returned with their type.
    pub types_filter: Vec<String>,
    /// Tagged fields not (yet) known to this crate, kept raw.
    pub unknown_tagged_fields: Vec<RawTaggedField>,
}

impl Default for ListGroupsRequest {
    fn default() -> Self {
        Self {
            states_filter: Vec::new(),
            types_filter: Vec::new(),
            unknown_tagged_fields: Vec::new(),
        }
    }
}

impl ListGroupsRequest {
    /// This message's api key in Kafka's registry.
    pub const API_KEY: i16 = 16;
    /// The lowest schema version this snapshot can speak.
    pub const MIN_VERSION: i16 = 0;
    /// The highest schema version this snapshot can speak.
    pub const MAX_VERSION: i16 = 5;

    /// Encode this `ListGroupsRequest` at `version`.
    pub fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        if version >= 4 {
            if is_flexible(version) {
                wire::put_compact_array_len(buf, Some(self.states_filter.len()));
            } else {
                wire::put_array_len(buf, Some(self.states_filter.len()))?;
            }
            for item in &self.states_filter {
                if is_flexible(version) {
                    wire::put_compact_string(buf, item);
                } else {
                    wire::put_string(buf, item)?;
                }
            }
        }
        if version >= 5 {
            if is_flexible(version) {
                wire::put_compact_array_len(buf, Some(self.types_filter.len()));
            } else {
                wire::put_array_len(buf, Some(self.types_filter.len()))?;
            }
            for item in &self.types_filter {
                if is_flexible(version) {
                    wire::put_compact_string(buf, item);
                } else {
                    wire::put_string(buf, item)?;
                }
            }
        }
        if is_flexible(version) {
            wire::put_tagged_fields(buf, &self.unknown_tagged_fields);
        }
        Ok(())
    }

    /// Decode one `ListGroupsRequest`, bounding allocation by the default
    /// [`Limits`] derived from `buf`'s remaining length.
    pub fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        Self::decode_with_limits(buf, version, Limits::default())
    }

    /// Decode one `ListGroupsRequest` under `limits`.
    pub fn decode_with_limits(
        buf: &mut impl Buf,
        version: i16,
        limits: Limits,
    ) -> Result<Self, DecodeError> {
        let mut budget = limits.budget(buf.remaining());
        Self::decode_with_budget(buf, version, &mut budget)
    }

    /// Decode one `ListGroupsRequest` against an existing `budget`.
    pub fn decode_with_budget(
        buf: &mut impl Buf,
        version: i16,
        budget: &mut Budget,
    ) -> Result<Self, DecodeError> {
        let mut this = Self::default();
        if version >= 4 {
            this.states_filter = {
                let len = if is_flexible(version) {
                    wire::get_compact_array_len(buf)?
                } else {
                    wire::get_array_len(buf)?
                };
                match len {
                    None => return Err(DecodeError::InvalidLength(-1)),
                    Some(n) => {
                        let mut items = Vec::new();
                        for _ in 0..n {
                            budget.push(
                                &mut items,
                                if is_flexible(version) {
                                    wire::get_compact_string(buf)?
                                } else {
                                    wire::get_string(buf)?
                                },
                            )?;
                        }
                        items
                    }
                }
            };
        }
        if version >= 5 {
            this.types_filter = {
                let len = if is_flexible(version) {
                    wire::get_compact_array_len(buf)?
                } else {
                    wire::get_array_len(buf)?
                };
                match len {
                    None => return Err(DecodeError::InvalidLength(-1)),
                    Some(n) => {
                        let mut items = Vec::new();
                        for _ in 0..n {
                            budget.push(
                                &mut items,
                                if is_flexible(version) {
                                    wire::get_compact_string(buf)?
                                } else {
                                    wire::get_string(buf)?
                                },
                            )?;
                        }
                        items
                    }
                }
            };
        }
        if is_flexible(version) {
            this.unknown_tagged_fields = wire::get_tagged_fields_with_budget(buf, budget)?;
        }
        Ok(this)
    }
}

impl crate::Message for ListGroupsRequest {
    const API_KEY: i16 = 16;
    const MIN_VERSION: i16 = 0;
    const MAX_VERSION: i16 = 5;

    fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        ListGroupsRequest::encode(self, buf, version)
    }
    fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        ListGroupsRequest::decode(buf, version)
    }
    fn decode_with_limits(
        buf: &mut impl Buf,
        version: i16,
        limits: Limits,
    ) -> Result<Self, DecodeError> {
        ListGroupsRequest::decode_with_limits(buf, version, limits)
    }
}
