//! Kafka message types generated from the vendored schemas.
//!
//! @generated by `cargo xtask codegen`. Do not edit by hand; edit the
//! schemas or the generator and re-run.

pub mod api_versions_request;
pub mod api_versions_response;
pub mod create_topics_request;
pub mod create_topics_response;
pub mod fetch_request;
pub mod fetch_response;
pub mod metadata_request;
pub mod metadata_response;
pub mod produce_request;
pub mod produce_response;
pub mod request_header;
pub mod response_header;

pub use api_versions_request::ApiVersionsRequest;
pub use api_versions_response::ApiVersionsResponse;
pub use create_topics_request::CreateTopicsRequest;
pub use create_topics_response::CreateTopicsResponse;
pub use fetch_request::FetchRequest;
pub use fetch_response::FetchResponse;
pub use metadata_request::MetadataRequest;
pub use metadata_response::MetadataResponse;
pub use produce_request::ProduceRequest;
pub use produce_response::ProduceResponse;
pub use request_header::RequestHeader;
pub use response_header::ResponseHeader;

/// Whether `api_version` of the request identified by `api_key` uses the
/// flexible (compact) encoding. `None` when the api key has no generated
/// message type in this crate.
pub fn request_is_flexible(api_key: i16, api_version: i16) -> Option<bool> {
    match api_key {
        18 => Some(api_versions_request::is_flexible(api_version)),
        19 => Some(create_topics_request::is_flexible(api_version)),
        1 => Some(fetch_request::is_flexible(api_version)),
        3 => Some(metadata_request::is_flexible(api_version)),
        0 => Some(produce_request::is_flexible(api_version)),
        _ => None,
    }
}
