//! `OffsetFetchResponse` — generated from `schemas/OffsetFetchResponse.json`.
//!
//! @generated by `cargo xtask codegen`. Do not edit by hand.

#![allow(
    clippy::field_reassign_with_default,
    clippy::nonminimal_bool,
    clippy::derivable_impls,
    clippy::borrow_deref_ref,
    clippy::double_parens,
    unused_parens
)]

use bytes::{Buf, BufMut};

use crate::budget::{Budget, Limits};
#[allow(unused_imports)]
use crate::error::{DecodeError, EncodeError};
use crate::wire::{self, RawTaggedField};

/// Whether `version` of this message uses the flexible (compact) encoding.
pub fn is_flexible(version: i16) -> bool {
    let _ = version;
    version >= 6
}

/// `OffsetFetchResponse`, versions 1-10.
#[derive(Debug, Clone, PartialEq)]
#[non_exhaustive]
pub struct OffsetFetchResponse {
    /// The duration in milliseconds for which the request was throttled due to a quota violation, or zero if the request did not violate any quota.
    pub throttle_time_ms: i32,
    /// The responses per topic.
    pub topics: Vec<OffsetFetchResponseTopic>,
    /// The top-level error code, or 0 if there was no error.
    pub error_code: i16,
    /// The responses per group id.
    pub groups: Vec<OffsetFetchResponseGroup>,
    /// Tagged fields not (yet) known to this crate, kept raw.
    pub unknown_tagged_fields: Vec<RawTaggedField>,
}

impl Default for OffsetFetchResponse {
    fn default() -> Self {
        Self {
            throttle_time_ms: 0,
            topics: Vec::new(),
            error_code: 0,
            groups: Vec::new(),
            unknown_tagged_fields: Vec::new(),
        }
    }
}

impl OffsetFetchResponse {
    /// This message's api key in Kafka's registry.
    pub const API_KEY: i16 = 9;
    /// The lowest schema version this snapshot can speak.
    pub const MIN_VERSION: i16 = 1;
    /// The highest schema version this snapshot can speak.
    pub const MAX_VERSION: i16 = 10;

    /// Encode this `OffsetFetchResponse` at `version`.
    pub fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        if version >= 3 {
            buf.put_i32(self.throttle_time_ms);
        }
        if version <= 7 {
            if is_flexible(version) {
                wire::put_compact_array_len(buf, Some(self.topics.len()));
            } else {
                wire::put_array_len(buf, Some(self.topics.len()))?;
            }
            for item in &self.topics {
                item.encode(buf, version)?;
            }
        }
        if (2..=7).contains(&version) {
            buf.put_i16(self.error_code);
        }
        if version >= 8 {
            if is_flexible(version) {
                wire::put_compact_array_len(buf, Some(self.groups.len()));
            } else {
                wire::put_array_len(buf, Some(self.groups.len()))?;
            }
            for item in &self.groups {
                item.encode(buf, version)?;
            }
        }
        if is_flexible(version) {
            wire::put_tagged_fields(buf, &self.unknown_tagged_fields);
        }
        Ok(())
    }

    /// Decode one `OffsetFetchResponse`, bounding allocation by the default
    /// [`Limits`] derived from `buf`'s remaining length.
    pub fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        Self::decode_with_limits(buf, version, Limits::default())
    }

    /// Decode one `OffsetFetchResponse` under `limits`.
    pub fn decode_with_limits(
        buf: &mut impl Buf,
        version: i16,
        limits: Limits,
    ) -> Result<Self, DecodeError> {
        let mut budget = limits.budget(buf.remaining());
        Self::decode_with_budget(buf, version, &mut budget)
    }

    /// Decode one `OffsetFetchResponse` against an existing `budget`.
    pub fn decode_with_budget(
        buf: &mut impl Buf,
        version: i16,
        budget: &mut Budget,
    ) -> Result<Self, DecodeError> {
        let mut this = Self::default();
        if version >= 3 {
            this.throttle_time_ms = wire::get_i32(buf)?;
        }
        if version <= 7 {
            this.topics = {
                let len = if is_flexible(version) {
                    wire::get_compact_array_len(buf)?
                } else {
                    wire::get_array_len(buf)?
                };
                match len {
                    None => return Err(DecodeError::InvalidLength(-1)),
                    Some(n) => {
                        let mut items = Vec::new();
                        for _ in 0..n {
                            let mark = buf.remaining();
                            let item =
                                OffsetFetchResponseTopic::decode_with_budget(buf, version, budget)?;
                            budget.progress(mark, buf.remaining())?;
                            budget.push(&mut items, item)?;
                        }
                        items
                    }
                }
            };
        }
        if (2..=7).contains(&version) {
            this.error_code = wire::get_i16(buf)?;
        }
        if version >= 8 {
            this.groups = {
                let len = if is_flexible(version) {
                    wire::get_compact_array_len(buf)?
                } else {
                    wire::get_array_len(buf)?
                };
                match len {
                    None => return Err(DecodeError::InvalidLength(-1)),
                    Some(n) => {
                        let mut items = Vec::new();
                        for _ in 0..n {
                            let mark = buf.remaining();
                            let item =
                                OffsetFetchResponseGroup::decode_with_budget(buf, version, budget)?;
                            budget.progress(mark, buf.remaining())?;
                            budget.push(&mut items, item)?;
                        }
                        items
                    }
                }
            };
        }
        if is_flexible(version) {
            this.unknown_tagged_fields = wire::get_tagged_fields_with_budget(buf, budget)?;
        }
        Ok(this)
    }
}

impl crate::Message for OffsetFetchResponse {
    const API_KEY: i16 = 9;
    const MIN_VERSION: i16 = 1;
    const MAX_VERSION: i16 = 10;

    fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        OffsetFetchResponse::encode(self, buf, version)
    }
    fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        OffsetFetchResponse::decode(buf, version)
    }
    fn decode_with_limits(
        buf: &mut impl Buf,
        version: i16,
        limits: Limits,
    ) -> Result<Self, DecodeError> {
        OffsetFetchResponse::decode_with_limits(buf, version, limits)
    }
}

/// `OffsetFetchResponseTopic` (nested in [`OffsetFetchResponse`]).
#[derive(Debug, Clone, PartialEq)]
#[non_exhaustive]
pub struct OffsetFetchResponseTopic {
    /// The topic name.
    pub name: String,
    /// The responses per partition.
    pub partitions: Vec<OffsetFetchResponsePartition>,
    /// Tagged fields not (yet) known to this crate, kept raw.
    pub unknown_tagged_fields: Vec<RawTaggedField>,
}

impl Default for OffsetFetchResponseTopic {
    fn default() -> Self {
        Self {
            name: String::new(),
            partitions: Vec::new(),
            unknown_tagged_fields: Vec::new(),
        }
    }
}

impl OffsetFetchResponseTopic {
    /// Encode this `OffsetFetchResponseTopic` at `version`.
    pub fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        if version <= 7 {
            if is_flexible(version) {
                wire::put_compact_string(buf, &self.name);
            } else {
                wire::put_string(buf, &self.name)?;
            }
        }
        if version <= 7 {
            if is_flexible(version) {
                wire::put_compact_array_len(buf, Some(self.partitions.len()));
            } else {
                wire::put_array_len(buf, Some(self.partitions.len()))?;
            }
            for item in &self.partitions {
                item.encode(buf, version)?;
            }
        }
        if is_flexible(version) {
            wire::put_tagged_fields(buf, &self.unknown_tagged_fields);
        }
        Ok(())
    }

    /// Decode one `OffsetFetchResponseTopic`, bounding allocation by the default
    /// [`Limits`] derived from `buf`'s remaining length.
    pub fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        Self::decode_with_limits(buf, version, Limits::default())
    }

    /// Decode one `OffsetFetchResponseTopic` under `limits`.
    pub fn decode_with_limits(
        buf: &mut impl Buf,
        version: i16,
        limits: Limits,
    ) -> Result<Self, DecodeError> {
        let mut budget = limits.budget(buf.remaining());
        Self::decode_with_budget(buf, version, &mut budget)
    }

    /// Decode one `OffsetFetchResponseTopic` against an existing `budget`.
    pub fn decode_with_budget(
        buf: &mut impl Buf,
        version: i16,
        budget: &mut Budget,
    ) -> Result<Self, DecodeError> {
        let mut this = Self::default();
        if version <= 7 {
            this.name = if is_flexible(version) {
                wire::get_compact_string(buf)?
            } else {
                wire::get_string(buf)?
            };
        }
        if version <= 7 {
            this.partitions = {
                let len = if is_flexible(version) {
                    wire::get_compact_array_len(buf)?
                } else {
                    wire::get_array_len(buf)?
                };
                match len {
                    None => return Err(DecodeError::InvalidLength(-1)),
                    Some(n) => {
                        let mut items = Vec::new();
                        for _ in 0..n {
                            let mark = buf.remaining();
                            let item = OffsetFetchResponsePartition::decode_with_budget(
                                buf, version, budget,
                            )?;
                            budget.progress(mark, buf.remaining())?;
                            budget.push(&mut items, item)?;
                        }
                        items
                    }
                }
            };
        }
        if is_flexible(version) {
            this.unknown_tagged_fields = wire::get_tagged_fields_with_budget(buf, budget)?;
        }
        Ok(this)
    }
}

/// `OffsetFetchResponsePartition` (nested in [`OffsetFetchResponse`]).
#[derive(Debug, Clone, PartialEq)]
#[non_exhaustive]
pub struct OffsetFetchResponsePartition {
    /// The partition index.
    pub partition_index: i32,
    /// The committed message offset.
    pub committed_offset: i64,
    /// The leader epoch.
    pub committed_leader_epoch: i32,
    /// The partition metadata.
    pub metadata: Option<String>,
    /// The error code, or 0 if there was no error.
    pub error_code: i16,
    /// Tagged fields not (yet) known to this crate, kept raw.
    pub unknown_tagged_fields: Vec<RawTaggedField>,
}

impl Default for OffsetFetchResponsePartition {
    fn default() -> Self {
        Self {
            partition_index: 0,
            committed_offset: 0,
            committed_leader_epoch: -1,
            metadata: Some(String::new()),
            error_code: 0,
            unknown_tagged_fields: Vec::new(),
        }
    }
}

impl OffsetFetchResponsePartition {
    /// Encode this `OffsetFetchResponsePartition` at `version`.
    pub fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        if version <= 7 {
            buf.put_i32(self.partition_index);
        }
        if version <= 7 {
            buf.put_i64(self.committed_offset);
        }
        if (5..=7).contains(&version) {
            buf.put_i32(self.committed_leader_epoch);
        }
        if version <= 7 {
            if is_flexible(version) {
                wire::put_compact_nullable_string(buf, self.metadata.as_deref());
            } else {
                wire::put_nullable_string(buf, self.metadata.as_deref())?;
            }
        }
        if version <= 7 {
            buf.put_i16(self.error_code);
        }
        if is_flexible(version) {
            wire::put_tagged_fields(buf, &self.unknown_tagged_fields);
        }
        Ok(())
    }

    /// Decode one `OffsetFetchResponsePartition`, bounding allocation by the default
    /// [`Limits`] derived from `buf`'s remaining length.
    pub fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        Self::decode_with_limits(buf, version, Limits::default())
    }

    /// Decode one `OffsetFetchResponsePartition` under `limits`.
    pub fn decode_with_limits(
        buf: &mut impl Buf,
        version: i16,
        limits: Limits,
    ) -> Result<Self, DecodeError> {
        let mut budget = limits.budget(buf.remaining());
        Self::decode_with_budget(buf, version, &mut budget)
    }

    /// Decode one `OffsetFetchResponsePartition` against an existing `budget`.
    pub fn decode_with_budget(
        buf: &mut impl Buf,
        version: i16,
        budget: &mut Budget,
    ) -> Result<Self, DecodeError> {
        let mut this = Self::default();
        if version <= 7 {
            this.partition_index = wire::get_i32(buf)?;
        }
        if version <= 7 {
            this.committed_offset = wire::get_i64(buf)?;
        }
        if (5..=7).contains(&version) {
            this.committed_leader_epoch = wire::get_i32(buf)?;
        }
        if version <= 7 {
            this.metadata = if is_flexible(version) {
                wire::get_compact_nullable_string(buf)?
            } else {
                wire::get_nullable_string(buf)?
            };
        }
        if version <= 7 {
            this.error_code = wire::get_i16(buf)?;
        }
        if is_flexible(version) {
            this.unknown_tagged_fields = wire::get_tagged_fields_with_budget(buf, budget)?;
        }
        Ok(this)
    }
}

/// `OffsetFetchResponseGroup` (nested in [`OffsetFetchResponse`]).
#[derive(Debug, Clone, PartialEq)]
#[non_exhaustive]
pub struct OffsetFetchResponseGroup {
    /// The group ID.
    pub group_id: String,
    /// The responses per topic.
    pub topics: Vec<OffsetFetchResponseTopics>,
    /// The group-level error code, or 0 if there was no error.
    pub error_code: i16,
    /// Tagged fields not (yet) known to this crate, kept raw.
    pub unknown_tagged_fields: Vec<RawTaggedField>,
}

impl Default for OffsetFetchResponseGroup {
    fn default() -> Self {
        Self {
            group_id: String::new(),
            topics: Vec::new(),
            error_code: 0,
            unknown_tagged_fields: Vec::new(),
        }
    }
}

impl OffsetFetchResponseGroup {
    /// Encode this `OffsetFetchResponseGroup` at `version`.
    pub fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        if version >= 8 {
            if is_flexible(version) {
                wire::put_compact_string(buf, &self.group_id);
            } else {
                wire::put_string(buf, &self.group_id)?;
            }
        }
        if version >= 8 {
            if is_flexible(version) {
                wire::put_compact_array_len(buf, Some(self.topics.len()));
            } else {
                wire::put_array_len(buf, Some(self.topics.len()))?;
            }
            for item in &self.topics {
                item.encode(buf, version)?;
            }
        }
        if version >= 8 {
            buf.put_i16(self.error_code);
        }
        if is_flexible(version) {
            wire::put_tagged_fields(buf, &self.unknown_tagged_fields);
        }
        Ok(())
    }

    /// Decode one `OffsetFetchResponseGroup`, bounding allocation by the default
    /// [`Limits`] derived from `buf`'s remaining length.
    pub fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        Self::decode_with_limits(buf, version, Limits::default())
    }

    /// Decode one `OffsetFetchResponseGroup` under `limits`.
    pub fn decode_with_limits(
        buf: &mut impl Buf,
        version: i16,
        limits: Limits,
    ) -> Result<Self, DecodeError> {
        let mut budget = limits.budget(buf.remaining());
        Self::decode_with_budget(buf, version, &mut budget)
    }

    /// Decode one `OffsetFetchResponseGroup` against an existing `budget`.
    pub fn decode_with_budget(
        buf: &mut impl Buf,
        version: i16,
        budget: &mut Budget,
    ) -> Result<Self, DecodeError> {
        let mut this = Self::default();
        if version >= 8 {
            this.group_id = if is_flexible(version) {
                wire::get_compact_string(buf)?
            } else {
                wire::get_string(buf)?
            };
        }
        if version >= 8 {
            this.topics = {
                let len = if is_flexible(version) {
                    wire::get_compact_array_len(buf)?
                } else {
                    wire::get_array_len(buf)?
                };
                match len {
                    None => return Err(DecodeError::InvalidLength(-1)),
                    Some(n) => {
                        let mut items = Vec::new();
                        for _ in 0..n {
                            let mark = buf.remaining();
                            let item = OffsetFetchResponseTopics::decode_with_budget(
                                buf, version, budget,
                            )?;
                            budget.progress(mark, buf.remaining())?;
                            budget.push(&mut items, item)?;
                        }
                        items
                    }
                }
            };
        }
        if version >= 8 {
            this.error_code = wire::get_i16(buf)?;
        }
        if is_flexible(version) {
            this.unknown_tagged_fields = wire::get_tagged_fields_with_budget(buf, budget)?;
        }
        Ok(this)
    }
}

/// `OffsetFetchResponseTopics` (nested in [`OffsetFetchResponse`]).
#[derive(Debug, Clone, PartialEq)]
#[non_exhaustive]
pub struct OffsetFetchResponseTopics {
    /// The topic name.
    pub name: String,
    /// The topic ID.
    pub topic_id: [u8; 16],
    /// The responses per partition.
    pub partitions: Vec<OffsetFetchResponsePartitions>,
    /// Tagged fields not (yet) known to this crate, kept raw.
    pub unknown_tagged_fields: Vec<RawTaggedField>,
}

impl Default for OffsetFetchResponseTopics {
    fn default() -> Self {
        Self {
            name: String::new(),
            topic_id: [0u8; 16],
            partitions: Vec::new(),
            unknown_tagged_fields: Vec::new(),
        }
    }
}

impl OffsetFetchResponseTopics {
    /// Encode this `OffsetFetchResponseTopics` at `version`.
    pub fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        if (8..=9).contains(&version) {
            if is_flexible(version) {
                wire::put_compact_string(buf, &self.name);
            } else {
                wire::put_string(buf, &self.name)?;
            }
        }
        if version >= 10 {
            wire::put_uuid(buf, self.topic_id);
        }
        if version >= 8 {
            if is_flexible(version) {
                wire::put_compact_array_len(buf, Some(self.partitions.len()));
            } else {
                wire::put_array_len(buf, Some(self.partitions.len()))?;
            }
            for item in &self.partitions {
                item.encode(buf, version)?;
            }
        }
        if is_flexible(version) {
            wire::put_tagged_fields(buf, &self.unknown_tagged_fields);
        }
        Ok(())
    }

    /// Decode one `OffsetFetchResponseTopics`, bounding allocation by the default
    /// [`Limits`] derived from `buf`'s remaining length.
    pub fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        Self::decode_with_limits(buf, version, Limits::default())
    }

    /// Decode one `OffsetFetchResponseTopics` under `limits`.
    pub fn decode_with_limits(
        buf: &mut impl Buf,
        version: i16,
        limits: Limits,
    ) -> Result<Self, DecodeError> {
        let mut budget = limits.budget(buf.remaining());
        Self::decode_with_budget(buf, version, &mut budget)
    }

    /// Decode one `OffsetFetchResponseTopics` against an existing `budget`.
    pub fn decode_with_budget(
        buf: &mut impl Buf,
        version: i16,
        budget: &mut Budget,
    ) -> Result<Self, DecodeError> {
        let mut this = Self::default();
        if (8..=9).contains(&version) {
            this.name = if is_flexible(version) {
                wire::get_compact_string(buf)?
            } else {
                wire::get_string(buf)?
            };
        }
        if version >= 10 {
            this.topic_id = wire::get_uuid(buf)?;
        }
        if version >= 8 {
            this.partitions = {
                let len = if is_flexible(version) {
                    wire::get_compact_array_len(buf)?
                } else {
                    wire::get_array_len(buf)?
                };
                match len {
                    None => return Err(DecodeError::InvalidLength(-1)),
                    Some(n) => {
                        let mut items = Vec::new();
                        for _ in 0..n {
                            let mark = buf.remaining();
                            let item = OffsetFetchResponsePartitions::decode_with_budget(
                                buf, version, budget,
                            )?;
                            budget.progress(mark, buf.remaining())?;
                            budget.push(&mut items, item)?;
                        }
                        items
                    }
                }
            };
        }
        if is_flexible(version) {
            this.unknown_tagged_fields = wire::get_tagged_fields_with_budget(buf, budget)?;
        }
        Ok(this)
    }
}

/// `OffsetFetchResponsePartitions` (nested in [`OffsetFetchResponse`]).
#[derive(Debug, Clone, PartialEq)]
#[non_exhaustive]
pub struct OffsetFetchResponsePartitions {
    /// The partition index.
    pub partition_index: i32,
    /// The committed message offset.
    pub committed_offset: i64,
    /// The leader epoch.
    pub committed_leader_epoch: i32,
    /// The partition metadata.
    pub metadata: Option<String>,
    /// The partition-level error code, or 0 if there was no error.
    pub error_code: i16,
    /// Tagged fields not (yet) known to this crate, kept raw.
    pub unknown_tagged_fields: Vec<RawTaggedField>,
}

impl Default for OffsetFetchResponsePartitions {
    fn default() -> Self {
        Self {
            partition_index: 0,
            committed_offset: 0,
            committed_leader_epoch: -1,
            metadata: Some(String::new()),
            error_code: 0,
            unknown_tagged_fields: Vec::new(),
        }
    }
}

impl OffsetFetchResponsePartitions {
    /// Encode this `OffsetFetchResponsePartitions` at `version`.
    pub fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        if version >= 8 {
            buf.put_i32(self.partition_index);
        }
        if version >= 8 {
            buf.put_i64(self.committed_offset);
        }
        if version >= 8 {
            buf.put_i32(self.committed_leader_epoch);
        }
        if version >= 8 {
            if is_flexible(version) {
                wire::put_compact_nullable_string(buf, self.metadata.as_deref());
            } else {
                wire::put_nullable_string(buf, self.metadata.as_deref())?;
            }
        }
        if version >= 8 {
            buf.put_i16(self.error_code);
        }
        if is_flexible(version) {
            wire::put_tagged_fields(buf, &self.unknown_tagged_fields);
        }
        Ok(())
    }

    /// Decode one `OffsetFetchResponsePartitions`, bounding allocation by the default
    /// [`Limits`] derived from `buf`'s remaining length.
    pub fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        Self::decode_with_limits(buf, version, Limits::default())
    }

    /// Decode one `OffsetFetchResponsePartitions` under `limits`.
    pub fn decode_with_limits(
        buf: &mut impl Buf,
        version: i16,
        limits: Limits,
    ) -> Result<Self, DecodeError> {
        let mut budget = limits.budget(buf.remaining());
        Self::decode_with_budget(buf, version, &mut budget)
    }

    /// Decode one `OffsetFetchResponsePartitions` against an existing `budget`.
    pub fn decode_with_budget(
        buf: &mut impl Buf,
        version: i16,
        budget: &mut Budget,
    ) -> Result<Self, DecodeError> {
        let mut this = Self::default();
        if version >= 8 {
            this.partition_index = wire::get_i32(buf)?;
        }
        if version >= 8 {
            this.committed_offset = wire::get_i64(buf)?;
        }
        if version >= 8 {
            this.committed_leader_epoch = wire::get_i32(buf)?;
        }
        if version >= 8 {
            this.metadata = if is_flexible(version) {
                wire::get_compact_nullable_string(buf)?
            } else {
                wire::get_nullable_string(buf)?
            };
        }
        if version >= 8 {
            this.error_code = wire::get_i16(buf)?;
        }
        if is_flexible(version) {
            this.unknown_tagged_fields = wire::get_tagged_fields_with_budget(buf, budget)?;
        }
        Ok(this)
    }
}
