//! `OffsetCommitResponse` — generated from `schemas/OffsetCommitResponse.json`.
//!
//! @generated by `cargo xtask codegen`. Do not edit by hand.

#![allow(
    clippy::field_reassign_with_default,
    clippy::nonminimal_bool,
    clippy::derivable_impls,
    clippy::borrow_deref_ref,
    clippy::double_parens,
    unused_parens
)]

use bytes::{Buf, BufMut};

#[allow(unused_imports)]
use crate::error::{DecodeError, EncodeError};
use crate::wire::{self, RawTaggedField};

/// Whether `version` of this message uses the flexible (compact) encoding.
pub fn is_flexible(version: i16) -> bool {
    let _ = version;
    version >= 8
}

/// `OffsetCommitResponse`, versions 2-10.
#[derive(Debug, Clone, PartialEq)]
#[non_exhaustive]
pub struct OffsetCommitResponse {
    /// The duration in milliseconds for which the request was throttled due to a quota violation, or zero if the request did not violate any quota.
    pub throttle_time_ms: i32,
    /// The responses for each topic.
    pub topics: Vec<OffsetCommitResponseTopic>,
    /// Tagged fields not (yet) known to this crate, kept raw.
    pub unknown_tagged_fields: Vec<RawTaggedField>,
}

impl Default for OffsetCommitResponse {
    fn default() -> Self {
        Self {
            throttle_time_ms: 0,
            topics: Vec::new(),
            unknown_tagged_fields: Vec::new(),
        }
    }
}

impl OffsetCommitResponse {
    pub const API_KEY: i16 = 8;
    pub const MIN_VERSION: i16 = 2;
    pub const MAX_VERSION: i16 = 10;

    pub fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        if version >= 3 {
            buf.put_i32(self.throttle_time_ms);
        }
        if is_flexible(version) {
            wire::put_compact_array_len(buf, Some(self.topics.len()));
        } else {
            wire::put_array_len(buf, Some(self.topics.len()))?;
        }
        for item in &self.topics {
            item.encode(buf, version)?;
        }
        if is_flexible(version) {
            wire::put_tagged_fields(buf, &self.unknown_tagged_fields);
        }
        Ok(())
    }

    pub fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        let mut this = Self::default();
        if version >= 3 {
            this.throttle_time_ms = wire::get_i32(buf)?;
        }
        this.topics = {
            let len = if is_flexible(version) {
                wire::get_compact_array_len(buf)?
            } else {
                wire::get_array_len(buf)?
            };
            match len {
                None => return Err(DecodeError::InvalidLength(-1)),
                Some(n) => {
                    let mut items = Vec::new();
                    for _ in 0..n {
                        items.push(OffsetCommitResponseTopic::decode(buf, version)?);
                    }
                    items
                }
            }
        };
        if is_flexible(version) {
            this.unknown_tagged_fields = wire::get_tagged_fields(buf)?;
        }
        Ok(this)
    }
}

impl crate::Message for OffsetCommitResponse {
    const API_KEY: i16 = 8;
    const MIN_VERSION: i16 = 2;
    const MAX_VERSION: i16 = 10;

    fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        OffsetCommitResponse::encode(self, buf, version)
    }
    fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        OffsetCommitResponse::decode(buf, version)
    }
}

/// `OffsetCommitResponseTopic` (nested in [`OffsetCommitResponse`]).
#[derive(Debug, Clone, PartialEq)]
#[non_exhaustive]
pub struct OffsetCommitResponseTopic {
    /// The topic name.
    pub name: String,
    /// The topic ID.
    pub topic_id: [u8; 16],
    /// The responses for each partition in the topic.
    pub partitions: Vec<OffsetCommitResponsePartition>,
    /// Tagged fields not (yet) known to this crate, kept raw.
    pub unknown_tagged_fields: Vec<RawTaggedField>,
}

impl Default for OffsetCommitResponseTopic {
    fn default() -> Self {
        Self {
            name: String::new(),
            topic_id: [0u8; 16],
            partitions: Vec::new(),
            unknown_tagged_fields: Vec::new(),
        }
    }
}

impl OffsetCommitResponseTopic {
    pub fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        if version <= 9 {
            if is_flexible(version) {
                wire::put_compact_string(buf, &self.name);
            } else {
                wire::put_string(buf, &self.name)?;
            }
        }
        if version >= 10 {
            wire::put_uuid(buf, self.topic_id);
        }
        if is_flexible(version) {
            wire::put_compact_array_len(buf, Some(self.partitions.len()));
        } else {
            wire::put_array_len(buf, Some(self.partitions.len()))?;
        }
        for item in &self.partitions {
            item.encode(buf, version)?;
        }
        if is_flexible(version) {
            wire::put_tagged_fields(buf, &self.unknown_tagged_fields);
        }
        Ok(())
    }

    pub fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        let mut this = Self::default();
        if version <= 9 {
            this.name = if is_flexible(version) {
                wire::get_compact_string(buf)?
            } else {
                wire::get_string(buf)?
            };
        }
        if version >= 10 {
            this.topic_id = wire::get_uuid(buf)?;
        }
        this.partitions = {
            let len = if is_flexible(version) {
                wire::get_compact_array_len(buf)?
            } else {
                wire::get_array_len(buf)?
            };
            match len {
                None => return Err(DecodeError::InvalidLength(-1)),
                Some(n) => {
                    let mut items = Vec::new();
                    for _ in 0..n {
                        items.push(OffsetCommitResponsePartition::decode(buf, version)?);
                    }
                    items
                }
            }
        };
        if is_flexible(version) {
            this.unknown_tagged_fields = wire::get_tagged_fields(buf)?;
        }
        Ok(this)
    }
}

/// `OffsetCommitResponsePartition` (nested in [`OffsetCommitResponse`]).
#[derive(Debug, Clone, PartialEq)]
#[non_exhaustive]
pub struct OffsetCommitResponsePartition {
    /// The partition index.
    pub partition_index: i32,
    /// The error code, or 0 if there was no error.
    pub error_code: i16,
    /// Tagged fields not (yet) known to this crate, kept raw.
    pub unknown_tagged_fields: Vec<RawTaggedField>,
}

impl Default for OffsetCommitResponsePartition {
    fn default() -> Self {
        Self {
            partition_index: 0,
            error_code: 0,
            unknown_tagged_fields: Vec::new(),
        }
    }
}

impl OffsetCommitResponsePartition {
    pub fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        buf.put_i32(self.partition_index);
        buf.put_i16(self.error_code);
        if is_flexible(version) {
            wire::put_tagged_fields(buf, &self.unknown_tagged_fields);
        }
        Ok(())
    }

    pub fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        let mut this = Self::default();
        this.partition_index = wire::get_i32(buf)?;
        this.error_code = wire::get_i16(buf)?;
        if is_flexible(version) {
            this.unknown_tagged_fields = wire::get_tagged_fields(buf)?;
        }
        Ok(this)
    }
}
