//! `OffsetFetchRequest` — generated from `schemas/OffsetFetchRequest.json`.
//!
//! @generated by `cargo xtask codegen`. Do not edit by hand.

#![allow(
    clippy::field_reassign_with_default,
    clippy::nonminimal_bool,
    clippy::derivable_impls,
    clippy::borrow_deref_ref,
    clippy::double_parens,
    unused_parens
)]

use bytes::{Buf, BufMut};

use crate::budget::{Budget, Limits};
#[allow(unused_imports)]
use crate::error::{DecodeError, EncodeError};
use crate::wire::{self, RawTaggedField};

/// Whether `version` of this message uses the flexible (compact) encoding.
pub fn is_flexible(version: i16) -> bool {
    let _ = version;
    version >= 6
}

/// `OffsetFetchRequest`, versions 1-10.
#[derive(Debug, Clone, PartialEq)]
#[non_exhaustive]
pub struct OffsetFetchRequest {
    /// The group to fetch offsets for.
    pub group_id: String,
    /// Each topic we would like to fetch offsets for, or null to fetch offsets for all topics.
    pub topics: Option<Vec<OffsetFetchRequestTopic>>,
    /// Each group we would like to fetch offsets for.
    pub groups: Vec<OffsetFetchRequestGroup>,
    /// Whether broker should hold on returning unstable offsets but set a retriable error code for the partitions.
    pub require_stable: bool,
    /// Tagged fields not (yet) known to this crate, kept raw.
    pub unknown_tagged_fields: Vec<RawTaggedField>,
}

impl Default for OffsetFetchRequest {
    fn default() -> Self {
        Self {
            group_id: String::new(),
            topics: Some(Vec::new()),
            groups: Vec::new(),
            require_stable: false,
            unknown_tagged_fields: Vec::new(),
        }
    }
}

impl OffsetFetchRequest {
    pub const API_KEY: i16 = 9;
    pub const MIN_VERSION: i16 = 1;
    pub const MAX_VERSION: i16 = 10;

    pub fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        if version <= 7 {
            if is_flexible(version) {
                wire::put_compact_string(buf, &self.group_id);
            } else {
                wire::put_string(buf, &self.group_id)?;
            }
        }
        if version <= 7 {
            match &self.topics {
                Some(items) => {
                    if is_flexible(version) {
                        wire::put_compact_array_len(buf, Some(items.len()));
                    } else {
                        wire::put_array_len(buf, Some(items.len()))?;
                    }
                    for item in items {
                        item.encode(buf, version)?;
                    }
                }
                None => {
                    if !(version >= 2) {
                        return Err(EncodeError::NullField("Topics"));
                    }
                    if is_flexible(version) {
                        wire::put_compact_array_len(buf, None);
                    } else {
                        wire::put_array_len(buf, None)?;
                    }
                }
            }
        }
        if version >= 8 {
            if is_flexible(version) {
                wire::put_compact_array_len(buf, Some(self.groups.len()));
            } else {
                wire::put_array_len(buf, Some(self.groups.len()))?;
            }
            for item in &self.groups {
                item.encode(buf, version)?;
            }
        }
        if version >= 7 {
            buf.put_u8(u8::from(self.require_stable));
        }
        if is_flexible(version) {
            wire::put_tagged_fields(buf, &self.unknown_tagged_fields);
        }
        Ok(())
    }

    /// Decode one `OffsetFetchRequest`, bounding allocation by the default
    /// [`Limits`] derived from `buf`'s remaining length.
    pub fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        Self::decode_with_limits(buf, version, Limits::default())
    }

    /// Decode one `OffsetFetchRequest` under `limits`.
    pub fn decode_with_limits(
        buf: &mut impl Buf,
        version: i16,
        limits: Limits,
    ) -> Result<Self, DecodeError> {
        let mut budget = limits.budget(buf.remaining());
        Self::decode_with_budget(buf, version, &mut budget)
    }

    /// Decode one `OffsetFetchRequest` against an existing `budget`.
    pub fn decode_with_budget(
        buf: &mut impl Buf,
        version: i16,
        budget: &mut Budget,
    ) -> Result<Self, DecodeError> {
        let mut this = Self::default();
        if version <= 7 {
            this.group_id = if is_flexible(version) {
                wire::get_compact_string(buf)?
            } else {
                wire::get_string(buf)?
            };
        }
        if version <= 7 {
            this.topics = {
                let len = if is_flexible(version) {
                    wire::get_compact_array_len(buf)?
                } else {
                    wire::get_array_len(buf)?
                };
                match len {
                    None => {
                        if !(version >= 2) {
                            return Err(DecodeError::InvalidLength(-1));
                        }
                        None
                    }
                    Some(n) => {
                        let mut items = Vec::new();
                        for _ in 0..n {
                            let mark = buf.remaining();
                            let item =
                                OffsetFetchRequestTopic::decode_with_budget(buf, version, budget)?;
                            budget.progress(mark, buf.remaining())?;
                            budget.push(&mut items, item)?;
                        }
                        Some(items)
                    }
                }
            };
        }
        if version >= 8 {
            this.groups = {
                let len = if is_flexible(version) {
                    wire::get_compact_array_len(buf)?
                } else {
                    wire::get_array_len(buf)?
                };
                match len {
                    None => return Err(DecodeError::InvalidLength(-1)),
                    Some(n) => {
                        let mut items = Vec::new();
                        for _ in 0..n {
                            let mark = buf.remaining();
                            let item =
                                OffsetFetchRequestGroup::decode_with_budget(buf, version, budget)?;
                            budget.progress(mark, buf.remaining())?;
                            budget.push(&mut items, item)?;
                        }
                        items
                    }
                }
            };
        }
        if version >= 7 {
            this.require_stable = wire::get_bool(buf)?;
        }
        if is_flexible(version) {
            this.unknown_tagged_fields = wire::get_tagged_fields_with_budget(buf, budget)?;
        }
        Ok(this)
    }
}

impl crate::Message for OffsetFetchRequest {
    const API_KEY: i16 = 9;
    const MIN_VERSION: i16 = 1;
    const MAX_VERSION: i16 = 10;

    fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        OffsetFetchRequest::encode(self, buf, version)
    }
    fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        OffsetFetchRequest::decode(buf, version)
    }
    fn decode_with_limits(
        buf: &mut impl Buf,
        version: i16,
        limits: Limits,
    ) -> Result<Self, DecodeError> {
        OffsetFetchRequest::decode_with_limits(buf, version, limits)
    }
}

/// `OffsetFetchRequestTopic` (nested in [`OffsetFetchRequest`]).
#[derive(Debug, Clone, PartialEq)]
#[non_exhaustive]
pub struct OffsetFetchRequestTopic {
    /// The topic name.
    pub name: String,
    /// The partition indexes we would like to fetch offsets for.
    pub partition_indexes: Vec<i32>,
    /// Tagged fields not (yet) known to this crate, kept raw.
    pub unknown_tagged_fields: Vec<RawTaggedField>,
}

impl Default for OffsetFetchRequestTopic {
    fn default() -> Self {
        Self {
            name: String::new(),
            partition_indexes: Vec::new(),
            unknown_tagged_fields: Vec::new(),
        }
    }
}

impl OffsetFetchRequestTopic {
    pub fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        if version <= 7 {
            if is_flexible(version) {
                wire::put_compact_string(buf, &self.name);
            } else {
                wire::put_string(buf, &self.name)?;
            }
        }
        if version <= 7 {
            if is_flexible(version) {
                wire::put_compact_array_len(buf, Some(self.partition_indexes.len()));
            } else {
                wire::put_array_len(buf, Some(self.partition_indexes.len()))?;
            }
            for item in &self.partition_indexes {
                buf.put_i32(*item);
            }
        }
        if is_flexible(version) {
            wire::put_tagged_fields(buf, &self.unknown_tagged_fields);
        }
        Ok(())
    }

    /// Decode one `OffsetFetchRequestTopic`, bounding allocation by the default
    /// [`Limits`] derived from `buf`'s remaining length.
    pub fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        Self::decode_with_limits(buf, version, Limits::default())
    }

    /// Decode one `OffsetFetchRequestTopic` under `limits`.
    pub fn decode_with_limits(
        buf: &mut impl Buf,
        version: i16,
        limits: Limits,
    ) -> Result<Self, DecodeError> {
        let mut budget = limits.budget(buf.remaining());
        Self::decode_with_budget(buf, version, &mut budget)
    }

    /// Decode one `OffsetFetchRequestTopic` against an existing `budget`.
    pub fn decode_with_budget(
        buf: &mut impl Buf,
        version: i16,
        budget: &mut Budget,
    ) -> Result<Self, DecodeError> {
        let mut this = Self::default();
        if version <= 7 {
            this.name = if is_flexible(version) {
                wire::get_compact_string(buf)?
            } else {
                wire::get_string(buf)?
            };
        }
        if version <= 7 {
            this.partition_indexes = {
                let len = if is_flexible(version) {
                    wire::get_compact_array_len(buf)?
                } else {
                    wire::get_array_len(buf)?
                };
                match len {
                    None => return Err(DecodeError::InvalidLength(-1)),
                    Some(n) => {
                        let mut items = Vec::new();
                        for _ in 0..n {
                            budget.push(&mut items, wire::get_i32(buf)?)?;
                        }
                        items
                    }
                }
            };
        }
        if is_flexible(version) {
            this.unknown_tagged_fields = wire::get_tagged_fields_with_budget(buf, budget)?;
        }
        Ok(this)
    }
}

/// `OffsetFetchRequestGroup` (nested in [`OffsetFetchRequest`]).
#[derive(Debug, Clone, PartialEq)]
#[non_exhaustive]
pub struct OffsetFetchRequestGroup {
    /// The group ID.
    pub group_id: String,
    /// The member id.
    pub member_id: Option<String>,
    /// The member epoch if using the new consumer protocol (KIP-848).
    pub member_epoch: i32,
    /// Each topic we would like to fetch offsets for, or null to fetch offsets for all topics.
    pub topics: Option<Vec<OffsetFetchRequestTopics>>,
    /// Tagged fields not (yet) known to this crate, kept raw.
    pub unknown_tagged_fields: Vec<RawTaggedField>,
}

impl Default for OffsetFetchRequestGroup {
    fn default() -> Self {
        Self {
            group_id: String::new(),
            member_id: None,
            member_epoch: -1,
            topics: Some(Vec::new()),
            unknown_tagged_fields: Vec::new(),
        }
    }
}

impl OffsetFetchRequestGroup {
    pub fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        if version >= 8 {
            if is_flexible(version) {
                wire::put_compact_string(buf, &self.group_id);
            } else {
                wire::put_string(buf, &self.group_id)?;
            }
        }
        if version >= 9 {
            if is_flexible(version) {
                wire::put_compact_nullable_string(buf, self.member_id.as_deref());
            } else {
                wire::put_nullable_string(buf, self.member_id.as_deref())?;
            }
        }
        if version >= 9 {
            buf.put_i32(self.member_epoch);
        }
        if version >= 8 {
            match &self.topics {
                Some(items) => {
                    if is_flexible(version) {
                        wire::put_compact_array_len(buf, Some(items.len()));
                    } else {
                        wire::put_array_len(buf, Some(items.len()))?;
                    }
                    for item in items {
                        item.encode(buf, version)?;
                    }
                }
                None => {
                    if is_flexible(version) {
                        wire::put_compact_array_len(buf, None);
                    } else {
                        wire::put_array_len(buf, None)?;
                    }
                }
            }
        }
        if is_flexible(version) {
            wire::put_tagged_fields(buf, &self.unknown_tagged_fields);
        }
        Ok(())
    }

    /// Decode one `OffsetFetchRequestGroup`, bounding allocation by the default
    /// [`Limits`] derived from `buf`'s remaining length.
    pub fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        Self::decode_with_limits(buf, version, Limits::default())
    }

    /// Decode one `OffsetFetchRequestGroup` under `limits`.
    pub fn decode_with_limits(
        buf: &mut impl Buf,
        version: i16,
        limits: Limits,
    ) -> Result<Self, DecodeError> {
        let mut budget = limits.budget(buf.remaining());
        Self::decode_with_budget(buf, version, &mut budget)
    }

    /// Decode one `OffsetFetchRequestGroup` against an existing `budget`.
    pub fn decode_with_budget(
        buf: &mut impl Buf,
        version: i16,
        budget: &mut Budget,
    ) -> Result<Self, DecodeError> {
        let mut this = Self::default();
        if version >= 8 {
            this.group_id = if is_flexible(version) {
                wire::get_compact_string(buf)?
            } else {
                wire::get_string(buf)?
            };
        }
        if version >= 9 {
            this.member_id = if is_flexible(version) {
                wire::get_compact_nullable_string(buf)?
            } else {
                wire::get_nullable_string(buf)?
            };
        }
        if version >= 9 {
            this.member_epoch = wire::get_i32(buf)?;
        }
        if version >= 8 {
            this.topics = {
                let len = if is_flexible(version) {
                    wire::get_compact_array_len(buf)?
                } else {
                    wire::get_array_len(buf)?
                };
                match len {
                    None => None,
                    Some(n) => {
                        let mut items = Vec::new();
                        for _ in 0..n {
                            let mark = buf.remaining();
                            let item =
                                OffsetFetchRequestTopics::decode_with_budget(buf, version, budget)?;
                            budget.progress(mark, buf.remaining())?;
                            budget.push(&mut items, item)?;
                        }
                        Some(items)
                    }
                }
            };
        }
        if is_flexible(version) {
            this.unknown_tagged_fields = wire::get_tagged_fields_with_budget(buf, budget)?;
        }
        Ok(this)
    }
}

/// `OffsetFetchRequestTopics` (nested in [`OffsetFetchRequest`]).
#[derive(Debug, Clone, PartialEq)]
#[non_exhaustive]
pub struct OffsetFetchRequestTopics {
    /// The topic name.
    pub name: String,
    /// The topic ID.
    pub topic_id: [u8; 16],
    /// The partition indexes we would like to fetch offsets for.
    pub partition_indexes: Vec<i32>,
    /// Tagged fields not (yet) known to this crate, kept raw.
    pub unknown_tagged_fields: Vec<RawTaggedField>,
}

impl Default for OffsetFetchRequestTopics {
    fn default() -> Self {
        Self {
            name: String::new(),
            topic_id: [0u8; 16],
            partition_indexes: Vec::new(),
            unknown_tagged_fields: Vec::new(),
        }
    }
}

impl OffsetFetchRequestTopics {
    pub fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        if (8..=9).contains(&version) {
            if is_flexible(version) {
                wire::put_compact_string(buf, &self.name);
            } else {
                wire::put_string(buf, &self.name)?;
            }
        }
        if version >= 10 {
            wire::put_uuid(buf, self.topic_id);
        }
        if version >= 8 {
            if is_flexible(version) {
                wire::put_compact_array_len(buf, Some(self.partition_indexes.len()));
            } else {
                wire::put_array_len(buf, Some(self.partition_indexes.len()))?;
            }
            for item in &self.partition_indexes {
                buf.put_i32(*item);
            }
        }
        if is_flexible(version) {
            wire::put_tagged_fields(buf, &self.unknown_tagged_fields);
        }
        Ok(())
    }

    /// Decode one `OffsetFetchRequestTopics`, bounding allocation by the default
    /// [`Limits`] derived from `buf`'s remaining length.
    pub fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        Self::decode_with_limits(buf, version, Limits::default())
    }

    /// Decode one `OffsetFetchRequestTopics` under `limits`.
    pub fn decode_with_limits(
        buf: &mut impl Buf,
        version: i16,
        limits: Limits,
    ) -> Result<Self, DecodeError> {
        let mut budget = limits.budget(buf.remaining());
        Self::decode_with_budget(buf, version, &mut budget)
    }

    /// Decode one `OffsetFetchRequestTopics` against an existing `budget`.
    pub fn decode_with_budget(
        buf: &mut impl Buf,
        version: i16,
        budget: &mut Budget,
    ) -> Result<Self, DecodeError> {
        let mut this = Self::default();
        if (8..=9).contains(&version) {
            this.name = if is_flexible(version) {
                wire::get_compact_string(buf)?
            } else {
                wire::get_string(buf)?
            };
        }
        if version >= 10 {
            this.topic_id = wire::get_uuid(buf)?;
        }
        if version >= 8 {
            this.partition_indexes = {
                let len = if is_flexible(version) {
                    wire::get_compact_array_len(buf)?
                } else {
                    wire::get_array_len(buf)?
                };
                match len {
                    None => return Err(DecodeError::InvalidLength(-1)),
                    Some(n) => {
                        let mut items = Vec::new();
                        for _ in 0..n {
                            budget.push(&mut items, wire::get_i32(buf)?)?;
                        }
                        items
                    }
                }
            };
        }
        if is_flexible(version) {
            this.unknown_tagged_fields = wire::get_tagged_fields_with_budget(buf, budget)?;
        }
        Ok(this)
    }
}
