//! `ProduceResponse` — generated from `schemas/ProduceResponse.json`.
//!
//! @generated by `cargo xtask codegen`. Do not edit by hand.
//!
//! Tagged fields are materialized as `Option` struct fields (`None` = absent
//! on the wire); unknown tags still round-trip through `unknown_tagged_fields`.

#![allow(
    clippy::field_reassign_with_default,
    clippy::nonminimal_bool,
    clippy::derivable_impls,
    clippy::borrow_deref_ref,
    clippy::double_parens,
    unused_parens
)]

use bytes::{Buf, BufMut};

use crate::budget::{Budget, Limits};
#[allow(unused_imports)]
use crate::error::{DecodeError, EncodeError};
use crate::wire::{self, RawTaggedField};

/// Whether `version` of this message uses the flexible (compact) encoding.
pub fn is_flexible(version: i16) -> bool {
    let _ = version;
    version >= 9
}

/// `ProduceResponse`, versions 3-13.
#[derive(Debug, Clone, PartialEq)]
#[non_exhaustive]
pub struct ProduceResponse {
    /// Each produce response.
    pub responses: Vec<TopicProduceResponse>,
    /// The duration in milliseconds for which the request was throttled due to a quota violation, or zero if the request did not violate any quota.
    pub throttle_time_ms: i32,
    /// Endpoints for all current-leaders enumerated in PartitionProduceResponses, with errors NOT_LEADER_OR_FOLLOWER.
    /// (Tagged field 0; `None` = absent on the wire.)
    pub node_endpoints: Option<Vec<NodeEndpoint>>,
    /// Tagged fields not (yet) known to this crate, kept raw.
    pub unknown_tagged_fields: Vec<RawTaggedField>,
}

impl Default for ProduceResponse {
    fn default() -> Self {
        Self {
            responses: Vec::new(),
            throttle_time_ms: 0,
            node_endpoints: None,
            unknown_tagged_fields: Vec::new(),
        }
    }
}

impl ProduceResponse {
    pub const API_KEY: i16 = 0;
    pub const MIN_VERSION: i16 = 3;
    pub const MAX_VERSION: i16 = 13;

    pub fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        if is_flexible(version) {
            wire::put_compact_array_len(buf, Some(self.responses.len()));
        } else {
            wire::put_array_len(buf, Some(self.responses.len()))?;
        }
        for item in &self.responses {
            item.encode(buf, version)?;
        }
        buf.put_i32(self.throttle_time_ms);
        if is_flexible(version) {
            let mut tagged = self.unknown_tagged_fields.clone();
            if version >= 10 {
                if let Some(v) = &self.node_endpoints {
                    let mut tag_data = bytes::BytesMut::new();
                    {
                        let buf = &mut tag_data;
                        if is_flexible(version) {
                            wire::put_compact_array_len(buf, Some((*v).len()));
                        } else {
                            wire::put_array_len(buf, Some((*v).len()))?;
                        }
                        for item in &(*v) {
                            item.encode(buf, version)?;
                        }
                    }
                    tagged.push(RawTaggedField {
                        tag: 0,
                        data: tag_data.freeze(),
                    });
                }
            }
            tagged.sort_by_key(|f| f.tag);
            wire::put_tagged_fields(buf, &tagged);
        }
        Ok(())
    }

    /// Decode one `ProduceResponse`, bounding allocation by the default
    /// [`Limits`] derived from `buf`'s remaining length.
    pub fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        Self::decode_with_limits(buf, version, Limits::default())
    }

    /// Decode one `ProduceResponse` under `limits`.
    pub fn decode_with_limits(
        buf: &mut impl Buf,
        version: i16,
        limits: Limits,
    ) -> Result<Self, DecodeError> {
        let mut budget = limits.budget(buf.remaining());
        Self::decode_with_budget(buf, version, &mut budget)
    }

    /// Decode one `ProduceResponse` against an existing `budget`.
    pub fn decode_with_budget(
        buf: &mut impl Buf,
        version: i16,
        budget: &mut Budget,
    ) -> Result<Self, DecodeError> {
        let mut this = Self::default();
        this.responses = {
            let len = if is_flexible(version) {
                wire::get_compact_array_len(buf)?
            } else {
                wire::get_array_len(buf)?
            };
            match len {
                None => return Err(DecodeError::InvalidLength(-1)),
                Some(n) => {
                    let mut items = Vec::new();
                    for _ in 0..n {
                        let mark = buf.remaining();
                        let item = TopicProduceResponse::decode_with_budget(buf, version, budget)?;
                        budget.progress(mark, buf.remaining())?;
                        budget.push(&mut items, item)?;
                    }
                    items
                }
            }
        };
        this.throttle_time_ms = wire::get_i32(buf)?;
        if is_flexible(version) {
            for raw in wire::get_tagged_fields_with_budget(buf, budget)? {
                if raw.tag == 0 && (version >= 10) {
                    let mut tag_data = raw.data;
                    let buf = &mut tag_data;
                    this.node_endpoints = Some({
                        let len = if is_flexible(version) {
                            wire::get_compact_array_len(buf)?
                        } else {
                            wire::get_array_len(buf)?
                        };
                        match len {
                            None => return Err(DecodeError::InvalidLength(-1)),
                            Some(n) => {
                                let mut items = Vec::new();
                                for _ in 0..n {
                                    let mark = buf.remaining();
                                    let item =
                                        NodeEndpoint::decode_with_budget(buf, version, budget)?;
                                    budget.progress(mark, buf.remaining())?;
                                    budget.push(&mut items, item)?;
                                }
                                items
                            }
                        }
                    });
                    if buf.has_remaining() {
                        return Err(DecodeError::InvalidLength(
                            i64::try_from(buf.remaining()).unwrap_or(i64::MAX),
                        ));
                    }
                } else {
                    budget.push(&mut this.unknown_tagged_fields, raw)?;
                }
            }
        }
        Ok(this)
    }
}

impl crate::Message for ProduceResponse {
    const API_KEY: i16 = 0;
    const MIN_VERSION: i16 = 3;
    const MAX_VERSION: i16 = 13;

    fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        ProduceResponse::encode(self, buf, version)
    }
    fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        ProduceResponse::decode(buf, version)
    }
    fn decode_with_limits(
        buf: &mut impl Buf,
        version: i16,
        limits: Limits,
    ) -> Result<Self, DecodeError> {
        ProduceResponse::decode_with_limits(buf, version, limits)
    }
}

/// `TopicProduceResponse` (nested in [`ProduceResponse`]).
#[derive(Debug, Clone, PartialEq)]
#[non_exhaustive]
pub struct TopicProduceResponse {
    /// The topic name.
    pub name: String,
    /// The unique topic ID
    pub topic_id: [u8; 16],
    /// Each partition that we produced to within the topic.
    pub partition_responses: Vec<PartitionProduceResponse>,
    /// Tagged fields not (yet) known to this crate, kept raw.
    pub unknown_tagged_fields: Vec<RawTaggedField>,
}

impl Default for TopicProduceResponse {
    fn default() -> Self {
        Self {
            name: String::new(),
            topic_id: [0u8; 16],
            partition_responses: Vec::new(),
            unknown_tagged_fields: Vec::new(),
        }
    }
}

impl TopicProduceResponse {
    pub fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        if version <= 12 {
            if is_flexible(version) {
                wire::put_compact_string(buf, &self.name);
            } else {
                wire::put_string(buf, &self.name)?;
            }
        }
        if version >= 13 {
            wire::put_uuid(buf, self.topic_id);
        }
        if is_flexible(version) {
            wire::put_compact_array_len(buf, Some(self.partition_responses.len()));
        } else {
            wire::put_array_len(buf, Some(self.partition_responses.len()))?;
        }
        for item in &self.partition_responses {
            item.encode(buf, version)?;
        }
        if is_flexible(version) {
            wire::put_tagged_fields(buf, &self.unknown_tagged_fields);
        }
        Ok(())
    }

    /// Decode one `TopicProduceResponse`, bounding allocation by the default
    /// [`Limits`] derived from `buf`'s remaining length.
    pub fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        Self::decode_with_limits(buf, version, Limits::default())
    }

    /// Decode one `TopicProduceResponse` under `limits`.
    pub fn decode_with_limits(
        buf: &mut impl Buf,
        version: i16,
        limits: Limits,
    ) -> Result<Self, DecodeError> {
        let mut budget = limits.budget(buf.remaining());
        Self::decode_with_budget(buf, version, &mut budget)
    }

    /// Decode one `TopicProduceResponse` against an existing `budget`.
    pub fn decode_with_budget(
        buf: &mut impl Buf,
        version: i16,
        budget: &mut Budget,
    ) -> Result<Self, DecodeError> {
        let mut this = Self::default();
        if version <= 12 {
            this.name = if is_flexible(version) {
                wire::get_compact_string(buf)?
            } else {
                wire::get_string(buf)?
            };
        }
        if version >= 13 {
            this.topic_id = wire::get_uuid(buf)?;
        }
        this.partition_responses = {
            let len = if is_flexible(version) {
                wire::get_compact_array_len(buf)?
            } else {
                wire::get_array_len(buf)?
            };
            match len {
                None => return Err(DecodeError::InvalidLength(-1)),
                Some(n) => {
                    let mut items = Vec::new();
                    for _ in 0..n {
                        let mark = buf.remaining();
                        let item =
                            PartitionProduceResponse::decode_with_budget(buf, version, budget)?;
                        budget.progress(mark, buf.remaining())?;
                        budget.push(&mut items, item)?;
                    }
                    items
                }
            }
        };
        if is_flexible(version) {
            this.unknown_tagged_fields = wire::get_tagged_fields_with_budget(buf, budget)?;
        }
        Ok(this)
    }
}

/// `PartitionProduceResponse` (nested in [`ProduceResponse`]).
#[derive(Debug, Clone, PartialEq)]
#[non_exhaustive]
pub struct PartitionProduceResponse {
    /// The partition index.
    pub index: i32,
    /// The error code, or 0 if there was no error.
    pub error_code: i16,
    /// The base offset.
    pub base_offset: i64,
    /// The timestamp returned by broker after appending the messages. If CreateTime is used for the topic, the timestamp will be -1.  If LogAppendTime is used for the topic, the timestamp will be the broker local time when the messages are appended.
    pub log_append_time_ms: i64,
    /// The log start offset.
    pub log_start_offset: i64,
    /// The batch indices of records that caused the batch to be dropped.
    pub record_errors: Vec<BatchIndexAndErrorMessage>,
    /// The global error message summarizing the common root cause of the records that caused the batch to be dropped.
    pub error_message: Option<String>,
    /// The leader broker that the producer should use for future requests.
    /// (Tagged field 0; `None` = absent on the wire.)
    pub current_leader: Option<LeaderIdAndEpoch>,
    /// Tagged fields not (yet) known to this crate, kept raw.
    pub unknown_tagged_fields: Vec<RawTaggedField>,
}

impl Default for PartitionProduceResponse {
    fn default() -> Self {
        Self {
            index: 0,
            error_code: 0,
            base_offset: 0,
            log_append_time_ms: -1,
            log_start_offset: -1,
            record_errors: Vec::new(),
            error_message: None,
            current_leader: None,
            unknown_tagged_fields: Vec::new(),
        }
    }
}

impl PartitionProduceResponse {
    pub fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        buf.put_i32(self.index);
        buf.put_i16(self.error_code);
        buf.put_i64(self.base_offset);
        buf.put_i64(self.log_append_time_ms);
        if version >= 5 {
            buf.put_i64(self.log_start_offset);
        }
        if version >= 8 {
            if is_flexible(version) {
                wire::put_compact_array_len(buf, Some(self.record_errors.len()));
            } else {
                wire::put_array_len(buf, Some(self.record_errors.len()))?;
            }
            for item in &self.record_errors {
                item.encode(buf, version)?;
            }
        }
        if version >= 8 {
            if is_flexible(version) {
                wire::put_compact_nullable_string(buf, self.error_message.as_deref());
            } else {
                wire::put_nullable_string(buf, self.error_message.as_deref())?;
            }
        }
        if is_flexible(version) {
            let mut tagged = self.unknown_tagged_fields.clone();
            if version >= 10 {
                if let Some(v) = &self.current_leader {
                    let mut tag_data = bytes::BytesMut::new();
                    {
                        let buf = &mut tag_data;
                        (*v).encode(buf, version)?;
                    }
                    tagged.push(RawTaggedField {
                        tag: 0,
                        data: tag_data.freeze(),
                    });
                }
            }
            tagged.sort_by_key(|f| f.tag);
            wire::put_tagged_fields(buf, &tagged);
        }
        Ok(())
    }

    /// Decode one `PartitionProduceResponse`, bounding allocation by the default
    /// [`Limits`] derived from `buf`'s remaining length.
    pub fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        Self::decode_with_limits(buf, version, Limits::default())
    }

    /// Decode one `PartitionProduceResponse` under `limits`.
    pub fn decode_with_limits(
        buf: &mut impl Buf,
        version: i16,
        limits: Limits,
    ) -> Result<Self, DecodeError> {
        let mut budget = limits.budget(buf.remaining());
        Self::decode_with_budget(buf, version, &mut budget)
    }

    /// Decode one `PartitionProduceResponse` against an existing `budget`.
    pub fn decode_with_budget(
        buf: &mut impl Buf,
        version: i16,
        budget: &mut Budget,
    ) -> Result<Self, DecodeError> {
        let mut this = Self::default();
        this.index = wire::get_i32(buf)?;
        this.error_code = wire::get_i16(buf)?;
        this.base_offset = wire::get_i64(buf)?;
        this.log_append_time_ms = wire::get_i64(buf)?;
        if version >= 5 {
            this.log_start_offset = wire::get_i64(buf)?;
        }
        if version >= 8 {
            this.record_errors = {
                let len = if is_flexible(version) {
                    wire::get_compact_array_len(buf)?
                } else {
                    wire::get_array_len(buf)?
                };
                match len {
                    None => return Err(DecodeError::InvalidLength(-1)),
                    Some(n) => {
                        let mut items = Vec::new();
                        for _ in 0..n {
                            let mark = buf.remaining();
                            let item = BatchIndexAndErrorMessage::decode_with_budget(
                                buf, version, budget,
                            )?;
                            budget.progress(mark, buf.remaining())?;
                            budget.push(&mut items, item)?;
                        }
                        items
                    }
                }
            };
        }
        if version >= 8 {
            this.error_message = if is_flexible(version) {
                wire::get_compact_nullable_string(buf)?
            } else {
                wire::get_nullable_string(buf)?
            };
        }
        if is_flexible(version) {
            for raw in wire::get_tagged_fields_with_budget(buf, budget)? {
                if raw.tag == 0 && (version >= 10) {
                    let mut tag_data = raw.data;
                    let buf = &mut tag_data;
                    this.current_leader =
                        Some(LeaderIdAndEpoch::decode_with_budget(buf, version, budget)?);
                    if buf.has_remaining() {
                        return Err(DecodeError::InvalidLength(
                            i64::try_from(buf.remaining()).unwrap_or(i64::MAX),
                        ));
                    }
                } else {
                    budget.push(&mut this.unknown_tagged_fields, raw)?;
                }
            }
        }
        Ok(this)
    }
}

/// `BatchIndexAndErrorMessage` (nested in [`ProduceResponse`]).
#[derive(Debug, Clone, PartialEq)]
#[non_exhaustive]
pub struct BatchIndexAndErrorMessage {
    /// The batch index of the record that caused the batch to be dropped.
    pub batch_index: i32,
    /// The error message of the record that caused the batch to be dropped.
    pub batch_index_error_message: Option<String>,
    /// Tagged fields not (yet) known to this crate, kept raw.
    pub unknown_tagged_fields: Vec<RawTaggedField>,
}

impl Default for BatchIndexAndErrorMessage {
    fn default() -> Self {
        Self {
            batch_index: 0,
            batch_index_error_message: None,
            unknown_tagged_fields: Vec::new(),
        }
    }
}

impl BatchIndexAndErrorMessage {
    pub fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        if version >= 8 {
            buf.put_i32(self.batch_index);
        }
        if version >= 8 {
            if is_flexible(version) {
                wire::put_compact_nullable_string(buf, self.batch_index_error_message.as_deref());
            } else {
                wire::put_nullable_string(buf, self.batch_index_error_message.as_deref())?;
            }
        }
        if is_flexible(version) {
            wire::put_tagged_fields(buf, &self.unknown_tagged_fields);
        }
        Ok(())
    }

    /// Decode one `BatchIndexAndErrorMessage`, bounding allocation by the default
    /// [`Limits`] derived from `buf`'s remaining length.
    pub fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        Self::decode_with_limits(buf, version, Limits::default())
    }

    /// Decode one `BatchIndexAndErrorMessage` under `limits`.
    pub fn decode_with_limits(
        buf: &mut impl Buf,
        version: i16,
        limits: Limits,
    ) -> Result<Self, DecodeError> {
        let mut budget = limits.budget(buf.remaining());
        Self::decode_with_budget(buf, version, &mut budget)
    }

    /// Decode one `BatchIndexAndErrorMessage` against an existing `budget`.
    pub fn decode_with_budget(
        buf: &mut impl Buf,
        version: i16,
        budget: &mut Budget,
    ) -> Result<Self, DecodeError> {
        let mut this = Self::default();
        if version >= 8 {
            this.batch_index = wire::get_i32(buf)?;
        }
        if version >= 8 {
            this.batch_index_error_message = if is_flexible(version) {
                wire::get_compact_nullable_string(buf)?
            } else {
                wire::get_nullable_string(buf)?
            };
        }
        if is_flexible(version) {
            this.unknown_tagged_fields = wire::get_tagged_fields_with_budget(buf, budget)?;
        }
        Ok(this)
    }
}

/// `LeaderIdAndEpoch` (nested in [`ProduceResponse`]).
#[derive(Debug, Clone, PartialEq)]
#[non_exhaustive]
pub struct LeaderIdAndEpoch {
    /// The ID of the current leader or -1 if the leader is unknown.
    pub leader_id: i32,
    /// The latest known leader epoch.
    pub leader_epoch: i32,
    /// Tagged fields not (yet) known to this crate, kept raw.
    pub unknown_tagged_fields: Vec<RawTaggedField>,
}

impl Default for LeaderIdAndEpoch {
    fn default() -> Self {
        Self {
            leader_id: -1,
            leader_epoch: -1,
            unknown_tagged_fields: Vec::new(),
        }
    }
}

impl LeaderIdAndEpoch {
    pub fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        if version >= 10 {
            buf.put_i32(self.leader_id);
        }
        if version >= 10 {
            buf.put_i32(self.leader_epoch);
        }
        if is_flexible(version) {
            wire::put_tagged_fields(buf, &self.unknown_tagged_fields);
        }
        Ok(())
    }

    /// Decode one `LeaderIdAndEpoch`, bounding allocation by the default
    /// [`Limits`] derived from `buf`'s remaining length.
    pub fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        Self::decode_with_limits(buf, version, Limits::default())
    }

    /// Decode one `LeaderIdAndEpoch` under `limits`.
    pub fn decode_with_limits(
        buf: &mut impl Buf,
        version: i16,
        limits: Limits,
    ) -> Result<Self, DecodeError> {
        let mut budget = limits.budget(buf.remaining());
        Self::decode_with_budget(buf, version, &mut budget)
    }

    /// Decode one `LeaderIdAndEpoch` against an existing `budget`.
    pub fn decode_with_budget(
        buf: &mut impl Buf,
        version: i16,
        budget: &mut Budget,
    ) -> Result<Self, DecodeError> {
        let mut this = Self::default();
        if version >= 10 {
            this.leader_id = wire::get_i32(buf)?;
        }
        if version >= 10 {
            this.leader_epoch = wire::get_i32(buf)?;
        }
        if is_flexible(version) {
            this.unknown_tagged_fields = wire::get_tagged_fields_with_budget(buf, budget)?;
        }
        Ok(this)
    }
}

/// `NodeEndpoint` (nested in [`ProduceResponse`]).
#[derive(Debug, Clone, PartialEq)]
#[non_exhaustive]
pub struct NodeEndpoint {
    /// The ID of the associated node.
    pub node_id: i32,
    /// The node's hostname.
    pub host: String,
    /// The node's port.
    pub port: i32,
    /// The rack of the node, or null if it has not been assigned to a rack.
    pub rack: Option<String>,
    /// Tagged fields not (yet) known to this crate, kept raw.
    pub unknown_tagged_fields: Vec<RawTaggedField>,
}

impl Default for NodeEndpoint {
    fn default() -> Self {
        Self {
            node_id: 0,
            host: String::new(),
            port: 0,
            rack: None,
            unknown_tagged_fields: Vec::new(),
        }
    }
}

impl NodeEndpoint {
    pub fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        if version >= 10 {
            buf.put_i32(self.node_id);
        }
        if version >= 10 {
            if is_flexible(version) {
                wire::put_compact_string(buf, &self.host);
            } else {
                wire::put_string(buf, &self.host)?;
            }
        }
        if version >= 10 {
            buf.put_i32(self.port);
        }
        if version >= 10 {
            if is_flexible(version) {
                wire::put_compact_nullable_string(buf, self.rack.as_deref());
            } else {
                wire::put_nullable_string(buf, self.rack.as_deref())?;
            }
        }
        if is_flexible(version) {
            wire::put_tagged_fields(buf, &self.unknown_tagged_fields);
        }
        Ok(())
    }

    /// Decode one `NodeEndpoint`, bounding allocation by the default
    /// [`Limits`] derived from `buf`'s remaining length.
    pub fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        Self::decode_with_limits(buf, version, Limits::default())
    }

    /// Decode one `NodeEndpoint` under `limits`.
    pub fn decode_with_limits(
        buf: &mut impl Buf,
        version: i16,
        limits: Limits,
    ) -> Result<Self, DecodeError> {
        let mut budget = limits.budget(buf.remaining());
        Self::decode_with_budget(buf, version, &mut budget)
    }

    /// Decode one `NodeEndpoint` against an existing `budget`.
    pub fn decode_with_budget(
        buf: &mut impl Buf,
        version: i16,
        budget: &mut Budget,
    ) -> Result<Self, DecodeError> {
        let mut this = Self::default();
        if version >= 10 {
            this.node_id = wire::get_i32(buf)?;
        }
        if version >= 10 {
            this.host = if is_flexible(version) {
                wire::get_compact_string(buf)?
            } else {
                wire::get_string(buf)?
            };
        }
        if version >= 10 {
            this.port = wire::get_i32(buf)?;
        }
        if version >= 10 {
            this.rack = if is_flexible(version) {
                wire::get_compact_nullable_string(buf)?
            } else {
                wire::get_nullable_string(buf)?
            };
        }
        if is_flexible(version) {
            this.unknown_tagged_fields = wire::get_tagged_fields_with_budget(buf, budget)?;
        }
        Ok(this)
    }
}
