//! `ResponseHeader` — generated from `schemas/ResponseHeader.json`.
//!
//! @generated by `cargo xtask codegen`. Do not edit by hand.

#![allow(
    clippy::field_reassign_with_default,
    clippy::nonminimal_bool,
    clippy::derivable_impls,
    clippy::borrow_deref_ref,
    clippy::double_parens,
    unused_parens
)]

use bytes::{Buf, BufMut};

#[allow(unused_imports)]
use crate::error::{DecodeError, EncodeError};
use crate::wire::{self, RawTaggedField};

/// Whether `version` of this message uses the flexible (compact) encoding.
pub fn is_flexible(version: i16) -> bool {
    let _ = version;
    version >= 1
}

/// `ResponseHeader`, versions 0-1.
#[derive(Debug, Clone, PartialEq)]
#[non_exhaustive]
pub struct ResponseHeader {
    /// The correlation ID of this response.
    pub correlation_id: i32,
    /// Tagged fields not (yet) known to this crate, kept raw.
    pub unknown_tagged_fields: Vec<RawTaggedField>,
}

impl Default for ResponseHeader {
    fn default() -> Self {
        Self {
            correlation_id: 0,
            unknown_tagged_fields: Vec::new(),
        }
    }
}

impl ResponseHeader {
    pub const MIN_VERSION: i16 = 0;
    pub const MAX_VERSION: i16 = 1;

    pub fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        buf.put_i32(self.correlation_id);
        if is_flexible(version) {
            wire::put_tagged_fields(buf, &self.unknown_tagged_fields);
        }
        Ok(())
    }

    pub fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        let mut this = Self::default();
        this.correlation_id = wire::get_i32(buf)?;
        if is_flexible(version) {
            this.unknown_tagged_fields = wire::get_tagged_fields(buf)?;
        }
        Ok(this)
    }
}
