//! `SaslHandshakeRequest` — generated from `schemas/SaslHandshakeRequest.json`.
//!
//! @generated by `cargo xtask codegen`. Do not edit by hand.

#![allow(
    clippy::field_reassign_with_default,
    clippy::nonminimal_bool,
    clippy::derivable_impls,
    clippy::borrow_deref_ref,
    clippy::double_parens,
    unused_parens
)]

use bytes::{Buf, BufMut};

#[allow(unused_imports)]
use crate::error::{DecodeError, EncodeError};
use crate::wire::{self, RawTaggedField};

/// Whether `version` of this message uses the flexible (compact) encoding.
pub fn is_flexible(version: i16) -> bool {
    let _ = version;
    false
}

/// `SaslHandshakeRequest`, versions 0-1.
#[derive(Debug, Clone, PartialEq)]
#[non_exhaustive]
pub struct SaslHandshakeRequest {
    /// The SASL mechanism chosen by the client.
    pub mechanism: String,
    /// Tagged fields not (yet) known to this crate, kept raw.
    pub unknown_tagged_fields: Vec<RawTaggedField>,
}

impl Default for SaslHandshakeRequest {
    fn default() -> Self {
        Self {
            mechanism: String::new(),
            unknown_tagged_fields: Vec::new(),
        }
    }
}

impl SaslHandshakeRequest {
    pub const API_KEY: i16 = 17;
    pub const MIN_VERSION: i16 = 0;
    pub const MAX_VERSION: i16 = 1;

    pub fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        if is_flexible(version) {
            wire::put_compact_string(buf, &self.mechanism);
        } else {
            wire::put_string(buf, &self.mechanism)?;
        }
        if is_flexible(version) {
            wire::put_tagged_fields(buf, &self.unknown_tagged_fields);
        }
        Ok(())
    }

    pub fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        let mut this = Self::default();
        this.mechanism = if is_flexible(version) {
            wire::get_compact_string(buf)?
        } else {
            wire::get_string(buf)?
        };
        if is_flexible(version) {
            this.unknown_tagged_fields = wire::get_tagged_fields(buf)?;
        }
        Ok(this)
    }
}
