//! `SaslHandshakeResponse` — generated from `schemas/SaslHandshakeResponse.json`.
//!
//! @generated by `cargo xtask codegen`. Do not edit by hand.

#![allow(
    clippy::field_reassign_with_default,
    clippy::nonminimal_bool,
    clippy::derivable_impls,
    clippy::borrow_deref_ref,
    clippy::double_parens,
    unused_parens
)]

use bytes::{Buf, BufMut};

use crate::budget::{Budget, Limits};
#[allow(unused_imports)]
use crate::error::{DecodeError, EncodeError};
use crate::wire::{self, RawTaggedField};

/// Whether `version` of this message uses the flexible (compact) encoding.
pub fn is_flexible(version: i16) -> bool {
    let _ = version;
    false
}

/// `SaslHandshakeResponse`, versions 0-1.
#[derive(Debug, Clone, PartialEq)]
#[non_exhaustive]
pub struct SaslHandshakeResponse {
    /// The error code, or 0 if there was no error.
    pub error_code: i16,
    /// The mechanisms enabled in the server.
    pub mechanisms: Vec<String>,
    /// Tagged fields not (yet) known to this crate, kept raw.
    pub unknown_tagged_fields: Vec<RawTaggedField>,
}

impl Default for SaslHandshakeResponse {
    fn default() -> Self {
        Self {
            error_code: 0,
            mechanisms: Vec::new(),
            unknown_tagged_fields: Vec::new(),
        }
    }
}

impl SaslHandshakeResponse {
    pub const API_KEY: i16 = 17;
    pub const MIN_VERSION: i16 = 0;
    pub const MAX_VERSION: i16 = 1;

    pub fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        buf.put_i16(self.error_code);
        if is_flexible(version) {
            wire::put_compact_array_len(buf, Some(self.mechanisms.len()));
        } else {
            wire::put_array_len(buf, Some(self.mechanisms.len()))?;
        }
        for item in &self.mechanisms {
            if is_flexible(version) {
                wire::put_compact_string(buf, item);
            } else {
                wire::put_string(buf, item)?;
            }
        }
        if is_flexible(version) {
            wire::put_tagged_fields(buf, &self.unknown_tagged_fields);
        }
        Ok(())
    }

    /// Decode one `SaslHandshakeResponse`, bounding allocation by the default
    /// [`Limits`] derived from `buf`'s remaining length.
    pub fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        Self::decode_with_limits(buf, version, Limits::default())
    }

    /// Decode one `SaslHandshakeResponse` under `limits`.
    pub fn decode_with_limits(
        buf: &mut impl Buf,
        version: i16,
        limits: Limits,
    ) -> Result<Self, DecodeError> {
        let mut budget = limits.budget(buf.remaining());
        Self::decode_with_budget(buf, version, &mut budget)
    }

    /// Decode one `SaslHandshakeResponse` against an existing `budget`.
    pub fn decode_with_budget(
        buf: &mut impl Buf,
        version: i16,
        budget: &mut Budget,
    ) -> Result<Self, DecodeError> {
        let mut this = Self::default();
        this.error_code = wire::get_i16(buf)?;
        this.mechanisms = {
            let len = if is_flexible(version) {
                wire::get_compact_array_len(buf)?
            } else {
                wire::get_array_len(buf)?
            };
            match len {
                None => return Err(DecodeError::InvalidLength(-1)),
                Some(n) => {
                    let mut items = Vec::new();
                    for _ in 0..n {
                        budget.push(
                            &mut items,
                            if is_flexible(version) {
                                wire::get_compact_string(buf)?
                            } else {
                                wire::get_string(buf)?
                            },
                        )?;
                    }
                    items
                }
            }
        };
        if is_flexible(version) {
            this.unknown_tagged_fields = wire::get_tagged_fields_with_budget(buf, budget)?;
        }
        Ok(this)
    }
}

impl crate::Message for SaslHandshakeResponse {
    const API_KEY: i16 = 17;
    const MIN_VERSION: i16 = 0;
    const MAX_VERSION: i16 = 1;

    fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        SaslHandshakeResponse::encode(self, buf, version)
    }
    fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        SaslHandshakeResponse::decode(buf, version)
    }
    fn decode_with_limits(
        buf: &mut impl Buf,
        version: i16,
        limits: Limits,
    ) -> Result<Self, DecodeError> {
        SaslHandshakeResponse::decode_with_limits(buf, version, limits)
    }
}
