//! `SaslAuthenticateResponse` — generated from `schemas/SaslAuthenticateResponse.json`.
//!
//! @generated by `cargo xtask codegen`. Do not edit by hand.

#![allow(
    clippy::field_reassign_with_default,
    clippy::nonminimal_bool,
    clippy::derivable_impls,
    clippy::borrow_deref_ref,
    clippy::double_parens,
    unused_parens
)]

use bytes::{Buf, BufMut};

#[allow(unused_imports)]
use crate::error::{DecodeError, EncodeError};
use crate::wire::{self, RawTaggedField};

/// Whether `version` of this message uses the flexible (compact) encoding.
pub fn is_flexible(version: i16) -> bool {
    let _ = version;
    version >= 2
}

/// `SaslAuthenticateResponse`, versions 0-2.
#[derive(Debug, Clone, PartialEq)]
pub struct SaslAuthenticateResponse {
    /// The error code, or 0 if there was no error.
    pub error_code: i16,
    /// The error message, or null if there was no error.
    pub error_message: Option<String>,
    /// The SASL authentication bytes from the server, as defined by the SASL mechanism.
    pub auth_bytes: bytes::Bytes,
    /// Number of milliseconds after which only re-authentication over the existing connection to create a new session can occur.
    pub session_lifetime_ms: i64,
    /// Tagged fields not (yet) known to this crate, kept raw.
    pub unknown_tagged_fields: Vec<RawTaggedField>,
}

impl Default for SaslAuthenticateResponse {
    fn default() -> Self {
        Self {
            error_code: 0,
            error_message: Some(String::new()),
            auth_bytes: bytes::Bytes::new(),
            session_lifetime_ms: 0,
            unknown_tagged_fields: Vec::new(),
        }
    }
}

impl SaslAuthenticateResponse {
    pub const API_KEY: i16 = 36;
    pub const MIN_VERSION: i16 = 0;
    pub const MAX_VERSION: i16 = 2;

    pub fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {
        buf.put_i16(self.error_code);
        if is_flexible(version) {
            wire::put_compact_nullable_string(buf, self.error_message.as_deref());
        } else {
            wire::put_nullable_string(buf, self.error_message.as_deref())?;
        }
        if is_flexible(version) {
            wire::put_compact_bytes(buf, &self.auth_bytes);
        } else {
            wire::put_bytes(buf, &self.auth_bytes)?;
        }
        if version >= 1 {
            buf.put_i64(self.session_lifetime_ms);
        }
        if is_flexible(version) {
            wire::put_tagged_fields(buf, &self.unknown_tagged_fields);
        }
        Ok(())
    }

    pub fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {
        let mut this = Self::default();
        this.error_code = wire::get_i16(buf)?;
        this.error_message = if is_flexible(version) {
            wire::get_compact_nullable_string(buf)?
        } else {
            wire::get_nullable_string(buf)?
        };
        this.auth_bytes = {
            let raw = if is_flexible(version) {
                wire::get_compact_nullable_bytes(buf)?
            } else {
                wire::get_nullable_bytes(buf)?
            };
            match raw {
                Some(v) => v,
                None => return Err(DecodeError::InvalidLength(-1)),
            }
        };
        if version >= 1 {
            this.session_lifetime_ms = wire::get_i64(buf)?;
        }
        if is_flexible(version) {
            this.unknown_tagged_fields = wire::get_tagged_fields(buf)?;
        }
        Ok(this)
    }
}
