[package]
name = "odradek-client"
description = "Async, Rust-native Kafka client built on odradek-protocol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
odradek-protocol = { workspace = true }
base64 = { workspace = true }
bytes = { workspace = true }
flate2 = { workspace = true }
getrandom = { workspace = true }
hmac = { workspace = true }
lz4_flex = { workspace = true }
pbkdf2 = { workspace = true }
rustls-pemfile = { workspace = true }
sha2 = { workspace = true }
snap = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-rustls = { workspace = true }
tracing = { workspace = true }
webpki-roots = { workspace = true }
zstd = { workspace = true }

[lints]
workspace = true
