//! Workspace automation.
//!
//! `cargo xtask codegen` regenerates `odradek-protocol/src/messages/` from
//! the Kafka message schemas vendored in `odradek-protocol/schemas/`.
//! Output is rustfmt-formatted (so it matches what the repo commits) and
//! written only where it differs, leaving a no-op run with nothing to
//! rebuild.
//!
//! `cargo xtask conformance` runs the acceptance suite against real broker
//! implementations in Docker; see `conformance.rs`.
//!
//! Tagged fields are materialized as `Option` struct fields (`None` =
//! absent on the wire); unknown tags round-trip raw. One shape is not
//! supported (the generator fails loudly on it): fields that are
//! wire-encoded in some versions and tagged in others.
//!
//! Every emitted array loop grows its vector against a shared
//! `budget::Budget` and refuses an element that consumed no input. The
//! bound belongs here rather than in each of the ~36 modules: a wire
//! count is attacker-controlled everywhere it appears, and a hand-added
//! `Vec::with_capacity(n)` in one generated file would undo it.

use std::fmt::Write as _;
use std::fs;
use std::io::Write as _;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

use anyhow::{Context, Result, bail};
use serde_json::Value;

mod conformance;

fn main() -> Result<()> {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let task = args.first().map(String::as_str).unwrap_or_default();
    match task {
        "codegen" => codegen(),
        "conformance" => conformance::conformance(&args[1..]),
        other => bail!("unknown task {other:?}; available tasks: codegen, conformance"),
    }
}

fn workspace_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .to_path_buf()
}

fn codegen() -> Result<()> {
    let root = workspace_root();
    let schema_dir = root.join("crates/odradek-protocol/schemas");
    let out_dir = root.join("crates/odradek-protocol/src/messages");
    fs::create_dir_all(&out_dir)?;

    let mut schema_files: Vec<PathBuf> = fs::read_dir(&schema_dir)?
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.extension().is_some_and(|e| e == "json"))
        .collect();
    schema_files.sort();

    let mut messages = Vec::new();
    for path in &schema_files {
        let msg = parse_message(path).with_context(|| format!("parsing {}", path.display()))?;
        messages.push(msg);
    }

    let mut mod_rs = String::new();
    let _ = writeln!(
        mod_rs,
        "//! Kafka message types generated from the vendored schemas.\n\
         //!\n\
         //! @generated by `cargo xtask codegen`. Do not edit by hand; edit the\n\
         //! schemas or the generator and re-run.\n"
    );

    // Generating is cheap and formatting is not, so format the modules in
    // parallel; the result is what gets compared against what is already
    // on disk.
    let mut generated = Vec::new();
    for msg in &messages {
        let module = snake_case(&msg.name);
        let code = generate_message(msg).with_context(|| format!("generating {}", msg.name))?;
        generated.push((module, msg, code));
    }
    let formatted: Vec<String> = std::thread::scope(|scope| {
        let workers: Vec<_> = generated
            .iter()
            .map(|(_, _, code)| scope.spawn(move || rustfmt_or(code)))
            .collect();
        workers
            .into_iter()
            .zip(&generated)
            .map(|(worker, (_, _, code))| worker.join().unwrap_or_else(|_| code.clone()))
            .collect()
    });

    let mut rewritten = 0usize;
    let mut module_names = Vec::new();
    for ((module, msg, _), code) in generated.iter().zip(&formatted) {
        rewritten += usize::from(write_if_changed(
            &out_dir.join(format!("{module}.rs")),
            code,
        )?);
        module_names.push((module.clone(), *msg));
    }

    for (module, _) in &module_names {
        let _ = writeln!(mod_rs, "pub mod {module};");
    }
    let _ = writeln!(mod_rs);
    for (module, msg) in &module_names {
        let _ = writeln!(mod_rs, "pub use {module}::{};", msg.name);
    }

    // Flexibility lookup for requests, used to derive header versions.
    let _ = writeln!(
        mod_rs,
        "\n/// Whether `api_version` of the request identified by `api_key` uses the\n\
         /// flexible (compact) encoding. `None` when the api key has no generated\n\
         /// message type in this crate.\n\
         pub fn request_is_flexible(api_key: i16, api_version: i16) -> Option<bool> {{\n    match api_key {{"
    );
    for (module, msg) in &module_names {
        if msg.typ == "request" {
            let key = msg.api_key.expect("request without apiKey");
            let _ = writeln!(
                mod_rs,
                "        {key} => Some({module}::is_flexible(api_version)),"
            );
        }
    }
    let _ = writeln!(mod_rs, "        _ => None,\n    }}\n}}");

    let _ = writeln!(
        mod_rs,
        "\n/// The version range this schema snapshot speaks for `api_key`'s\n\
         /// request type, or `None` for keys with no generated support.\n\
         pub fn supported_versions(api_key: i16) -> Option<(i16, i16)> {{\n    match api_key {{"
    );
    for (_module, msg) in &module_names {
        if msg.typ == "request" {
            let key = msg.api_key.expect("request without apiKey");
            let _ = writeln!(
                mod_rs,
                "        {key} => Some(({}, {})),",
                msg.valid.min, msg.valid.max
            );
        }
    }
    let _ = writeln!(mod_rs, "        _ => None,\n    }}\n}}");

    rewritten += usize::from(write_if_changed(
        &out_dir.join("mod.rs"),
        &rustfmt_or(&mod_rs),
    )?);
    println!(
        "generated {} message modules in {} ({rewritten} file(s) changed)",
        module_names.len(),
        out_dir.display()
    );
    Ok(())
}

/// Write `contents` only if the file does not already say exactly that.
///
/// Rewriting a byte-identical file still bumps its mtime, and a bumped
/// mtime under `src/messages/` makes cargo rebuild the protocol crate and
/// everything downstream — six seconds of compiling to reach the state it
/// was already in. Returns whether the file changed.
fn write_if_changed(path: &Path, contents: &str) -> Result<bool> {
    if fs::read_to_string(path).is_ok_and(|on_disk| on_disk == contents) {
        return Ok(false);
    }
    fs::write(path, contents).with_context(|| format!("writing {}", path.display()))?;
    Ok(true)
}

/// Format generated code as `cargo fmt` would.
///
/// The generator emits legible-enough but unformatted Rust, while what is
/// committed is formatted — so without this every file would differ from
/// its own last output and [`write_if_changed`] could never skip a write.
/// Returns an empty string if rustfmt is unavailable or unhappy; callers
/// then keep the unformatted source, and `cargo fmt` (which CI runs right
/// after codegen anyway) settles the final shape.
fn rustfmt(code: &str) -> String {
    let Ok(mut child) = Command::new("rustfmt")
        .args(["--edition", "2024", "--emit", "stdout"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::null())
        .spawn()
    else {
        return String::new();
    };
    // rustfmt parses the whole input before emitting anything, so writing
    // it all and then reading cannot deadlock on a full pipe.
    let Some(mut stdin) = child.stdin.take() else {
        return String::new();
    };
    let written = stdin
        .write_all(code.as_bytes())
        .and_then(|()| stdin.flush());
    drop(stdin);
    match (written, child.wait_with_output()) {
        (Ok(()), Ok(out)) if out.status.success() => {
            String::from_utf8(out.stdout).unwrap_or_default()
        }
        _ => String::new(),
    }
}

/// [`rustfmt`], falling back to the unformatted source.
fn rustfmt_or(code: &str) -> String {
    let formatted = rustfmt(code);
    if formatted.is_empty() {
        code.to_owned()
    } else {
        formatted
    }
}

// ---------------------------------------------------------------------------
// Schema model
// ---------------------------------------------------------------------------

/// An inclusive version range. `min > max` encodes the empty range.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct VersionRange {
    min: i16,
    max: i16, // i16::MAX means open-ended
}

impl VersionRange {
    const EMPTY: VersionRange = VersionRange { min: 1, max: 0 };

    fn parse(s: &str) -> Result<VersionRange> {
        let s = s.trim();
        if s == "none" {
            return Ok(VersionRange::EMPTY);
        }
        if let Some(min) = s.strip_suffix('+') {
            return Ok(VersionRange {
                min: min.parse()?,
                max: i16::MAX,
            });
        }
        if let Some((min, max)) = s.split_once('-') {
            return Ok(VersionRange {
                min: min.parse()?,
                max: max.parse()?,
            });
        }
        let v: i16 = s.parse()?;
        Ok(VersionRange { min: v, max: v })
    }

    fn is_empty(self) -> bool {
        self.min > self.max
    }

    /// The versions in both ranges.
    fn intersect(self, other: VersionRange) -> VersionRange {
        VersionRange {
            min: self.min.max(other.min),
            max: self.max.min(other.max),
        }
    }

    /// Rust boolean expression testing membership of `version`, folding to
    /// `true`/`false` where the outcome is constant over `valid`.
    fn expr(self, valid: VersionRange) -> String {
        if self.is_empty() {
            return "false".into();
        }
        let lower = self.min > valid.min; // lower bound can exclude some valid version
        let upper = self.max < valid.max; // upper bound can exclude some valid version
        match (lower, upper) {
            (false, false) => "true".into(),
            (true, false) => format!("version >= {}", self.min),
            (false, true) => format!("version <= {}", self.max),
            (true, true) if self.min == self.max => format!("version == {}", self.min),
            (true, true) => format!("({}..={}).contains(&version)", self.min, self.max),
        }
    }
}

#[derive(Debug, Clone)]
enum FieldType {
    Bool,
    Int8,
    Int16,
    Uint16,
    Int32,
    Uint32,
    Int64,
    Float64,
    Uuid,
    String,
    Bytes,
    Records,
    Struct(String),
    Array(Box<FieldType>),
}

impl FieldType {
    fn parse(s: &str) -> Result<FieldType> {
        if let Some(elem) = s.strip_prefix("[]") {
            return Ok(FieldType::Array(Box::new(FieldType::parse(elem)?)));
        }
        Ok(match s {
            "bool" => FieldType::Bool,
            "int8" => FieldType::Int8,
            "int16" => FieldType::Int16,
            "uint16" => FieldType::Uint16,
            "int32" => FieldType::Int32,
            "uint32" => FieldType::Uint32,
            "int64" => FieldType::Int64,
            "float64" => FieldType::Float64,
            "uuid" => FieldType::Uuid,
            "string" => FieldType::String,
            "bytes" => FieldType::Bytes,
            "records" => FieldType::Records,
            name if name.chars().next().is_some_and(|c| c.is_ascii_uppercase()) => {
                FieldType::Struct(name.to_owned())
            }
            other => bail!("unsupported field type {other:?}"),
        })
    }
}

#[derive(Debug, Clone)]
struct Field {
    name: String,
    ftype: FieldType,
    versions: VersionRange,
    nullable: Option<VersionRange>,
    tag: Option<u64>,
    tagged_versions: Option<VersionRange>,
    default: Option<Value>,
    flexible_override: Option<VersionRange>,
    about: Option<String>,
    inline_fields: Option<Vec<Field>>,
}

#[derive(Debug)]
struct StructDef {
    name: String,
    fields: Vec<Field>,
}

#[derive(Debug)]
struct Message {
    name: String,
    typ: String, // request | response | header | data
    api_key: Option<i16>,
    valid: VersionRange,
    flexible: VersionRange,
    fields: Vec<Field>,
    common_structs: Vec<StructDef>,
    schema_file: String,
}

fn parse_message(path: &Path) -> Result<Message> {
    let raw = fs::read_to_string(path)?;
    let stripped: String = raw
        .lines()
        .filter(|line| !line.trim_start().starts_with("//"))
        .collect::<Vec<_>>()
        .join("\n");
    let json: Value = serde_json::from_str(&stripped)?;

    let name = json["name"].as_str().context("missing name")?.to_owned();
    let typ = json["type"].as_str().context("missing type")?.to_owned();
    let api_key = json["apiKey"].as_i64().map(|k| k as i16);
    let valid = VersionRange::parse(
        json["validVersions"]
            .as_str()
            .context("missing validVersions")?,
    )?;
    let flexible = match json["flexibleVersions"].as_str() {
        Some(s) => VersionRange::parse(s)?,
        None => VersionRange::EMPTY,
    };
    let fields = parse_fields(json["fields"].as_array().context("missing fields")?)?;
    let common_structs = match json["commonStructs"].as_array() {
        Some(defs) => defs
            .iter()
            .map(|d| {
                Ok(StructDef {
                    name: d["name"].as_str().context("commonStruct name")?.to_owned(),
                    fields: parse_fields(d["fields"].as_array().context("commonStruct fields")?)?,
                })
            })
            .collect::<Result<Vec<_>>>()?,
        None => Vec::new(),
    };
    Ok(Message {
        name,
        typ,
        api_key,
        valid,
        flexible,
        fields,
        common_structs,
        schema_file: path.file_name().unwrap().to_string_lossy().into_owned(),
    })
}

fn parse_fields(fields: &[Value]) -> Result<Vec<Field>> {
    fields
        .iter()
        .map(|f| {
            let name = f["name"].as_str().context("field name")?.to_owned();
            let ftype = FieldType::parse(f["type"].as_str().context("field type")?)
                .with_context(|| format!("field {name}"))?;
            let versions = VersionRange::parse(f["versions"].as_str().context("field versions")?)?;
            let nullable = match f["nullableVersions"].as_str() {
                Some(s) => Some(VersionRange::parse(s)?),
                None => None,
            };
            let flexible_override = match f["flexibleVersions"].as_str() {
                Some(s) => Some(VersionRange::parse(s)?),
                None => None,
            };
            let inline_fields = match f["fields"].as_array() {
                Some(inner) => Some(parse_fields(inner)?),
                None => None,
            };
            let tagged_versions = match f["taggedVersions"].as_str() {
                Some(s) => Some(VersionRange::parse(s)?),
                None => None,
            };
            Ok(Field {
                name,
                ftype,
                versions,
                nullable,
                tag: f["tag"].as_u64(),
                tagged_versions,
                default: f.get("default").cloned(),
                flexible_override,
                about: f["about"].as_str().map(str::to_owned),
                inline_fields,
            })
        })
        .collect()
}

// ---------------------------------------------------------------------------
// Code generation
// ---------------------------------------------------------------------------

fn generate_message(msg: &Message) -> Result<String> {
    let mut structs: Vec<StructDef> = vec![StructDef {
        name: msg.name.clone(),
        fields: msg.fields.clone(),
    }];
    collect_inline_structs(&msg.fields, &mut structs);
    for cs in &msg.common_structs {
        if !structs.iter().any(|s| s.name == cs.name) {
            structs.push(StructDef {
                name: cs.name.clone(),
                fields: cs.fields.clone(),
            });
        }
        collect_inline_structs(&cs.fields, &mut structs);
    }

    // The generator only handles the shape every current schema uses: a
    // tagged field is tagged for its entire lifetime. A field that is
    // wire-encoded in some versions and tagged in others needs new
    // codegen support — fail loudly rather than mis-encode.
    let mut has_tagged = false;
    for def in &structs {
        for f in &def.fields {
            if f.tag.is_some() {
                has_tagged = true;
                if f.tagged_versions != Some(f.versions) {
                    bail!(
                        "{}.{}: taggedVersions {:?} != versions {:?}; \
                         partially tagged fields are not supported",
                        def.name,
                        f.name,
                        f.tagged_versions,
                        f.versions
                    );
                }
            }
        }
    }

    let mut out = String::new();
    let w = &mut out;
    let _ = writeln!(
        w,
        "//! `{}` — generated from `schemas/{}`.",
        msg.name, msg.schema_file
    );
    let _ = writeln!(w, "//!");
    let _ = writeln!(
        w,
        "//! @generated by `cargo xtask codegen`. Do not edit by hand."
    );
    if has_tagged {
        let _ = writeln!(w, "//!");
        let _ = writeln!(
            w,
            "//! Tagged fields are materialized as `Option` struct fields \
             (`None` = absent\n//! on the wire); unknown tags still round-trip \
             through `unknown_tagged_fields`."
        );
    }
    let _ = writeln!(w);
    // Style lints that the generated encode/decode shapes trip by design:
    // decode fills a Default-initialized struct, version guards produce
    // negations like `!(version >= 3)`, and tagged-field snippets reuse
    // the by-reference path `(*v)` uniformly across value shapes.
    let _ = writeln!(
        w,
        "#![allow(clippy::field_reassign_with_default, clippy::nonminimal_bool, clippy::derivable_impls, clippy::borrow_deref_ref, clippy::double_parens, unused_parens)]"
    );
    let _ = writeln!(w);
    let _ = writeln!(w, "use bytes::{{Buf, BufMut}};");
    let _ = writeln!(w);
    let _ = writeln!(w, "use crate::budget::{{Budget, Limits}};");
    let _ = writeln!(w, "#[allow(unused_imports)]");
    let _ = writeln!(w, "use crate::error::{{DecodeError, EncodeError}};");
    let _ = writeln!(w, "use crate::wire::{{self, RawTaggedField}};");
    let _ = writeln!(w);
    let _ = writeln!(
        w,
        "/// Whether `version` of this message uses the flexible (compact) encoding."
    );
    let _ = writeln!(w, "pub fn is_flexible(version: i16) -> bool {{");
    let _ = writeln!(w, "    let _ = version;");
    let _ = writeln!(w, "    {}", msg.flexible.expr(msg.valid));
    let _ = writeln!(w, "}}");

    for (i, def) in structs.iter().enumerate() {
        generate_struct(w, msg, def, i == 0)?;
    }
    Ok(out)
}

fn collect_inline_structs(fields: &[Field], out: &mut Vec<StructDef>) {
    for f in fields {
        if let Some(inner) = &f.inline_fields {
            let name = struct_name_of(&f.ftype);
            if let Some(name) = name {
                if !out.iter().any(|s| s.name == name) {
                    out.push(StructDef {
                        name: name.to_owned(),
                        fields: inner.clone(),
                    });
                }
            }
            collect_inline_structs(inner, out);
        }
    }
}

fn struct_name_of(ftype: &FieldType) -> Option<&str> {
    match ftype {
        FieldType::Struct(n) => Some(n),
        FieldType::Array(inner) => struct_name_of(inner),
        _ => None,
    }
}

fn generate_struct(w: &mut String, msg: &Message, def: &StructDef, is_top: bool) -> Result<()> {
    let wire_fields: Vec<&Field> = def.fields.iter().filter(|f| f.tag.is_none()).collect();
    let mut tagged_fields: Vec<&Field> = def.fields.iter().filter(|f| f.tag.is_some()).collect();
    tagged_fields.sort_by_key(|f| f.tag);

    let _ = writeln!(w);
    if is_top {
        let _ = writeln!(w, "/// `{}`, versions {}.", def.name, range_doc(msg.valid));
    } else {
        let _ = writeln!(w, "/// `{}` (nested in [`{}`]).", def.name, msg.name);
    }
    let _ = writeln!(w, "#[derive(Debug, Clone, PartialEq)]");
    let _ = writeln!(w, "#[non_exhaustive]");
    let _ = writeln!(w, "pub struct {} {{", def.name);
    for f in &wire_fields {
        if let Some(about) = &f.about {
            let _ = writeln!(
                w,
                "    /// {}",
                about.replace('[', "\\[").replace(']', "\\]")
            );
        }
        let _ = writeln!(w, "    pub {}: {},", rust_field_name(&f.name), rust_type(f));
    }
    for f in &tagged_fields {
        if let Some(about) = &f.about {
            let _ = writeln!(
                w,
                "    /// {}",
                about.replace('[', "\\[").replace(']', "\\]")
            );
        }
        let _ = writeln!(
            w,
            "    /// (Tagged field {}; `None` = absent on the wire.)",
            f.tag.unwrap()
        );
        let _ = writeln!(
            w,
            "    pub {}: Option<{}>,",
            rust_field_name(&f.name),
            rust_type(f)
        );
    }
    let _ = writeln!(
        w,
        "    /// Tagged fields not (yet) known to this crate, kept raw."
    );
    let _ = writeln!(w, "    pub unknown_tagged_fields: Vec<RawTaggedField>,");
    let _ = writeln!(w, "}}");

    // Default impl using schema defaults.
    let _ = writeln!(w);
    let _ = writeln!(w, "impl Default for {} {{", def.name);
    let _ = writeln!(w, "    fn default() -> Self {{");
    let _ = writeln!(w, "        Self {{");
    for f in &wire_fields {
        let _ = writeln!(
            w,
            "            {}: {},",
            rust_field_name(&f.name),
            default_expr(f)?
        );
    }
    for f in &tagged_fields {
        let _ = writeln!(w, "            {}: None,", rust_field_name(&f.name));
    }
    let _ = writeln!(w, "            unknown_tagged_fields: Vec::new(),");
    let _ = writeln!(w, "        }}");
    let _ = writeln!(w, "    }}");
    let _ = writeln!(w, "}}");

    let _ = writeln!(w);
    let _ = writeln!(w, "impl {} {{", def.name);
    if is_top {
        if let Some(key) = msg.api_key {
            let _ = writeln!(w, "    /// This message's api key in Kafka's registry.");
            let _ = writeln!(w, "    pub const API_KEY: i16 = {key};");
        }
        let _ = writeln!(
            w,
            "    /// The lowest schema version this snapshot can speak."
        );
        let _ = writeln!(w, "    pub const MIN_VERSION: i16 = {};", msg.valid.min);
        let _ = writeln!(
            w,
            "    /// The highest schema version this snapshot can speak."
        );
        let _ = writeln!(w, "    pub const MAX_VERSION: i16 = {};", msg.valid.max);
        let _ = writeln!(w);
    }

    // encode
    let _ = writeln!(w, "    /// Encode this `{}` at `version`.", def.name);
    let _ = writeln!(
        w,
        "    pub fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {{"
    );
    for f in &wire_fields {
        let body = encode_field(msg, f)?;
        emit_guarded(w, &f.versions.expr(msg.valid), &body);
    }
    if tagged_fields.is_empty() {
        let _ = writeln!(w, "        if is_flexible(version) {{");
        let _ = writeln!(
            w,
            "            wire::put_tagged_fields(buf, &self.unknown_tagged_fields);"
        );
        let _ = writeln!(w, "        }}");
    } else {
        let _ = writeln!(w, "        if is_flexible(version) {{");
        let _ = writeln!(
            w,
            "            let mut tagged = self.unknown_tagged_fields.clone();"
        );
        for f in &tagged_fields {
            let name = rust_field_name(&f.name);
            let encode = encode_field_value(msg, f, "(*v)")?;
            let mut body = String::new();
            let _ = writeln!(body, "if let Some(v) = &self.{name} {{");
            let _ = writeln!(body, "    let mut tag_data = bytes::BytesMut::new();");
            let _ = writeln!(body, "    {{");
            let _ = writeln!(body, "        let buf = &mut tag_data;");
            for line in encode.lines() {
                let _ = writeln!(body, "        {line}");
            }
            let _ = writeln!(body, "    }}");
            let _ = writeln!(
                body,
                "    tagged.push(RawTaggedField {{ tag: {}, data: tag_data.freeze() }});",
                f.tag.unwrap()
            );
            let _ = write!(body, "}}");
            let mut guarded = String::new();
            emit_guarded(&mut guarded, &f.versions.expr(msg.valid), &body);
            for line in guarded.lines() {
                let _ = writeln!(w, "    {line}");
            }
        }
        let _ = writeln!(w, "            tagged.sort_by_key(|f| f.tag);");
        let _ = writeln!(w, "            wire::put_tagged_fields(buf, &tagged);");
        let _ = writeln!(w, "        }}");
    }
    let _ = writeln!(w, "        Ok(())");
    let _ = writeln!(w, "    }}");

    // decode: three entry points over one body. `decode` keeps its
    // signature (and gains the default bound), `decode_with_limits`
    // takes a policy, `decode_with_budget` joins a bound already in
    // progress so that nesting cannot multiply it.
    let _ = writeln!(w);
    let _ = writeln!(
        w,
        "    /// Decode one `{}`, bounding allocation by the default\n    \
             /// [`Limits`] derived from `buf`'s remaining length.",
        def.name
    );
    let _ = writeln!(
        w,
        "    pub fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {{"
    );
    let _ = writeln!(
        w,
        "        Self::decode_with_limits(buf, version, Limits::default())"
    );
    let _ = writeln!(w, "    }}");
    let _ = writeln!(w);
    let _ = writeln!(w, "    /// Decode one `{}` under `limits`.", def.name);
    let _ = writeln!(
        w,
        "    pub fn decode_with_limits(buf: &mut impl Buf, version: i16, limits: Limits) -> Result<Self, DecodeError> {{"
    );
    let _ = writeln!(
        w,
        "        let mut budget = limits.budget(buf.remaining());"
    );
    let _ = writeln!(
        w,
        "        Self::decode_with_budget(buf, version, &mut budget)"
    );
    let _ = writeln!(w, "    }}");
    let _ = writeln!(w);
    let _ = writeln!(
        w,
        "    /// Decode one `{}` against an existing `budget`.",
        def.name
    );
    let _ = writeln!(
        w,
        "    pub fn decode_with_budget(buf: &mut impl Buf, version: i16, budget: &mut Budget) -> Result<Self, DecodeError> {{"
    );
    let _ = writeln!(w, "        let mut this = Self::default();");
    for f in &wire_fields {
        let body = decode_field(msg, f)?;
        emit_guarded(w, &f.versions.expr(msg.valid), &body);
    }
    if tagged_fields.is_empty() {
        let _ = writeln!(w, "        if is_flexible(version) {{");
        let _ = writeln!(
            w,
            "            this.unknown_tagged_fields = wire::get_tagged_fields_with_budget(buf, budget)?;"
        );
        let _ = writeln!(w, "        }}");
    } else {
        let _ = writeln!(w, "        if is_flexible(version) {{");
        let _ = writeln!(
            w,
            "            for raw in wire::get_tagged_fields_with_budget(buf, budget)? {{"
        );
        for (i, f) in tagged_fields.iter().enumerate() {
            let name = rust_field_name(&f.name);
            let value = decode_value(msg, f)?;
            let keyword = if i == 0 { "if" } else { "} else if" };
            let versions = f.versions.expr(msg.valid);
            let guard = if versions == "true" {
                format!("raw.tag == {}", f.tag.unwrap())
            } else {
                format!("raw.tag == {} && ({versions})", f.tag.unwrap())
            };
            let _ = writeln!(w, "                {keyword} {guard} {{");
            let _ = writeln!(w, "                    let mut tag_data = raw.data;");
            let _ = writeln!(w, "                    let buf = &mut tag_data;");
            let mut body = String::new();
            let _ = writeln!(body, "this.{name} = Some({value});");
            let _ = writeln!(
                body,
                "if buf.has_remaining() {{\n    return Err(DecodeError::InvalidLength(\n        i64::try_from(buf.remaining()).unwrap_or(i64::MAX),\n    ));\n}}"
            );
            for line in body.lines() {
                let _ = writeln!(w, "                    {line}");
            }
        }
        let _ = writeln!(w, "                }} else {{");
        let _ = writeln!(
            w,
            "                    budget.push(&mut this.unknown_tagged_fields, raw)?;"
        );
        let _ = writeln!(w, "                }}");
        let _ = writeln!(w, "            }}");
        let _ = writeln!(w, "        }}");
    }
    let _ = writeln!(w, "        Ok(this)");
    let _ = writeln!(w, "    }}");
    let _ = writeln!(w, "}}");

    // The generic spine: every top-level keyed message implements
    // crate::Message by delegating to the inherent methods above.
    if is_top {
        if let Some(key) = msg.api_key {
            let _ = writeln!(w);
            let _ = writeln!(w, "impl crate::Message for {} {{", def.name);
            let _ = writeln!(w, "    const API_KEY: i16 = {key};");
            let _ = writeln!(w, "    const MIN_VERSION: i16 = {};", msg.valid.min);
            let _ = writeln!(w, "    const MAX_VERSION: i16 = {};", msg.valid.max);
            let _ = writeln!(w);
            let _ = writeln!(
                w,
                "    fn encode(&self, buf: &mut impl BufMut, version: i16) -> Result<(), EncodeError> {{"
            );
            let _ = writeln!(w, "        {}::encode(self, buf, version)", def.name);
            let _ = writeln!(w, "    }}");
            let _ = writeln!(
                w,
                "    fn decode(buf: &mut impl Buf, version: i16) -> Result<Self, DecodeError> {{"
            );
            let _ = writeln!(w, "        {}::decode(buf, version)", def.name);
            let _ = writeln!(w, "    }}");
            let _ = writeln!(
                w,
                "    fn decode_with_limits(buf: &mut impl Buf, version: i16, limits: Limits) -> Result<Self, DecodeError> {{"
            );
            let _ = writeln!(
                w,
                "        {}::decode_with_limits(buf, version, limits)",
                def.name
            );
            let _ = writeln!(w, "    }}");
            let _ = writeln!(w, "}}");
        }
    }
    Ok(())
}

/// Emit `body` wrapped in `if guard { .. }`, folding constant guards.
fn emit_guarded(w: &mut String, guard: &str, body: &str) {
    match guard {
        "false" => {}
        "true" => {
            for line in body.lines() {
                let _ = writeln!(w, "        {line}");
            }
        }
        cond => {
            let _ = writeln!(w, "        if {cond} {{");
            for line in body.lines() {
                let _ = writeln!(w, "            {line}");
            }
            let _ = writeln!(w, "        }}");
        }
    }
}

fn range_doc(r: VersionRange) -> String {
    if r.max == i16::MAX {
        format!("{}+", r.min)
    } else {
        format!("{}-{}", r.min, r.max)
    }
}

// --- naming -----------------------------------------------------------------

fn snake_case(name: &str) -> String {
    let mut out = String::new();
    let chars: Vec<char> = name.chars().collect();
    for (i, &c) in chars.iter().enumerate() {
        if c.is_ascii_uppercase() {
            let prev_lower =
                i > 0 && (chars[i - 1].is_ascii_lowercase() || chars[i - 1].is_ascii_digit());
            let next_lower = i > 0
                && chars[i - 1].is_ascii_uppercase()
                && chars.get(i + 1).is_some_and(|n| n.is_ascii_lowercase());
            if prev_lower || next_lower {
                out.push('_');
            }
            out.push(c.to_ascii_lowercase());
        } else {
            out.push(c);
        }
    }
    out
}

const KEYWORDS: &[&str] = &[
    "as", "async", "await", "box", "break", "const", "continue", "crate", "do", "dyn", "else",
    "enum", "extern", "false", "final", "fn", "for", "if", "impl", "in", "let", "loop", "macro",
    "match", "mod", "move", "mut", "override", "priv", "pub", "ref", "return", "static", "struct",
    "super", "trait", "true", "try", "type", "unsafe", "use", "where", "while", "yield",
];

fn rust_field_name(name: &str) -> String {
    let snake = snake_case(name);
    if KEYWORDS.contains(&snake.as_str()) {
        format!("r#{snake}")
    } else {
        snake
    }
}

// --- types ------------------------------------------------------------------

fn base_rust_type(ftype: &FieldType) -> String {
    match ftype {
        FieldType::Bool => "bool".into(),
        FieldType::Int8 => "i8".into(),
        FieldType::Int16 => "i16".into(),
        FieldType::Uint16 => "u16".into(),
        FieldType::Int32 => "i32".into(),
        FieldType::Uint32 => "u32".into(),
        FieldType::Int64 => "i64".into(),
        FieldType::Float64 => "f64".into(),
        FieldType::Uuid => "[u8; 16]".into(),
        FieldType::String => "String".into(),
        FieldType::Bytes | FieldType::Records => "bytes::Bytes".into(),
        FieldType::Struct(n) => n.clone(),
        FieldType::Array(inner) => format!("Vec<{}>", base_rust_type(inner)),
    }
}

fn rust_type(f: &Field) -> String {
    let base = base_rust_type(&f.ftype);
    if f.nullable.is_some() {
        format!("Option<{base}>")
    } else {
        base
    }
}

// --- defaults ----------------------------------------------------------------

fn default_str(f: &Field) -> Option<String> {
    match &f.default {
        Some(Value::String(s)) => Some(s.clone()),
        Some(Value::Number(n)) => Some(n.to_string()),
        Some(Value::Bool(b)) => Some(b.to_string()),
        _ => None,
    }
}

fn parse_int_default(s: &str) -> Result<i128> {
    let s = s.trim();
    if let Some(hex) = s.strip_prefix("0x") {
        Ok(i128::from_str_radix(hex, 16)?)
    } else if let Some(hex) = s.strip_prefix("-0x") {
        Ok(-i128::from_str_radix(hex, 16)?)
    } else {
        Ok(s.parse()?)
    }
}

fn default_expr(f: &Field) -> Result<String> {
    let dflt = default_str(f);
    let is_null = dflt.as_deref() == Some("null");
    if is_null && f.nullable.is_none() {
        bail!("field {} has default null but no nullableVersions", f.name);
    }
    let inner = match &f.ftype {
        FieldType::Bool => dflt.unwrap_or_else(|| "false".into()),
        FieldType::Int8
        | FieldType::Int16
        | FieldType::Uint16
        | FieldType::Int32
        | FieldType::Uint32
        | FieldType::Int64 => match &dflt {
            Some(s) if !is_null => parse_int_default(s)?.to_string(),
            _ => "0".into(),
        },
        FieldType::Float64 => match &dflt {
            Some(s) if !is_null => format!("{:?}", s.parse::<f64>()?),
            _ => "0.0".into(),
        },
        FieldType::Uuid => "[0u8; 16]".into(),
        FieldType::String => match &dflt {
            Some(s) if !is_null => format!("{s:?}.to_string()"),
            _ => "String::new()".into(),
        },
        FieldType::Bytes | FieldType::Records => "bytes::Bytes::new()".into(),
        FieldType::Struct(_) => "Default::default()".into(),
        FieldType::Array(_) => "Vec::new()".into(),
    };
    Ok(if f.nullable.is_some() {
        if is_null {
            "None".into()
        } else {
            format!("Some({inner})")
        }
    } else {
        inner
    })
}

// --- encode ------------------------------------------------------------------

/// Flexibility test expression for one field (field-level override wins).
fn field_flex_expr(msg: &Message, f: &Field) -> String {
    match f.flexible_override {
        Some(r) => r.expr(msg.valid),
        None => "is_flexible(version)".into(),
    }
}

/// Pick `flex_arm` or `plain_arm` based on the field's flexibility expression,
/// folding constant cases.
fn flex_switch(flex: &str, flex_arm: String, plain_arm: String) -> String {
    match flex {
        "true" => flex_arm,
        "false" => plain_arm,
        cond => format!("if {cond} {{\n    {flex_arm}\n}} else {{\n    {plain_arm}\n}}"),
    }
}

fn encode_field(msg: &Message, f: &Field) -> Result<String> {
    let name = rust_field_name(&f.name);
    encode_field_value(msg, f, &format!("self.{name}"))
}

/// Encode `f` reading its value from `path` (`buf` is the free-variable
/// write target, letting tagged fields shadow it with a side buffer).
fn encode_field_value(msg: &Message, f: &Field, path: &str) -> Result<String> {
    let flex = field_flex_expr(msg, f);
    // Folded over the versions the field is actually on the wire, so
    // a guard that can never fire is not emitted at all.
    let nullable_expr = f.nullable.map(|r| r.expr(msg.valid.intersect(f.versions)));

    let code = match (&f.ftype, &nullable_expr) {
        // Scalars, non-nullable
        (FieldType::Bool, None) => format!("buf.put_u8(u8::from({path}));"),
        (FieldType::Int8, None) => format!("buf.put_i8({path});"),
        (FieldType::Int16, None) => format!("buf.put_i16({path});"),
        (FieldType::Uint16, None) => format!("buf.put_u16({path});"),
        (FieldType::Int32, None) => format!("buf.put_i32({path});"),
        (FieldType::Uint32, None) => format!("buf.put_u32({path});"),
        (FieldType::Int64, None) => format!("buf.put_i64({path});"),
        (FieldType::Float64, None) => format!("buf.put_f64({path});"),
        (FieldType::Uuid, None) => format!("wire::put_uuid(buf, {path});"),
        (FieldType::Struct(_), None) => format!("{path}.encode(buf, version)?;"),
        (FieldType::String, None) => flex_switch(
            &flex,
            format!("wire::put_compact_string(buf, &{path});"),
            format!("wire::put_string(buf, &{path})?;"),
        ),
        (FieldType::Bytes | FieldType::Records, None) => flex_switch(
            &flex,
            format!("wire::put_compact_bytes(buf, &{path});"),
            format!("wire::put_bytes(buf, &{path})?;"),
        ),
        (FieldType::String, Some(nullable)) => {
            let write = flex_switch(
                &flex,
                format!("wire::put_compact_nullable_string(buf, {path}.as_deref());"),
                format!("wire::put_nullable_string(buf, {path}.as_deref())?;"),
            );
            null_guard(&f.name, path, nullable, write)
        }
        (FieldType::Bytes | FieldType::Records, Some(nullable)) => {
            let write = flex_switch(
                &flex,
                format!("wire::put_compact_nullable_bytes(buf, {path}.as_deref());"),
                format!("wire::put_nullable_bytes(buf, {path}.as_deref())?;"),
            );
            null_guard(&f.name, path, nullable, write)
        }
        (FieldType::Array(elem), None) => {
            let put_len = flex_switch(
                &flex,
                format!("wire::put_compact_array_len(buf, Some({path}.len()));"),
                format!("wire::put_array_len(buf, Some({path}.len()))?;"),
            );
            let elem_code = encode_element(msg, f, elem)?;
            format!("{put_len}\nfor item in &{path} {{\n    {elem_code}\n}}")
        }
        (FieldType::Array(elem), Some(nullable)) => {
            let put_some = flex_switch(
                &flex,
                "wire::put_compact_array_len(buf, Some(items.len()));".into(),
                "wire::put_array_len(buf, Some(items.len()))?;".into(),
            );
            let put_none = flex_switch(
                &flex,
                "wire::put_compact_array_len(buf, None);".into(),
                "wire::put_array_len(buf, None)?;".into(),
            );
            let elem_code = encode_element(msg, f, elem)?;
            let none_arm = if nullable == "true" {
                put_none
            } else {
                format!(
                    "if !({nullable}) {{\n    return Err(EncodeError::NullField({:?}));\n}}\n{put_none}",
                    f.name
                )
            };
            format!(
                "match &{path} {{\n    Some(items) => {{\n        {put_some}\n        for item in items {{\n            {elem_code}\n        }}\n    }}\n    None => {{\n        {none_arm}\n    }}\n}}",
            )
        }
        (FieldType::Struct(_), Some(nullable)) => {
            // Kafka serializes a nullable struct as a signed marker
            // byte: -1 for null, 1 followed by the struct's fields.
            let none_arm = if nullable == "true" {
                "buf.put_i8(-1);".to_string()
            } else {
                format!(
                    "if !({nullable}) {{\n    return Err(EncodeError::NullField({:?}));\n}}\nbuf.put_i8(-1);",
                    f.name
                )
            };
            format!(
                "match &{path} {{\n    Some(v) => {{\n        buf.put_i8(1);\n        v.encode(buf, version)?;\n    }}\n    None => {{\n        {none_arm}\n    }}\n}}"
            )
        }
        (other, Some(_)) => bail!("nullable {other:?} not supported (field {})", f.name),
    };
    Ok(code)
}

/// For nullable scalar-ish fields: error when null in a non-nullable version,
/// then run `write` (which handles both Some and None wire forms).
fn null_guard(schema_name: &str, path: &str, nullable: &str, write: String) -> String {
    if nullable == "true" {
        write
    } else {
        format!(
            "if {path}.is_none() && !({nullable}) {{\n    return Err(EncodeError::NullField({schema_name:?}));\n}}\n{write}"
        )
    }
}

fn encode_element(msg: &Message, f: &Field, elem: &FieldType) -> Result<String> {
    let flex = field_flex_expr(msg, f);
    Ok(match elem {
        FieldType::Bool => "buf.put_u8(u8::from(*item));".into(),
        FieldType::Int8 => "buf.put_i8(*item);".into(),
        FieldType::Int16 => "buf.put_i16(*item);".into(),
        FieldType::Uint16 => "buf.put_u16(*item);".into(),
        FieldType::Int32 => "buf.put_i32(*item);".into(),
        FieldType::Uint32 => "buf.put_u32(*item);".into(),
        FieldType::Int64 => "buf.put_i64(*item);".into(),
        FieldType::Float64 => "buf.put_f64(*item);".into(),
        FieldType::Uuid => "wire::put_uuid(buf, *item);".into(),
        FieldType::Struct(_) => "item.encode(buf, version)?;".into(),
        FieldType::String => flex_switch(
            &flex,
            "wire::put_compact_string(buf, item);".into(),
            "wire::put_string(buf, item)?;".into(),
        ),
        FieldType::Bytes => flex_switch(
            &flex,
            "wire::put_compact_bytes(buf, item);".into(),
            "wire::put_bytes(buf, item)?;".into(),
        ),
        other => bail!(
            "array element type {other:?} not supported (field {})",
            f.name
        ),
    })
}

// --- decode ------------------------------------------------------------------

fn decode_field(msg: &Message, f: &Field) -> Result<String> {
    let name = rust_field_name(&f.name);
    let value = decode_value(msg, f)?;
    Ok(format!("this.{name} = {value};"))
}

/// The expression decoding `f`'s value from the free variable `buf`.
fn decode_value(msg: &Message, f: &Field) -> Result<String> {
    let flex = field_flex_expr(msg, f);
    // Folded over the versions the field is actually on the wire, so
    // a guard that can never fire is not emitted at all.
    let nullable_expr = f.nullable.map(|r| r.expr(msg.valid.intersect(f.versions)));

    let value = match (&f.ftype, &nullable_expr) {
        (FieldType::Bool, None) => "wire::get_bool(buf)?".to_string(),
        (FieldType::Int8, None) => "wire::get_i8(buf)?".to_string(),
        (FieldType::Int16, None) => "wire::get_i16(buf)?".to_string(),
        (FieldType::Uint16, None) => "wire::get_u16(buf)?".to_string(),
        (FieldType::Int32, None) => "wire::get_i32(buf)?".to_string(),
        (FieldType::Uint32, None) => "wire::get_u32(buf)?".to_string(),
        (FieldType::Int64, None) => "wire::get_i64(buf)?".to_string(),
        (FieldType::Float64, None) => "wire::get_f64(buf)?".to_string(),
        (FieldType::Uuid, None) => "wire::get_uuid(buf)?".to_string(),
        (FieldType::Struct(n), None) => format!("{n}::decode_with_budget(buf, version, budget)?"),
        (FieldType::Struct(n), Some(nullable)) => {
            let none_val = if nullable == "true" {
                "None".to_string()
            } else {
                format!(
                    "{{\n    if !({nullable}) {{\n        return Err(DecodeError::InvalidLength(-1));\n    }}\n    None\n}}"
                )
            };
            format!(
                "if wire::get_i8(buf)? < 0 {{\n    {none_val}\n}} else {{\n    Some({n}::decode_with_budget(buf, version, budget)?)\n}}"
            )
        }
        (FieldType::String, None) => flex_switch(
            &flex,
            "wire::get_compact_string(buf)?".into(),
            "wire::get_string(buf)?".into(),
        ),
        (FieldType::Bytes | FieldType::Records, None) => {
            let read = flex_switch(
                &flex,
                "wire::get_compact_nullable_bytes(buf)?".into(),
                "wire::get_nullable_bytes(buf)?".into(),
            );
            format!(
                "{{\n    let raw = {read};\n    match raw {{\n        Some(v) => v,\n        None => return Err(DecodeError::InvalidLength(-1)),\n    }}\n}}"
            )
        }
        (FieldType::String, Some(nullable)) => {
            let read = flex_switch(
                &flex,
                "wire::get_compact_nullable_string(buf)?".into(),
                "wire::get_nullable_string(buf)?".into(),
            );
            nullable_check(&read, nullable)
        }
        (FieldType::Bytes | FieldType::Records, Some(nullable)) => {
            let read = flex_switch(
                &flex,
                "wire::get_compact_nullable_bytes(buf)?".into(),
                "wire::get_nullable_bytes(buf)?".into(),
            );
            nullable_check(&read, nullable)
        }
        (FieldType::Array(elem), nullable) => {
            let read_len = flex_switch(
                &flex,
                "wire::get_compact_array_len(buf)?".into(),
                "wire::get_array_len(buf)?".into(),
            );
            // `n` is a wire count and never sizes the allocation: the
            // vector grows from the elements that actually arrive, and
            // every growth is charged to the shared budget first. A
            // struct element also has to consume input — a zero-width
            // element would turn a hostile count into a spin.
            let push = match &**elem {
                FieldType::Struct(_) => {
                    let decode = decode_element(msg, f, elem)?;
                    format!(
                        "let mark = buf.remaining();\n                let item = {decode};\n                budget.progress(mark, buf.remaining())?;\n                budget.push(&mut items, item)?;"
                    )
                }
                // Every primitive codec consumes at least one byte, so
                // progress needs no check here.
                _ => {
                    let decode = decode_element(msg, f, elem)?;
                    format!("budget.push(&mut items, {decode})?;")
                }
            };
            let some_arm = format!(
                "Some(n) => {{\n            let mut items = Vec::new();\n            for _ in 0..n {{\n                {push}\n            }}\n            {}\n        }}",
                if nullable.is_some() {
                    "Some(items)"
                } else {
                    "items"
                }
            );
            let none_arm = match nullable {
                None => "None => return Err(DecodeError::InvalidLength(-1)),".to_string(),
                Some(cond) if cond == "true" => "None => None,".to_string(),
                Some(cond) => format!(
                    "None => {{\n            if !({cond}) {{\n                return Err(DecodeError::InvalidLength(-1));\n            }}\n            None\n        }}"
                ),
            };
            format!(
                "{{\n    let len = {read_len};\n    match len {{\n        {none_arm}\n        {some_arm}\n    }}\n}}"
            )
        }
        (other, Some(_)) => bail!("nullable {other:?} not supported (field {})", f.name),
    };
    Ok(value)
}

/// Wrap a nullable read with a strictness check: null is only legal in
/// versions where the schema allows it.
fn nullable_check(read: &str, nullable: &str) -> String {
    if nullable == "true" {
        read.to_string()
    } else {
        format!(
            "{{\n    let raw = {read};\n    if raw.is_none() && !({nullable}) {{\n        return Err(DecodeError::InvalidLength(-1));\n    }}\n    raw\n}}"
        )
    }
}

fn decode_element(msg: &Message, f: &Field, elem: &FieldType) -> Result<String> {
    let flex = field_flex_expr(msg, f);
    Ok(match elem {
        FieldType::Bool => "wire::get_bool(buf)?".into(),
        FieldType::Int8 => "wire::get_i8(buf)?".into(),
        FieldType::Int16 => "wire::get_i16(buf)?".into(),
        FieldType::Uint16 => "wire::get_u16(buf)?".into(),
        FieldType::Int32 => "wire::get_i32(buf)?".into(),
        FieldType::Uint32 => "wire::get_u32(buf)?".into(),
        FieldType::Int64 => "wire::get_i64(buf)?".into(),
        FieldType::Float64 => "wire::get_f64(buf)?".into(),
        FieldType::Uuid => "wire::get_uuid(buf)?".into(),
        FieldType::Struct(n) => format!("{n}::decode_with_budget(buf, version, budget)?"),
        FieldType::String => flex_switch(
            &flex,
            "wire::get_compact_string(buf)?".into(),
            "wire::get_string(buf)?".into(),
        ),
        other => bail!(
            "array element type {other:?} not supported (field {})",
            f.name
        ),
    })
}
